### ISSUE TITLE
for the first hit of what drugs may treat Type 2 Diabetes Mellitus Glipizide is listed first. Under the Evidence hyperlink I clicked on  "Sources" where I found a list of the sources used presumably to get info on the association between T2D and Glipizide. When I clicked on the hyperlinks eg ChEMBL, I was taken to the start pg for ChEMBL but what I expected was that I'd be taken to the ChEMBL page for the drug I was exploring, Glipizide https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL1073/   -Maureen 

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#418] opened 2023-07-11 21:54 UTC

**Comment by andrewsu** [comment] 2023-07-13 22:00
closing as a duplicate of #231

**Closed by andrewsu** 2023-07-13 22:00 UTC
