### ISSUE TITLE
null primary knowledge source is output

### ISSUE THREAD

**Issue by edeutsch** [NCATSTranslator/Feedback#627] opened 2023-11-03 16:42 UTC
In this query:
https://arax.ci.transltr.io/?r=56372c55-b532-4017-b389-ce1fbc9199f5

ARAX is getting dinged for invalid TRAPI:
https://arax.ci.transltr.io/?r=41b109cb-28df-458a-8fcd-6a2c2c328d9b

But the error stems from this edge that ARAX received from service provider:
```
        "infores:service-provider-trapi:PUBCHEM.COMPOUND:5918--biolink:affects--biolink:causes--increased--activity_or_abundance--NCBIGene:158--None": {
          "attributes": [
            {
              "attribute_source": "infores:text-mining-provider-targeted",
              "attribute_type_id": "biolink:primary_knowledge_source",
              "attributes": null,
              "description": null,
              "original_attribute_name": null,
              "value": "infores:text-mining-provider-targeted",
              "value_type_id": "biolink:InformationResource",
              "value_url": null
            },
            {
              "attribute_source": "infores:text-mining-provider-targeted",
              "attribute_type_id": "biolink:supporting_data_source",
              "attributes": null,
              "description": null,
              "original_attribute_name": null,
              "value": "infores:pubmed",
              "value_type_id": "biolink:InformationResource",
              "value_url": null
            },
            {
              "attribute_source": "infores:text-mining-provider-targeted",
              "attribute_type_id": "biolink:evidence_count",
              "attributes": null,
              "description": null,
              "original_attribute_name": null,
              "value": 1,
              "value_type_id": "biolink:EvidenceCount",
              "value_url": null
            },
            {
              "attribute_source": "infores:text-mining-provider-targeted",
              "attribute_type_id": "biolink:extraction_confidence_score",
              "attributes": null,
              "description": null,
              "original_attribute_name": null,
              "value": 0.993869164229577,
              "value_type_id": "biolink:ConfidenceLevel",
              "value_url": null
            },
            {
              "attribute_source": "infores:pubmed",
              "attribute_type_id": "biolink:publications",
              "attributes": null,
              "description": null,
              "original_attribute_name": null,
              "value": [
                "PMC:3298879"
              ],
              "value_type_id": "biolink:Uriorcurie",
              "value_url": null
            },
            {
              "attribute_source": "infores:text-mining-provider-targeted",
              "attribute_type_id": "biolink:has_supporting_study_result",
              "attributes": [
                {
                  "attribute_source": "infores:text-mining-provider-targeted",
                  "attribute_type_id": "biolink:supporting_text",
                  "attributes": null,
                  "description": null,
                  "original_attribute_name": null,
                  "value": "The mRNA level of the gene encoding ASase (potassium-independent isoform) increased from 10 DAP to 18 DAP in this experiment (Fig. 3).",
                  "value_type_id": "EDAM:data_3671",
                  "value_url": null
                },
                {
                  "attribute_source": "infores:pubmed",
                  "attribute_type_id": "biolink:publications",
                  "attributes": null,
                  "description": null,
                  "original_attribute_name": null,
                  "value": "PMC:3298879",
                  "value_type_id": "biolink:Uriorcurie",
                  "value_url": "https://pubmed.ncbi.nlm.nih.gov/PMC3298879/"
                },
                {
                  "attribute_source": "infores:pubmed",
                  "attribute_type_id": "biolink:supporting_text_located_in",
                  "attributes": null,
                  "description": null,
                  "original_attribute_name": null,
                  "value": "RESULTS",
                  "value_type_id": "IAO_0000314",
                  "value_url": null
                },
                {
                  "attribute_source": "infores:text-mining-provider-targeted",
                  "attribute_type_id": "biolink:extraction_confidence_score",
                  "attributes": null,
                  "description": null,
                  "original_attribute_name": null,
                  "value": 0.993869164229577,
                  "value_type_id": "EDAM:data_1772",
                  "value_url": null
                },
                {
                  "attribute_source": "infores:text-mining-provider-targeted",
                  "attribute_type_id": "biolink:subject_location_in_text",
                  "attributes": null,
                  "description": null,
                  "original_attribute_name": null,
                  "value": "102|105",
                  "value_type_id": "SIO:001056",
                  "value_url": null
                },
                {
                  "attribute_source": "infores:text-mining-provider-targeted ",
                  "attribute_type_id": "biolink:object_location_in_text",
                  "attributes": null,
                  "description": null,
                  "original_attribute_name": null,
                  "value": "36|41",
                  "value_type_id": "SIO:001056",
                  "value_url": null
                },
                {
                  "attribute_source": "infores:pubmed",
                  "attribute_type_id": "biolink:supporting_document_year",
                  "attributes": null,
                  "description": null,
                  "original_attribute_name": null,
                  "value": 2008,
                  "value_type_id": "UO:0000036",
                  "value_url": null
                }
              ],
              "description": null,
              "original_attribute_name": null,
              "value": "tmkp:65f2c8343d502b11ef61496dd6fb0a1ce603f26d3a95809e060c3470d9a653e4",
              "value_type_id": "biolink:TextMiningResult",
              "value_url": "https://tmui.text-mining-kp.org/evidence/65f2c8343d502b11ef61496dd6fb0a1ce603f26d3a95809e060c3470d9a653e4"
            }
          ],
          "object": "NCBIGene:158",
          "predicate": "biolink:affects",
          "qualifiers": [
            {
              "qualifier_type_id": "biolink:qualified_predicate",
              "qualifier_value": "biolink:causes"
            },
            {
              "qualifier_type_id": "biolink:object_aspect_qualifier",
              "qualifier_value": "activity_or_abundance"
            },
            {
              "qualifier_type_id": "biolink:object_direction_qualifier",
              "qualifier_value": "increased"
            }
          ],
          "sources": [
            {
              "resource_id": null,                                      <<------------------------------------------
              "resource_role": "primary_knowledge_source",
              "source_record_urls": null,
              "upstream_resource_ids": null
            },
            {
              "resource_id": "infores:text-mining-provider-targeted",
              "resource_role": "aggregator_knowledge_source",
              "source_record_urls": null,
              "upstream_resource_ids": [
                null
              ]
            },
            {
              "resource_id": "infores:service-provider-trapi",
              "resource_role": "aggregator_knowledge_source",
              "source_record_urls": null,
              "upstream_resource_ids": [
                "infores:text-mining-provider-targeted"
              ]
            },
            {
              "resource_id": "infores:arax",
              "resource_role": "aggregator_knowledge_source",
              "source_record_urls": null,
              "upstream_resource_ids": [
                "infores:service-provider-trapi"
              ]
            }
          ],
          "subject": "PUBCHEM.COMPOUND:5918"
        }
```
	
Note that the primary_knowledge_source has a null resource_id, which is not permitted.

Tagging @colleenXu @andrewsu I'm not sure who should be addressing this.

**Comment by andrewsu** [comment] 2023-11-03 21:34
Thanks @edeutsch!  I confirmed that this is a bug on our CI instance (but not PROD).  Created the issue linked above...

**Comment by colleenXu** [comment] 2023-12-19 21:38
This should be addressed in BTE dev/CI since 12/15

**Closed** 2024-06-01 01:00 UTC
