### ISSUE TITLE
example diseases don't work

### ISSUE THREAD

**Issue by gglusman** [NCATSTranslator/Feedback#460] opened 2023-08-04 19:52 UTC
All five example diseases lead to "There was an error when processing your query. Please try again."

![image](https://github.com/NCATSTranslator/Feedback/assets/3977332/5489d809-8bb1-4677-85e6-e67bcff9cd71)

**Comment by gprice1129** [comment] 2023-08-05 19:36
We are doing a slight overhaul of how pre-run queries work. This will be fixed as part of that effort.

**Comment by sierra-moxon** [comment] 2023-08-08 22:50
closing this: https://github.com/NCATSTranslator/Feedback/issues/255 as a "duplicate" of this ticket.  I know this is being revamped at the moment and the ticket I link here will be obsolete with that revamping.

**Comment by sstemann** [comment] 2023-09-12 19:55
CI: These two are probably for @MarkDWilliams to troubleshoot

Demo for What chemicals may downregulate:[CHAMP1](https://www.ncbi.nlm.nih.gov/gene/283489) - doesn't seem to load
https://ui.ci.transltr.io/demo/results?l=CHAMP1&i=NCBIGene:283489&t=2&q=b558e797-c054-4e8e-bfc1-a4ffd515698a

Demo for What genes may be upregulated by:[Pregabalin](https://pubchem.ncbi.nlm.nih.gov/compound/5486971) - is still running

https://ui.ci.transltr.io/demo/results?l=Pregabalin&i=PUBCHEM.COMPOUND:5486971&t=3&q=e486acfb-273f-4ba9-8b41-36365abb109b

Demo for What genes may be downregulated by:[Pregabalin](https://pubchem.ncbi.nlm.nih.gov/compound/5486971)
https://ui.ci.transltr.io/demo/results?l=Pregabalin&i=PUBCHEM.COMPOUND:5486971&t=4&q=a5e379b5-2fc1-4a42-a9f0-5f6b2ace7a17

Test:
What chemicals may upregulate:[NGLY1](https://www.ncbi.nlm.nih.gov/gene/55768) - still running
https://ui.test.transltr.io/demo/results?l=NGLY1&i=NCBIGene:55768&t=1&q=7c7b719b-65db-4d04-ac9c-d5dba19508c9

What chemicals may downregulate:[CHAMP1](https://www.ncbi.nlm.nih.gov/gene/283489) - still running
https://ui.test.transltr.io/demo/results?l=CHAMP1&i=NCBIGene:283489&t=2&q=21cd1292-0ff6-462b-9b45-ecd989139269

What chemicals may downregulate:[NGLY1](https://www.ncbi.nlm.nih.gov/gene/55768) - still running
https://ui.test.transltr.io/demo/results?l=NGLY1&i=NCBIGene:55768&t=2&q=efa1cf10-b63f-4130-a059-70e77968d619

What genes may be downregulated by:[Amlodipine](https://pubchem.ncbi.nlm.nih.gov/compound/2162) - nothing loads
https://ui.test.transltr.io/demo/results?l=Amlodipine&i=PUBCHEM.COMPOUND:2162&t=4&q=f0822bc2-4ec3-4ece-9c6a-0a70080041ec

(I ran all the disease ones on prod, but not MVP2, saving this comment now so as not to lose this - some observations on diseases were here #538 and #539)

**Comment by Genomewide** [comment] 2023-09-13 19:33
We are going to rerun all of the queries at 5-minute intervals to try again. That will give us a feel for the number of answers.

**Comment by Genomewide** [comment] 2023-09-13 19:35
@sstemann  I will check all pks before they go up. And we will remove champ1.  I think that a timeout is causing the low number of results. Improving agent is not making the cutoff and I bet the last time I did the exercise they were.

**Comment by gglusman** [comment] 2024-01-11 18:28
Re-testing on 2024/1/11 (test instance). All runs indicate 'submitted Sep 8, 2023'.
chemicals downregulating ADNP: looks fine
chemicals downregulating CHAMP1: **no results available**
chemicals upregulating NGLY1: **takes very long**
genes upregulated/downregulated by pregabalin: both look fine
genes downregulated by amlodipine: **takes very long**

**Comment by gprice1129** [comment] 2024-01-12 05:19
@gglusman we have stopped updating CI and Test example queries because the instability of the system makes this extremely error prone, meaning this requires a lot of effort on our side to verify and re-run queries that failed for some reason or another.

We only update production example queries and test them extensively before releasing, which unfortunately is impossible to verify in the Test environment.

**Comment by sstemann** [comment] 2024-02-15 13:26
works in prod as designed.

**Closed by sstemann** 2024-02-15 13:26 UTC
Labels: UI - display, UI - known issue
