### ISSUE TITLE
Search History Error Message

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#515] opened 2023-09-07 13:03 UTC
Related to #508, since Search History is available with/without logging in, it looks like for queries that I run when Logged In, display an error when I access them through Search History without logging in.  It may just be that Search History shouldn't be available if you aren't logged in.

Not Logged In:
<img width="952" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/b28c63a4-7861-4282-9835-4667cb09097c">

Same Mondo/PK when Logged In:
<img width="945" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/ea95acfb-079b-4994-9580-25e11563130c">

I guess its related to main vs demo  in the URL

**Comment by dnsmith124** [comment] 2023-09-07 13:51
Your diagnosis of the issue is correct here @sstemann. I'm going to hide the search history for non-logged in users for now, since arbitrary queries aren't accessible to them anymore anyway. Then in an upcoming update we'll likely adjust the search history to be attached to the user's account rather than their browser as stated in [#508](https://github.com/NCATSTranslator/Feedback/issues/508)

**Comment by dnsmith124** [comment] 2023-09-12 15:46
Confirmed that search history no longer displays for non-logged in users on test. 

Closing!

**Closed by dnsmith124** 2023-09-12 15:46 UTC
Labels: UI - feature request
