### ISSUE TITLE
The only edge is "lithium decreases CASP3 activity", which is the opposite of what is asked for.  There are not other paths that might be accounting for this...

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#154] opened 2023-03-28 14:12 UTC
## Steps to reproduce:
Ask: What gene is upregulated by Lithium?
Find Casp3 in the list

**Comment by sierra-moxon** [comment] 2023-03-31 16:05
robokop

![Image](https://user-images.githubusercontent.com/4561292/229172421-fd02f695-57c4-4e12-bb57-e06508ccde28.png)

**Comment by sierra-moxon** [comment] 2023-04-21 15:47
retested - this is no longer the only edge returned, but it does still show up if you filter the results (it is a low-ranked answer).

**Comment by capasfield** [comment] 2023-04-28 16:53
From TAQA -
Discuss in architecture - which ARAs are producing these results?

**Comment by dnsmith124** [comment] 2023-05-02 19:13
The bug that was causing the above share link to error out for some users has been resolved on CI! 

https://ui.ci.transltr.io/results?l=Lithium&t=3&q=c76c0987-e2af-4902-9a1c-d94a98fc86b7

**Comment by sstemann** [comment] 2023-05-08 16:00
Based on that UI URL above, here is the [ARAX Interface view](https://arax.ncats.io/?r=c76c0987-e2af-4902-9a1c-d94a98fc86b7).  Which you will see this result is coming from Robokop, and is not limited to CASP3:

![image](https://user-images.githubusercontent.com/38321826/236872036-325eb2d6-2885-41cf-a460-f7115a15e776.png)

![image](https://user-images.githubusercontent.com/38321826/236872107-957b3c94-7705-428b-a751-c6cb928e842e.png)

![image](https://user-images.githubusercontent.com/38321826/236872251-07a5f966-c346-4e73-92d4-a069ded22e90.png)

![image](https://user-images.githubusercontent.com/38321826/236872385-05b236ba-3640-4e95-bd47-cb9cba9298b1.png)

![image](https://user-images.githubusercontent.com/38321826/236872445-1a9a03f5-aa59-47fd-bf60-2cfa293b622d.png)

**Comment by cbizon** [comment] 2023-05-09 15:55
This is being caused by some bugs in ARAGORN's current rules.

**Comment by sstemann** [comment] 2023-06-28 17:46
looks like Robokop doesn't respond to this query in CI, but ARAGORN does and has the opposite direction

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/f1b0ccfb-18c9-425c-9dda-1d666a344c7d)

will the fix be pushed to CI by June 30?

**Comment by cbizon** [comment] 2023-07-20 01:13
New CI PK: 24f485e9-3600-4697-af0a-bae881ec3ea8

I think that Aragorn and Robokop are now no longer returning opposite edges (though they do return other CASP3 paths).

But it looks like ARAX is:
<img width="1622" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/10744350/fc72b9e8-f61d-414d-9d46-6685246ed63d">

It looks like the edge is coming from molepro, but I'm also confused b/c I don't think that this is a valid predicate any more?

**Comment by edeutsch** [comment] 2023-07-20 02:20
well, this PK is failing validation first of all.
https://arax.ncats.io/api/arax/v1.4/response/95bfe9f9-1418-4c83-9048-c384cca00902
```
        "infores:molepro:PUBCHEM.COMPOUND:3028194--biolink:affects--None--None--None--NCBIGene:2932--infores:gtopdb": {
          "attributes": [
            {
              "attribute_source": "infores:molepro",
              "attribute_type_id": "biolink:knowledge_level",
              "attributes": null,
              "description": null,
              "original_attribute_name": "biolink:knowledge_level",
              "value": "unspecified",
              "value_type_id": "string",
              "value_url": null
            },
            {
              "attribute_source": "infores:molepro",
              "attribute_type_id": "biolink:agent_type",
              "attributes": null,
              "description": null,
              "original_attribute_name": "biolink:agent_type",
              "value": "unspecified",
              "value_type_id": "string",
              "value_url": null
            },
            {
              "attribute_source": null,
              "attribute_type_id": "biolink:publications",
              "attributes": null,
              "description": null,
              "original_attribute_name": null,
              "value": [
                "PMID:11162580"
              ],
              "value_type_id": "linkml:Uriorcurie",
              "value_url": null
            }
          ],
          "object": "NCBIGene:2932",
          "predicate": "biolink:affects",
          "qualifiers": [
            {
              "qualifier_type_id": "object_aspect_qualifier",
              "qualifier_value": "activity"
            }
          ],
          "sources": [
            {
              "resource_id": "infores:gtopdb",
              "resource_role": "primary_knowledge_source",
              "source_record_urls": null,
              "upstream_resource_ids": null
            },
            {
              "resource_id": "infores:molepro",
              "resource_role": "aggregator_knowledge_source",
              "source_record_urls": null,
              "upstream_resource_ids": [
                "infores:gtopdb"
              ]
            },
            {
              "resource_id": "infores:arax",
              "resource_role": "aggregator_knowledge_source",
              "source_record_urls": null,
              "upstream_resource_ids": [
                "infores:molepro"
              ]
            }
          ],
          "subject": "PUBCHEM.COMPOUND:3028194"
        },
```

This fails because an edge from MolePro has problem:
```
Critical:
* Trapi:
=> Schema validation error
	$ global
		# v1.4.2:
		- component | reason: 
			KnowledgeGraph | 'object_aspect_qualifier' does not match '^biolink:[a-z][a-z_]*$'
```

But I suppose that's not the problem you're asking about.

The descreases_activity_of also seems to be coming from MolePro:
```
        "infores:molepro:PUBCHEM.COMPOUND:3028194--biolink:decreases_activity_of--None--None--None--NCBIGene:111--infores:ctd": {
          "attributes": [
            {
              "attribute_source": "infores:ctd",
              "attribute_type_id": "biolink:relation",
              "attributes": [],
              "description": null,
              "original_attribute_name": "Relation",
              "value": "results in decreased activity of",
              "value_type_id": "string",
              "value_url": null
            },
            {
              "attribute_source": "infores:molepro",
              "attribute_type_id": "biolink:knowledge_level",
              "attributes": null,
              "description": null,
              "original_attribute_name": "biolink:knowledge_level",
              "value": "knowledge_assertion",
              "value_type_id": "string",
              "value_url": null
            },
            {
              "attribute_source": "infores:molepro",
              "attribute_type_id": "biolink:agent_type",
              "attributes": null,
              "description": null,
              "original_attribute_name": "biolink:agent_type",
              "value": "manual_agent",
              "value_type_id": "string",
              "value_url": null
            },
            {
              "attribute_source": null,
              "attribute_type_id": "biolink:publications",
              "attributes": null,
              "description": null,
              "original_attribute_name": null,
              "value": [
                "PMID:19922557"
              ],
              "value_type_id": "linkml:Uriorcurie",
              "value_url": null
            }
          ],
          "object": "NCBIGene:111",
          "predicate": "biolink:decreases_activity_of",
          "qualifiers": [],
          "sources": [
            {
              "resource_id": "infores:ctd",
              "resource_role": "primary_knowledge_source",
              "source_record_urls": null,
              "upstream_resource_ids": null
            },
            {
              "resource_id": "infores:molepro",
              "resource_role": "aggregator_knowledge_source",
              "source_record_urls": null,
              "upstream_resource_ids": [
                "infores:ctd"
              ]
            },
            {
              "resource_id": "infores:arax",
              "resource_role": "aggregator_knowledge_source",
              "source_record_urls": null,
              "upstream_resource_ids": [
                "infores:molepro"
              ]
            }
          ],
          "subject": "PUBCHEM.COMPOUND:3028194"
        },
```

@vdancik might be able to fix?

**Comment by saramsey** [comment] 2023-08-01 21:20
I concur, this doesn't seem to be an issue in RTX-KG2c, but rather, MolPro.

**Comment by sierra-moxon** [comment] 2024-05-17 00:24
fixed; closing.

**Closed by sierra-moxon** 2024-05-17 00:24 UTC
Labels: bug, Friends and Family, opposite of what I asked for
