### ISSUE TITLE
Truncate FUNCTION section

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#250] opened 2023-06-05 17:11 UTC
## Screenshots:
![screenshot](https://raw.githubusercontent.com/TranslatorSRI/IssueScreenshots/main/screenshot_20230605171153314554.jpeg)

**Comment by swandle06** [comment] 2023-06-05 17:14
When you open a single result box to view the evidence for a gene, it displays a "FUNCTION" for that gene, which can sometimes be voluminous. Could that be truncated by default with an icon to expand it? Otherwise, you sometimes have to scroll a bit to get to the network and pathway diagrams.

**Comment by sierra-moxon** [comment] 2023-06-05 19:54
duplicate of https://github.com/NCATSTranslator/Feedback/issues/112

**Closed by sierra-moxon** 2023-06-05 19:54 UTC
