### ISSUE TITLE
Looks like the ARAX Edge Analysis Graph Isn't displayed in the UI (when obsoleted predicates are used)

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#330] opened 2023-06-07 15:00 UTC
MVP1 for Multiple Sclerosis:  https://ui.test.transltr.io/results?l=Multiple%20Sclerosis&t=0&q=bc963cad-e2e3-4200-b401-d757597b4766
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/2e3e4b13-7b91-45bb-b55b-6c8ce4fe3502)

To see the edge analysis graph in the ARAX GUI:
1. Click here:  https://arax.ci.transltr.io/?r=bc963cad-e2e3-4200-b401-d757597b4766
2. Go to message id column for ARAX row and click the link
3. In the left pane, go to Results
4. Expand result 7, GLATIRAMER ACETATE
5. On the treats edge go to  the Aux Graph link
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/0633a960-3361-40ea-a45d-2e49bbd47757)

7. View all the paths
. 
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/c137fe1c-086b-4cca-a4fc-4a2836252a74)

**Comment by edeutsch** [comment] 2023-06-13 04:02
It is a known bug that ARAX support graphs are sometimes using obsoleted predicates. A fix is in the works, but completion is still unclear.

**Comment by sstemann** [comment] 2023-06-28 17:26
https://github.com/NCATSTranslator/Feedback/issues/118

**Comment by edeutsch** [comment] 2023-06-28 18:47
This issue was discussed again today at our group meeting and it is high prio to fix, but somewhat difficult. 
Work is ongoing. @saramsey

**Comment by sandrine-muller-research** [comment] 2023-10-06 19:41
Retested today and reproduced on [PROD](https://ui.transltr.io/main/results?l=Multiple%20Sclerosis&i=MONDO:0005301&t=0&q=7a9df8f8-b08d-483e-bcba-f01d2903579f) 
<img width="1035" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/22616936/b7db7803-1fd3-440b-9094-05c9569c8173">
<img width="1169" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/22616936/6ee9f06b-dc8c-4c38-8855-8d421ad4593e">
<img width="1171" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/22616936/eef3c919-5393-4a2c-b392-eb8b8ba71c34">

**Comment by Genomewide** [comment] 2023-10-09 19:22
@gprice1129 there are multiple sn ID. Here is the top level data for this one:

                    {
                        "id": null,
                        "score": null,
                        "essence": "GLATIRAMER ACETATE",
                        "analyses": [
                            {
                                "score": 0.9618372171563662,
                                "attributes": null,
                                "resource_id": "infores:rtx-kg2",
                                "edge_bindings": {
                                    "t_edge": [
                                        {
                                            "id": "infores:molepro:CHEMBL.COMPOUND:CHEMBL1201507--biolink:treats--None--None--None--MONDO:0005301--infores:chembl",
                                            "attributes": null
                                        },
                                        {
                                            "id": "infores:molepro:CHEMBL.COMPOUND:CHEMBL1201507--biolink:treats--None--None--None--MONDO:0005314--infores:chembl",
                                            "attributes": null
                                        },
                                        {
                                            "id": "infores:rtx-kg2:CHEMBL.COMPOUND:CHEMBL1201507--biolink:treats--None--None--None--MONDO:0005284--infores:chembl",
                                            "attributes": null
                                        },
                                        {
                                            "id": "infores:spoke:CHEMBL.COMPOUND:CHEMBL1201507--biolink:treats--None--None--None--MONDO:0005301--infores:chembl",
                                            "attributes": null
                                        },
                                        {
                                            "id": "infores:rtx-kg2:CHEMBL.COMPOUND:CHEMBL1201507--biolink:treats--None--None--None--MONDO:0005314--infores:chembl",
                                            "attributes": null
                                        },
                                        {
                                            "id": "infores:rtx-kg2:CHEMBL.COMPOUND:CHEMBL1201507--biolink:treats--None--None--None--MONDO:0005301--infores:chembl",
                                            "attributes": null
                                        },
                                        {
                                            "id": "infores:molepro:CHEMBL.COMPOUND:CHEMBL1201507--biolink:treats--None--None--None--MONDO:0005284--infores:chembl",
                                            "attributes": null
                                        }
                                    ]
                                },
                                "scoring_method": null,
                                "support_graphs": [
                                    "aux_graph_N1_605;N1_656;N1_77",
                                    "aux_graph_49_option_group-subclass:on--on"
                                ]
                            }
                        ],
                        "row_data": [
                            0.962,
                            "GLATIRAMER ACETATE",
                            "['biolink:Drug', 'biolink:SmallMolecule']"
                        ],
                        "confidence": null,
                        "score_name": null,
                        "description": "No description available",
                        "resource_id": "ARAX",
                        "result_group": null,
                        "node_bindings": {
                            "on": [
                                {
                                    "id": "MONDO:0005301",
                                    "query_id": null,
                                    "attributes": null
                                },
                                {
                                    "id": "MONDO:0005314",
                                    "query_id": null,
                                    "attributes": null
                                },
                                {
                                    "id": "MONDO:0005284",
                                    "query_id": null,
                                    "attributes": null
                                }
                            ],
                            "sn": [
                                {
                                    "id": "CHEMBL.COMPOUND:CHEMBL1201507",
                                    "query_id": null,
                                    "attributes": null
                                }
                            ]
                        },
                        "score_direction": null,
                        "essence_category": "['biolink:Drug', 'biolink:SmallMolecule']",
                        "normalized_score": 95.2,
                        "result_group_similarity_score": null
                    },

**Comment by gprice1129** [comment] 2023-10-11 15:01
@edeutsch can you please just confirm there is no action item here for the UI.

**Comment by dkoslicki** [comment] 2023-10-11 18:41
Question: is this due to the string that looks similar to `aux_graph_45_creative_DTD_option_group_0`? Isn't that just the name of the support graph? Running just the creative portion in CI: https://arax.ci.transltr.io/?r=173060, as well as the original query in CI: https://arax.ci.transltr.io/?r=173052 I can confirm that this predicate is no longer present. So should be fixed in the next PROD release

**Comment by edeutsch** [comment] 2023-10-12 03:51
Our two-month old code in PROD has finally been replaced with much newer code today with the deployment by ITRB. and on arax.ncats.io.

So if there is some thought that maybe this problem is fixed in our latest code, I suggest rerunning the query. All of our instances are now running the latest code, as of a few hours ago.

**Comment by sandrine-muller-research** [comment] 2023-10-12 13:46
Triaged it to be tested on PROD at next testing session. Thank you.

**Comment by saramsey** [comment] 2023-10-21 23:14
Hi all, I'm attempting to reproduce the problem in the current production (`ui.transltr.io`) web interface, and I'm unsure how to do it. I clicked on "drug treats disease" and typed "multiple sclerosis" in the search box. I got back some results, and used the string filter to find the result for "Glatiramer acetate". In that result, only see one drug-treats-disease path (from Improving Agent) and it doesn't seem to have any connection to ARAX. Please forgive my ineptness with using the Translator UI. But if someone could help me to reproduce the problem, I could investigate where we are with a fix. In particular, I am unsure how to go from a Translator UI result to a PK. Thank you so much in advance for any help.


![Screenshot 2023-10-21 at 4 13 33 PM](https://github.com/NCATSTranslator/Feedback/assets/5562107/d3242a52-98bc-4e6b-90c0-d2c568d6cf19)

**Comment by saramsey** [comment] 2023-10-22 04:23
Hi all, @andrewsu helped me with my question. Thank you.

**Comment by codewarrior2000** [comment] 2023-10-22 17:43
@saramsey thank you for sharing the trick here.
It's hasn't been exactly obvious that the PK from the UI and the TRAPI Response identifier in the ARAX UI are the same thing, both of which are more commonly known as a UUID, [Universally unique identifier](https://en.wikipedia.org/wiki/Universally_unique_identifier).

**Comment by saramsey** [comment] 2024-01-24 18:59
Since this is kind of an xDTD issue (I think?), I'm taking myself off of this issue since @dkoslicki has point on xDTD (@dkoslicki please let me know if I am being too hasty in removing myself from this issue).

**Closed** 2024-02-12 16:35 UTC
Labels: biolink, test on PROD
