### ISSUE TITLE
Wrong directionality - chemical is regulated by a gene

### ISSUE THREAD

**Issue by ccolvis** [NCATSTranslator/Feedback#313] opened 2023-06-06 16:21 UTC
https://ui.test.transltr.io/results?l=CRYBA1&t=1&q=e46fc2b9-c2ad4b0d-ba8f-19112ba1eb1a

Query looking for chemicals that regulate a gene, return an answer that "(2s)-2-ammonio-3-[4-(4-hydroxy-3,5-diiodophenoxy)-3,5-diiodophenyl]propanoate _Has Decreased Expression Caused By_ Cryba1" 

The gene should not be decreasing expression of a chemical.

**Comment by Genomewide** [comment] 2023-07-05 16:55
The link above does not return results in UI or ARAX. 

Here is another example https://ui.ci.transltr.io/results?l=Acetaminophen&i=PUBCHEM.COMPOUND:1983&t=3&q=b90aec07-5c51-411b-b223-4e335e552b6c



![Image](https://github.com/NCATSTranslator/Feedback/assets/55069176/daa056ff-211f-40ae-952d-60af36787055)

This one is from improving agent. 


On ARAX the display looks broken as well. 
https://arax.ncats.io/?r=6ac981e7-3ed9-4b0e-8f97-9cad5c8559b8

![Image](https://github.com/NCATSTranslator/Feedback/assets/55069176/cb1c6155-24a0-43b1-a33a-d8d8229f3b63)

**Comment by cbizon** [comment] 2023-07-20 02:23
I reran the original query (chemical upregulates CRYBA1) in CI: 290e9695-8cd2-42ef-9c71-9b7e318b3fe9 and found the same chemical (2-ammoni...) .  But it now appears that the expression is in the right direction (chemical to gene).  I think that Andy's example is also fine  because it says ADRB2 has increased expression caused by Acetaminophen, i.e. the chemical is causing the expression change as expected.

closing

**Closed by cbizon** 2023-07-20 02:23 UTC
Labels: opposite of what I asked for
