### ISSUE TITLE
All contain xxx--treats -- xxx --Phenotype of-- with no Genes as intermediary nodes

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#905] opened 2024-08-06 17:08 UTC
Retested today on [PROD](https://ui.transltr.io/main/results?l=Autism%20Spectrum%20Disorder&i=MONDO:0005258&t=0&q=46913488-480c-4e63-93e6-dde351604a96): I could not find the same problematic paths under Aripiprazole but we do have problematic paths in my opinion (not very clever reasoning, often leading to bad results IMO):
<img width="732" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/22616936/fb022df8-c1a4-43c5-b258-ee42452e41b5">
They all contain xxx--treats -- xxx --Phenotype of-- with no Genes as intermediary nodes

_Originally posted by @sandrine-muller-research in https://github.com/NCATSTranslator/Feedback/issues/357#issuecomment-1751203852_

**Comment by sstemann** [comment] 2024-08-06 17:09
these seem to be BTE results. I believe this is by design but will let BTE respond.

https://ui.transltr.io/main/results?l=Autism%20Spectrum%20Disorder&i=MONDO:0005258&t=0&r=0&q=a85f95bf-80b3-49e6-b42a-cba033fec6f6

**Comment by andrewsu** [comment] 2024-08-06 17:22
I'll take this one too (just to keep @tokebe on some other priorities)...

**Comment by tokebe** [comment] 2024-08-06 17:36
Probably best to direct these kinds of issues to @andrewsu in the future; if it's clearly evident of a bug by all means direct it to me, but otherwise I think it might make more sense for Andrew to receive and delegate these as appropriate.

**Comment by andrewsu** [comment] 2024-08-06 20:31
Yes, everything is operating by design. In https://github.com/biothings/bte_trapi_query_graph_handler/blob/main/data/templateGroups.json#L1-L16, we define the specific templates that the creative mode query is expanded to.  The TRAPI for each template is in https://github.com/biothings/bte_trapi_query_graph_handler/tree/main/data/templates/Drug-treats-Disease. We of course know that the selection of templates and our scoring function can be improved. I'm going to close this issue, but feel free to repoen if anyone has a specific suggestion.  (I'll also note that BTE reports sirolimus with rank 117...)

**Closed by andrewsu** 2024-08-06 20:31 UTC
