### ISSUE TITLE
Monarch Initiative data is not showing up in top query results, despite high answer quality potential

### ISSUE THREAD

**Issue by karafecho** [NCATSTranslator/Feedback#30] opened 2022-10-25 16:46 UTC
The October 2022 QotM identified Monarch Initiative (https://monarchinitiative.org/) as a possible Translator knowledge source. The [Translator landscape survey data sheet](https://docs.google.com/spreadsheets/d/1Ma4U3aY16mJushsW74vf9mWVacFvf7FiTEdlVqaUi5g/edit#gid=0) lists Monarch API (Ranking Agent’s Automat) and Monarch Initiative (SRI’s Reference KG), but it’s not clear if these resources are truly integrated with Translator or simply underutilized. This issue is to suggest that Translator team members (KP and ARA teams) explore this potentially valuable resource and existing Monarch-related Translator knowledge sources.

**Comment by sierra-moxon** [comment] 2022-11-18 06:30
Hi @karafecho - the SRI reference KG is the Monarch graph, and is being served/searched/etc via Plater-deployed API.

I know its been awhile since this issue was raised, but do you have any additional details about the kinds of data that can be found on Monarch, that should be but is currently not exposed (or ranked too low in the search results)?

**Comment by karafecho** [comment] 2022-11-18 15:00
Yes, I am aware that the SRI Reference KG is the Monarch KG, and as I noted, it is listed on the Translator survey data sheet, but as I recall, Translator team members were either unaware of the resource or not fully leveraging it. There also was a question of whether all of the available data (e.g., specific edges) were being exposed as part of Translator. The issue arose during QotM 6.

**Comment by karafecho** [comment] 2022-11-18 15:19
In reviewing this non-specific issue as part of TAQA, what might be helpful is a quick 'tour' of Monarch.

**Comment by sierra-moxon** [comment] 2023-07-10 16:50
duplicate of issue #130 - closing this one as that one has a few more examples that we could possible derive automated tests.

**Closed by sierra-moxon** 2023-07-10 16:50 UTC
