### ISSUE TITLE
Can't search for sem-5 (genes and chemicals name testing)

### ISSUE THREAD

**Issue by sandrine-m** [NCATSTranslator/Feedback#381] opened 2023-06-30 22:40 UTC
I got a list of weirdly named compounds and proteins from unusual [chemical names wikipedia page](https://en.wikipedia.org/wiki/List_of_chemical_compounds_with_unusual_names) and its related sources (e.g. [here](https://www.chm.bris.ac.uk/sillymolecules/sillymols.htm)).

The gene name in question is named sem-5 for Sex muscle abnormal protein 5 in Caenorhabditis elegans. [ARAX synonyms](https://arax.ncats.io/?term=Sem-5%20protein,%20C%20elegans) and Name resolver do have knowedge of this gene. The gene has an NCBI gene ID ([NCBIGene:181055](https://www.ncbi.nlm.nih.gov/gene/181055)). When I search for it in the test UI, I have no match for the name nor for its symbol. I have been trying a few IDs with no success (UniProt, NCBI).

**Comment by sandrine-m** [comment] 2023-06-30 22:47
Not sure this is an autocomplete issue so please feel free to change the labels! Thank you!

**Comment by sandrine-m** [comment] 2023-07-01 10:23
added the ARAX synonyms CI hyperlink as advised by @edeutsch :
[ARAX synonyms for sem-5](https://arax.ci.transltr.io/?term=Sem-5%20protein,%20C%20elegans)

**Comment by sierra-moxon** [comment] 2023-07-03 18:25
resolving as duplicate of #380

**Closed by sierra-moxon** 2023-07-03 18:25 UTC
Labels: autocomplete
