### ISSUE TITLE
Chrug-Strauss Syndrome (CSS) is not found by the search. If I try "CSS" as a search term, unrelated disorders are suggested. If remove the hyphen then the new name for Chrug-Strauss is suggested "eosinophilic granulomatosis with polyangiitis" 

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#39] opened 2022-11-04 17:18 UTC
## Steps to reproduce:
Search for Chrug-Strauss Syndrome

**Comment by sierra-moxon** [comment] 2022-11-18 00:03
closing as a duplicate of #10

**Closed by sierra-moxon** 2022-11-18 00:03 UTC
