### ISSUE TITLE
almost missed the right tab "Sources"

### ISSUE THREAD

**Issue by remontoire-pac** [NCATSTranslator/Feedback#278] opened 2023-06-06 14:19 UTC
![image](https://github.com/NCATSTranslator/Feedback/assets/2120526/184bf4af-edf6-41d7-a7cd-3777ed3210c6)
I love the color scheme in general, so I'm not sure how best to make it more clear there are two tabs "Publications" and "Sources".

While I'm at it, I'm not sure centering (rather than left-justifying) the contents of these columns makes them easier to scan.

**Comment by dnsmith124** [comment] 2023-06-09 16:23
There is a redesign for the tabs that has been user-tested, but I haven't implemented it yet. Assigning this to me and changing status to in progress

**Comment by dnsmith124** [comment] 2023-06-09 16:25
@remontoire-pac  I believe the label for a primary_knowledge_source is provided to us, but since the UI's backend massages the data a bit I'm not sure where to adjust that label upstream. 

@gprice1129 Paul is interested in changing the name of ChEMBL in primary_knowledge_source, do you know the name of the attribute or where that's located?

**Comment by remontoire-pac** [comment] 2023-06-11 03:33
Pasted from a related ticket:





*To clarify, I'm hoping that we can (in general) expose: (1) original
source; (2) KP; (3) ARA within the UI. I saw examples this week that leaned
in both directions of omission -- can we make it a priority to expose this
basic level of source name for all UI displays? I understand that "deeper
down" we are still working on how precisely to provide EPC, so for now I'm
just talking about the UI to be exposed this summer. PAC *

**Comment by dnsmith124** [comment] 2023-06-26 19:15
This issue has been resolved, as I've implemented Desi's new, user-tested design for the tab headings in the evidence modal window. Here's what the new design looks like: 

![Screen Shot 2023-06-26 at 2 02 13 PM](https://github.com/NCATSTranslator/Feedback/assets/54226761/a424b4d8-7e3b-410e-b2d9-6f027228e00d)

Confirmed live on CI, closing.

**Closed by dnsmith124** 2023-06-26 19:15 UTC
Labels: UI - display, infores, EPIC: infores catalog updates
