### ISSUE TITLE
Link example diseases on MVP1 screen to the corresponding PKs

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#401] opened 2023-07-06 21:44 UTC
## Steps to reproduce:
on CI
start page
click on Alzheimer's example option

**Comment by sandrine-m** [comment] 2023-07-06 21:45
issue submitted by @sandrine-m 
![image](https://github.com/NCATSTranslator/Feedback/assets/66342541/04bb117b-b82b-4ba4-8764-e7d61bc65412)

<img width="1253" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/66342541/4988f121-80a5-4757-b805-d4a7d5b8a38e">

**Comment by sierra-moxon** [comment] 2023-08-08 23:10
closing as duplicate of #460

**Closed by sierra-moxon** 2023-08-08 23:10 UTC
Labels: UI - display
