### ISSUE TITLE
Publications without Primary KS

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#324] opened 2023-06-06 21:04 UTC
Steps:
1. https://ui.test.transltr.io/results?l=Niemann-pick%20Disease&t=0&q=280c5d97-f8b1-4dcd-a809-a8136f3d3b64
2. Ursodeoxycholic acid
3. Treats Edge - 1 pub, from TMKP but only shows TMKP
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/fa6305d4-ca0b-4139-98c4-02a4be49b3a3)

4. will complete later - and 3 weeks late i'm back - but i suspect Chris already got to the root of this.
5. looks like the primary KS for this edge in Robokop is not compliant with the infores catalog, but the publications part is, so UI displayed the pub without the primary KS, so Robokop needs to fix these Primary KS references
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/9e58f92a-5488-4a54-b42d-8081544ee99f)

**Comment by cbizon** [comment] 2023-06-30 13:17
@EvanDietzMorris I believe that this is the same issue you are working on at the moment, correct?

**Comment by sierra-moxon** [comment] 2023-07-03 16:25
closing as a duplicate of #350

**Closed by sierra-moxon** 2023-07-03 16:25 UTC
Labels: infores, EPIC: infores catalog updates
