### ISSUE TITLE
Missing evidence details

### ISSUE THREAD

**Issue by gglusman** [NCATSTranslator/Feedback#803] opened 2024-06-25 18:35 UTC
Testing what may treat sepsis https://ui.test.transltr.io/main/results?l=Sepsis&i=HP:0100806&t=0&r=0&q=d2f631c2-11d6-4ffd-90b1-935f81c7bcdf

Result 5: "immunoglobulins, intravenous", a lookup edge supported by SemMed text mining, and its evidence display starts with what appears to be a broken entry:
![image](https://github.com/NCATSTranslator/Feedback/assets/3977332/c7944168-20c1-4c3e-9dcb-d47ad5f291b1)

**Comment by bill-baumgartner** [comment] 2024-07-12 15:51
This appears to be a case of a PubMed abstract that was at one time processed by SemMed (and is still present in the SemMed data files -- I just confirmed), but has since been removed from PubMed. See the `PMID 26533250 is not available` message when accessing the [PubMed link for this PMID](https://pubmed.ncbi.nlm.nih.gov/26533250/).  Because it has been removed from PubMed, no data for it will be returned from our Publication Metadata Service, so the missing details are expected in this case.

**Comment by bill-baumgartner** [comment] 2024-07-12 15:53
I'll also point out that all of the snippets shown for the SemMed results seem to be the beginning of the corresponding abstracts. The SemMed data files include the sentence-level information for all assertions. Those KPs who are serving SemMed should include the sentence-level data so that the UI can show the exact snippet of text from which each assertion was derived.

**Comment by gprice1129** [comment] 2024-07-17 16:10
This does not seem like a UI issue, right?

**Comment by andrewsu** [comment] 2024-07-17 17:20
I agree, @gprice1129.  And I think this is also essentially a duplicate of #625 which has more details, so I'm going to close this one...

**Closed by andrewsu** 2024-07-17 17:20 UTC
Labels: TMKP
