### ISSUE TITLE
No Search History > Ask a Question Seems like a Dead Link

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#676] opened 2024-01-05 20:51 UTC
Clear your cache 
https://ui.test.transltr.io/demo
Login to Test UI
Go to Search History
Click Ask a Question
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/bcc91e16-b1dc-4bbb-9302-b0b9395cbdde)

You are directed to a blank page
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/14df6410-5286-487c-a3fc-d449d1fd89d4)

**Comment by sierra-moxon** [comment] 2024-01-19 17:34
@dnsmith124 - from TAQA - we're leaving this in your capable hands -- let us know if you need help in retesting.

**Comment by CaseyTa** [comment] 2024-01-19 17:37
Looks like this is expected behavior. The screenshot shows "The results of the questions you have asked are stored locally in your browser's history."

**Comment by dnsmith124** [comment] 2024-01-19 17:42
The link in question should be redirecting automatically to /main, but for some reason it's not. I'm adding in a that should go into CI today to correct this. Will update once the fix is deployed

**Comment by dnsmith124** [comment] 2024-01-19 22:11
Tested and confirmed this has been resolved in CI. 

Closing!

**Closed by dnsmith124** 2024-01-19 22:11 UTC
