### ISSUE TITLE
no publications, uninformative source in EPC

### ISSUE THREAD

**Issue by gglusman** [NCATSTranslator/Feedback#680] opened 2024-01-10 22:54 UTC
[What drugs may treat PRP, 2024/1/10 edition](https://ui.test.transltr.io/main/results?l=Pityriasis+Rubra+Pilaris&i=MONDO%3A0100017&t=0&r=ee8ef27c&q=cfcdc63b-f49f-4ebd-bda1-c2510bd353f1).

Result 3/960 is Etanercept (score 4.99). Evidence cites 0 publications, 0 clinical trials, and 2 sources. These are AEOLUS and BTE, each linking to their respective wiki pages. These links don't help get more evidence for the assertion.
Result 6/960 is Tretinoin (score 4.96). Evidence: 0 pubs, 0 CTs, 1 source - BTE. Again, an EPC dead end.
Same for result 12/960, Fluconazole (score 4.92), etc.

**Comment by gglusman** [comment] 2024-01-11 16:17
Likely related to #657.

**Comment by gglusman** [comment] 2024-01-11 16:33
https://ui.test.transltr.io/main/results?l=Aggressive+Systemic+Mastocytosis&i=MONDO%3A0020333&t=0&r=f58a3afe&q=246f5c17-fd36-4980-92fe-e8cf105e53fc: top 52 results have 0 publications, 0 clinical trials, and 1 source (Unsecret Agent) supporting.

**Comment by cbizon** [comment] 2024-01-19 17:53
BTE is showing up as a primary knowledge source on a treats edge for Etanercept

**Comment by cbizon** [comment] 2024-01-19 17:57
It's not totally clear whether these are inferred edges missing their support graphs or lookup edges with a misassigned primary knowledge source, but in either case, the new UI in test will make this more straightforward to diagnose.

**Comment by andrewsu** [comment] 2024-01-23 19:17
agree with @colleenXu's analysis -- I think BTE is reporting what it knows appropriately.

**Comment by cbizon** [comment] 2024-01-24 15:25
@gprice1129 do you agree that this is a UI issue?

**Comment by Genomewide** [comment] 2024-01-25 00:31
@colleenXu @gprice1129 @andrewsu I think I see what the technical problem is. I don't think it is a UI problem. 

I also don't think fixing it will really addresse @gglusman issue? 
I think the real issue here is the AEOLUS website for the primary source is unhelpful in finding out why that edge is there. I think this is related to the infores work that hopefully is getting better. Is that right, Gwênlyn?

I think I found the technical issue though!  It looks like BTE may have edges with incorrect attribute labels and missing edges.  

The edge IDs suggest BTE meant this to be a 1-hop inferred treats? With one edge as the aux_graph.  And Aragorn and ARAX meant there to be a 1-hop lookup edge.  All pointing to aeolus as the knowledge source. Which makes this an odd case, but allowed and we would support it.  If all 3 had just been a lookup then the display would definitely be correct. What is missing is the 'inferred' part. 

For an edge to be displayed as 'inferred', the only way we can identify them today is to look for attributes pointing to aux_graphs.  support_graphs are part of the analysis object and we don't display them. We were told support_graphs are the edges that may have helped in scoring but were not part of the paths to be displayed.  

I think that is why this result looks off in the ARAX view as well. If it were a support graph, then it would have a link to the support graph.  

![image](https://github.com/NCATSTranslator/Feedback/assets/55069176/e1ad0de5-2b0b-438f-9cc4-5fb7c2d1e766)

I see the following for BTE:
BTE - has inferred in the ID but does not have aux_graphs. has additional edge with support_graph in the ID. 

BTE analysis:
```json
                            {
                                "score": 0.9504392119646858,
                                "attributes": null,
                                "resource_id": "infores:biothings-explorer",
                                "edge_bindings": {
                                    "t_edge": [
                                        {
                                            "id": "b4eb32ffb57766c71724794168601b13",
                                            "attributes": null
                                        },
                                        {
                                            "id": "inferred-UNII:OP401G7OJC-treats-MONDO:0100017",
                                            "attributes": null
                                        }
                                    ]
                                },
                                "scoring_method": null,
                                "support_graphs": null
                            }
```
Edge 1
```json
                        "inferred-UNII:OP401G7OJC-treats-MONDO:0100017": {
                            "object": "MONDO:0100017",
                            "sources": [
                                {
                                    "resource_id": "infores:biothings-explorer",
                                    "resource_role": "primary_knowledge_source",
                                    "upstream_resource_ids": []
                                }
                            ],
                            "subject": "UNII:OP401G7OJC",
                            "predicate": "biolink:treats",
                            "attributes": [
                                {
                                    "value": [
                                        "inferred-UNII:OP401G7OJC-treats-MONDO:0100017-support0"
                                    ],
                                    "attribute_type_id": "biolink:support_graphs"
                                }
                            ]
                        },
```
If attribute_type_id was set to aux_graphs that would would tell us that the edge is infered.  
But also, I don't see any edges for the graph "inferred-UNII:OP401G7OJC-treats-MONDO:0100017-support0". So, there would not be any paths shown under the infered for this.  It would just be displayed like an infered edge with BTE as the knowledge source.  


Edge 2
```json
                        "b4eb32ffb57766c71724794168601b13": {
                            "object": "MONDO:0100017",
                            "sources": [
                                {
                                    "resource_id": "infores:aeolus",
                                    "resource_role": "primary_knowledge_source",
                                    "upstream_resource_ids": []
                                },
                                {
                                    "resource_id": "infores:mychem-info",
                                    "resource_role": "aggregator_knowledge_source",
                                    "upstream_resource_ids": [
                                        "infores:aeolus"
                                    ]
                                },
                                {
                                    "resource_id": "infores:biothings-explorer",
                                    "resource_role": "aggregator_knowledge_source",
                                    "upstream_resource_ids": [
                                        "infores:mychem-info"
                                    ]
                                }
                            ],
                            "subject": "UNII:OP401G7OJC",
                            "predicate": "biolink:treats",
                            "attributes": []
                        },
```

If this was supposed to be 1 hop inferred with 1 edge in the support graph, then what might have made sense would be:
1. The analysis would have the the edge inferred-UNII:OP401G7OJC-treats-MONDO:0100017
2. Its attributes would be like they are now but with biolink:aux_graph
3. inferred-UNII:OP401G7OJC-treats-MONDO:0100017-support0 would be the id that could be found in the aux_graph section of the Trapi. Where it would point to a list of edges. 
4. In this case it would have one edge with id b4eb32ffb57766c71724794168601b13

**Comment by Genomewide** [comment] 2024-01-25 00:39
This totally bring back up the issue from this week about vocabulary! Here is an Aragorn example where all of the parts are there.  

Open view of the result:
![image](https://github.com/NCATSTranslator/Feedback/assets/55069176/a925ffa1-ac0c-4720-b3f8-10d659f4c67c)
**It has'Edge Supprot Graphs' and 'Analysis Support Graphs'**
If the vocab was aligned, this would be called aux_graphs.  

Edge support graphs:
![image](https://github.com/NCATSTranslator/Feedback/assets/55069176/74c393c8-32cf-45a2-be02-64310b00b6f2)

The UI shows these:
![image](https://github.com/NCATSTranslator/Feedback/assets/55069176/7f53af86-9367-4968-91cc-044ecf8cf757)

The Analysis support graphs can be displayed in ARAX, but not the UI:

![image](https://github.com/NCATSTranslator/Feedback/assets/55069176/832f299c-fd9c-4dd0-a799-7d8240c17df6)


Also, should this be caught in ARAX and show a warning or something?

**Comment by cbizon** [comment] 2024-01-25 01:12
I'm not sure I understand @Genomewide  - the ARAGORN example uses the attribute "biolink:support_graphs" on the inferred edge, just as BTE does. That, as I understand it, is the right attribute name in both cases.  And both point to auxiallary graphs that have edges in them.

The only thing I can't verify for sure from this comment is whether the BTE aux graph "inferred-UNII:OP401G7OJC-treats-MONDO:0100017-support0" has the right edge in it.

But if it does, then I'm not clear on why the UI will show the aux graph for ARAGORN's and not BTE's result.

Also, I'm not clear on what your last comment there is referring to:
> Also, should this be caught in ARAX and show a warning or something?

Maybe I'm missing the point here...

**Comment by Genomewide** [comment] 2024-01-25 01:14
@cbizon You are right, I had to back that out of what I put above. I edited to remove it, but you may still see the old answer.  I think BTE is just missing support graphs.

**Comment by Genomewide** [comment] 2024-01-25 01:24
Here is the weird kicker! And I think Gus just figured it out! 
ARAX displays this for the BTE result. 
![image](https://github.com/NCATSTranslator/Feedback/assets/55069176/d3dd159f-89f9-439f-a57e-a5fb14b1d138)

I only look at the merged JSON and not the individual ones.  I bet it is getting cut in the merge. According to the data I see inferred-PUBCHEM.COMPOUND:3365-treats-MONDO:0100017-support0 has no edges. It is just referenced like the other answer above. 

@MarkDWilliams can you check this? 
Here is the ref link again.  
https://arax.ci.transltr.io/?r=cfcdc63b-f49f-4ebd-bda1-c2510bd353f1

**Comment by cbizon** [comment] 2024-01-25 01:25
Oh ok, thanks @Genomewide !

**Comment by Genomewide** [comment] 2024-01-25 01:27
I am so sorry you read all of that! I did not want to leave it in bc it was confusing so I rewrote history a bit, but you were too on top of it and got the incorrect and (what I hope are) correct parts.

**Comment by gprice1129** [comment] 2024-01-25 04:44
Just to be extra clear why the BTE edges are missing. The current UI code treats the **entire analysis as invalid** if it can't find any of the referenced nodes, edges, or support graphs in the analysis **no matter how many levels deep in the support graphs the missing reference occurs**.

**Comment by MarkDWilliams** [comment] 2024-01-25 14:45
Taking a look at this now to see what the root cause of the issue is.

**Comment by MarkDWilliams** [comment] 2024-01-26 16:33
Shervin was able to dig into these results (thanks @ShervinAbd92 !) and I believe she found the issue.  Reposting her comments here as she's AFK for a bit.

> In the removed_block function the aux_graph ” inferred-UNII:OP401G7OJC-treats-MONDO:0100017-support0" is added to the aux_graph_to_remove list since there is an overlap between  “a8095addc72a5c9785059bda32cd940f  and “MONDO:0100017-has_phenotype-MONDO:0005070-via_subclass”--> which is in the list of edges_to_remove, which has a “object” that is among nodes_to_remove list from the block list.

So, it looks like

1. the Aux graph is slated to be removed because it contained an edge to be removed (and no other edges.  If it had other "legitimate" edges, it would only have the blocked edges removed but the aux graph as a whole would remain.)
2. The edge is on the list to remove because it contains a blocked node
3. The blocked node in question is `MONDO:0005070` : "Tumor"

We have a few options here as I see it, and I'm happy to facilitate whatever folks want to see.

1. Software is working as intended.  No fix needed
2. "Tumor" is not generic enough to warrant inclusion in the Blocklist and should be removed (which would bring back the aux graph and edge)
3. "Tumor" is a valid blocklist entry, but the behavior for blocking should be handled differently somehow (I'm open to options here)

For #3, I _believe_ the behavior that we're seeing here is in-line with what got discussed on the TAQA breakout for how the blocking should work, but I'm happy to change that if, seeing it in action, we have different feelings about it.  I'll lay out the broad strokes of what we have implemented below for clarity :

- First, we find any overlap between the blocklist and the knowledge_graph nodes.  That is, which, if any, blocked nodes actually occur in this set of results.
- Once identified, we remove these nodes from the knowledge_graph and any edges which contain them as a subject or object.
- Then, we look at `results`.  `Results` that have a blocked node as part of their `node_bindings` on the actual `result` object just get removed entirely.  That is if a result says "Water treats Diabetes", we remove the whole result
- If a `result` is ok at the top-level, we move on to looking in the `analyses`.
- If there are any `edge_bindings` in the analysis that are among our bad edges, we remove just those.
- However, if all the edges in an analysis are bad, we remove the whole analysis  
- If the `support_graph` in the `analysis` (which is basically a list of edge_bindings) has any of our edges to be removed, we remove those from the `support_graph` as well.
- Finally, if in the process of removing "bad" analyses, we find ourself with a `result` that now has no `analyses` (i.e. a `result` that only had "bad" evidence supporting it, we remove that `results` because we don't want to show something with zero evidence.

Apologies for the long post with a series of lists, but I just wanted to make sure everything was as clear as possible.  Does anyone have any thoughts on which option we should pursue?

**Comment by cbizon** [comment] 2024-01-26 19:43
This mostly makes sense, but if I understand it all, then the removal of Tumor should eventually have led to the remove of the result, but it didn't.  Is that wrong?

I guess I also wonder about whether Tumor should be on the block list.   For instance something like Chemical reduces Tumors and therefore treats Cancer X seems like a valid path?

Are we mixing up different uses for the blocklist i.e. is Tumor on there for another good reason that I'm not thinking of?

**Comment by colleenXu** [comment] 2024-01-26 20:15
So it looks like most of the discussion is about BTE's PRP disease and Etanercept drug result. 

Here's the screenshot for that ([Andy's post shows the Fluconazole drug result instead](https://github.com/NCATSTranslator/Feedback/issues/680#issuecomment-1909192920))

![Screen Shot 2024-01-26 at 12 11 05 PM](https://github.com/NCATSTranslator/Feedback/assets/43731687/e933821b-3f00-428a-86ee-85ae71486914)

---

My observations are:
* there's a bunch of other edges in the support graph that don't involve tumor/MONDO:0005070. So shouldn't the support graph have been kept - just with the tumor-edges + tumor-node removed from the aux-graph/knowledge-graph? 
* MONDO:0005070 = neoplasm here, not tumor?

**Comment by MarkDWilliams** [comment] 2024-01-26 20:53
The initial thinking with this logic was that removing edges from aux graphs would leave aux graphs that were disconnected or didn't make sense.  So, we remove the whole aux_graph.  If folks want this behavior changed, we could remove just the tumor edge and leave the rest.  It might just leave us with some funky aux graphs in the future.

**Comment by MarkDWilliams** [comment] 2024-01-26 20:55
@cbizon It would only "trickle up" to remove the whole result if removing this aux graph left us with a result that had no supporting evidence.

**Comment by Genomewide** [comment] 2024-01-26 21:05
@MarkDWilliams Is there a time when this would leave us with an inferred edge that has no aux graphs?

Also, would be good to have @gprice1129 look at the explanation and see when he thinks our system would just boot the result.  The reason this one still showed up was because others reported it. It would disappear if not.

**Comment by gprice1129** [comment] 2024-01-26 21:26
A couple things I want to clarify:
1. @MarkDWilliams I think it should be considered a bug that there is a hanging reference to an auxiliary graph (or anything, nodes, edges, etc.) that has been removed from the response by the ARS. I would like to hear your thoughts.
2. @Genomewide I don't think there is a situation where removing the node/edges from a graph would break the UI unless there are dangling references (see point 1).

**Comment by MarkDWilliams** [comment] 2024-02-09 17:09
Agree.  Dangling references are a bug on the ARS side and should be fixed.  Also agree with the overall principle that if you're removing something, you should remove all references to it.

**Comment by sierra-moxon** [comment] 2024-05-17 15:44
Noting that Etanercept has a much lower score now, in the 2's vs ~5.  

No "Tretinoin" but two with that in the name, one has a score of 5.  It seems reasonable to me after taking a look at the publications.  But also noting that it says it has 9 publications when really it only has 2. 

<img width="938" alt="Screen Shot 2024-05-17 at 8 42 37 AM" src="https://github.com/NCATSTranslator/Feedback/assets/4561292/3b050507-adda-408c-bb52-a3419773c919">
<img width="1220" alt="Screen Shot 2024-05-17 at 8 43 03 AM" src="https://github.com/NCATSTranslator/Feedback/assets/4561292/3e9d35f1-a1c1-462c-a4aa-45807286b243">

**Comment by sstemann** [comment] 2024-08-08 19:49
In Fugu on Test Environment

Etanercept - 4.49 and 3 pubs
Tretinoin - 4.43 and 16 pubs
Fluconazole - 3.65 and 2 pubs

https://ui.test.transltr.io/main/results?l=Pityriasis%20Rubra%20Pilaris&i=MONDO:0100017&t=0&r=0&q=11c31e0e-c504-410f-bba4-efc085f4d04b

@gglusman does that help?  i will say there are still times when the EPC is a deadend, but not for these examples?

**Comment by gglusman** [comment] 2024-08-08 21:12
It does look much better indeed!

**Closed** 2024-08-09 00:20 UTC
