### ISSUE TITLE
Publication Counts - View All vs Edge

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#454] opened 2023-08-01 19:30 UTC
Steps:
1.  in UI TEST What chemicals may upregulate PTEN https://ui.test.transltr.io/results?l=PTEN&i=NCBIGene:5728&t=1&q=159f8459-06e9-4d43-afef-e183df303c0e
2. On the view result, View All Evidence - Publications - 14, all either "causes increased activity or abundance of" or "causes increased activity of"
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/e45b890a-c655-4a7d-81c4-47636a0997a9)

3. There's one path, one edge - click the edge
4. Publications - 27, and they seem duplicative for each "causes increased activity of" theres an entry that looks the same for "affects"
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/52acd55a-6106-46d0-b3f0-45d6ef60858e)

i'm not sure if this is a UI issue or a source (ARAX, Robokop, Unsecret)

https://arax.ncats.io/?r=159f8459-06e9-4d43-afef-e183df303c0e

or if this will all be changed with the ARS Merging?  I'm not sure,

**Comment by dnsmith124** [comment] 2023-08-02 15:48
It looks like this is a quirk of the UI. Right now when you click "view all" it shows all publications associated with the edges in that result, and each publication has a list of edges with which it is associated. The first edge in that list is what gets displayed in the "relationship" column, and each publication is listed only once (not multiple times if it's associated with multiple edges). 

Viewing a particular edge/set of edges like in the 2nd screenshot shows an aggregation of all publications associated with those edges. Essentially it grabs all publications associated with each selected edge and throws them into one big list, but it doesn't limit a particular publication to only show once, since you're looking at a combined set of publications for all of the selected edges. 

So if you look between these two views it sort of looks like either there are either missing publications in the "view all evidence" window, or there are duplicates within the edge-specific evidence window, even though technically it's working "_correctly_". 

@sstemann should I change this behavior? If so, should every instance of a publication be shown in the "view all evidence" window, or should duplicates be removed from the edge-specific evidence window?

**Comment by Genomewide** [comment] 2023-08-15 19:16
WE have discussed designs for the future that will address this (I think). You currently get one line per paper / per edge. The edge descriptions are too long to combine.  However, I have one proposed design that would show the edges at the top of the EPC like now, but with ref #s . Then the ref # only could be shown. 

This design includes the edge ref# as well as the edge source indicator designs:

![image](https://github.com/NCATSTranslator/Feedback/assets/55069176/292899cb-197c-41cb-8477-615193bd7975)


These were deemed post-September projects.

**Comment by gprice1129** [comment] 2023-09-27 21:46
Closing, this is not a bug.

**Closed by gprice1129** 2023-09-27 21:46 UTC
