### ISSUE TITLE
One of the 100.0 responses is GLP1R, but semaglutide is an agonist, so it should be upregulated.

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#233] opened 2023-06-05 16:48 UTC
## Steps to reproduce:
ui.ci.transltr.io -> what gene is downregulated by semaglutide

**Comment by cbizon** [comment] 2023-06-05 16:48
47bcf75c-6220-4a19-9441-519791054452

**Comment by cbizon** [comment] 2023-06-05 17:09
Another example: what gene is downregulated by ibuprofen.  Returns PTGS2 (which is correct) but also PPARG.   NSAIDs like ibuprofen are PPARG agonists, so this is the opposite of what I asked for...

**Comment by cbizon** [comment] 2023-07-20 01:25
ARAGORN no longer returning GLP1R, but CI: fe5a00a8-0fcf-420b-ba2f-1cd2aec656b5

It looks like ARAX is returning GLP1R, as an agonist (which is the opposite):

<img width="1603" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/10744350/08193c67-ff25-4a9c-a84d-a2ff35668643">

**Comment by edeutsch** [comment] 2023-07-20 02:26
it looks like this is coming from MolePro?

![image](https://github.com/NCATSTranslator/Feedback/assets/12707718/dd2e2110-dad0-43e1-ae94-61a73b1dd093)

**Comment by saramsey** [comment] 2023-08-01 19:55
I concur with @edeutsch. I am not seeing a KG2.8.4c issue here.

**Comment by sierra-moxon** [comment] 2024-05-17 00:54
can not reproduce; closing as fixed!

**Closed by sierra-moxon** 2024-05-17 00:54 UTC
Labels: opposite of what I asked for
