### ISSUE TITLE
Minimum number of evidence filter does not include sources in the evidence count?

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#236] opened 2023-06-05 16:53 UTC
## Steps to reproduce:
Queried for what drugs may treat Crohn Disease on UI-Test. Under evidence, most results (only results from Improving so far) have 0 publications and 1 source, so I would assume these results have 1 piece of evidence. But when enabling the "Minimum Number of Evidence" filter with the minimum set to 1, no results are retained. I would have expected them all to be retained. 

## Screenshots:
![screenshot](https://raw.githubusercontent.com/TranslatorSRI/IssueScreenshots/main/screenshot_20230605165315598326.jpeg)

**Comment by sandrine-m** [comment] 2023-06-16 23:46
Could not reproduce issue from shared PK:
<img width="1256" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/66342541/64f06ece-5c3c-4f30-a64b-e4a74d1c41df">
Might this be due to the user not waiting for query to finish calculating the results?

**Comment by dnsmith124** [comment] 2023-06-23 15:51
I believe the reason @sandrine-m could not reproduce is due to loading the pk later automatically added in fresh results, which included results that had publications and so some results were visible with the min evidence facet set to 1. 

I was able to recreate this by submitting a fresh query for Crohn Disease and only looking at the initial results from Improving agent (which all have a source but no publications). 

This morning I'll be working on updating that facet to take sources into account in addition to publications, rather than just the latter.

**Comment by sandrine-m** [comment] 2023-06-23 16:48
Thanks @dnsmith124 ! I have assigned it to you since you are working on it (to avoid retesting). :) Feel free to assign anyone else as you see fits

**Comment by dnsmith124** [comment] 2023-06-23 21:00
Tested and confirmed as resolved on ci: sources are now counted as part of the minimum evidence filter. 

Easiest way to test is to submit a new query, then when the first results from Improving are shown, activate the minimum evidence filter with a value of 1. 

Closing.

**Closed by dnsmith124** 2023-06-23 21:00 UTC
Labels: UI - display, infores, EPIC: infores catalog updates
