### ISSUE TITLE
Which KP/ARA can provide biolink:MolecularMixture content, including whether each ingredient is active or inactive (e.g. data from DailyMed)

### ISSUE THREAD

**Issue by karafecho** [NCATSTranslator/Feedback#60] opened 2022-12-15 16:54 UTC
The QotM surfaced [DailyMed](https://dailymed.nlm.nih.gov/dailymed/) as a source of data on active vs inactive medication component. This resource was identified in the context of distinguishing propofol from soybean oil. Note that DailyMed is one of many potential knowledge sources that contain information on labeling.

**Comment by sierra-moxon** [comment] 2022-12-15 22:56
In addition, the QotM identified [FooDB](https://foodb.ca/) <-> [FoodOn](https://foodon.org/) mappings, [FoodData Central](https://fdc.nal.usda.gov/) as sources of nutrient data and food-derived chemicals. It was noted that the SPOKE team manually created mappings from FoodDB <> FoodOn, which they offered to send to SRI. In addition, there are existing tickets in the biothings repo for both FoodDB and FoodDataCentral: https://github.com/biothings/pending.api/issues/65 and https://github.com/biothings/pending.api/issues/66. Creating ticket here to promote broader discussion and prioritization.

**Comment by sierra-moxon** [comment] 2022-12-16 15:45
duplicate of #66 and also related to #62 

We would like a data source that can provide the chemical content of CBD.

**Comment by sierra-moxon** [comment] 2024-05-17 00:05
closing as @gglusman is working on importing DailyMed for the clinical KP.

**Closed by sierra-moxon** 2024-05-17 00:05 UTC
Labels: KP - data/attribute gap
