### ISSUE TITLE
F- is not part of K+

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#750] opened 2024-04-01 20:34 UTC
## Steps to reproduce:
search for ALPL

**Comment by sandrine-muller-research** [comment] 2024-04-01 20:38
In the query "What gene may be upregulated by potassium ion?"
we get : ALPL
through the path :
![image](https://github.com/NCATSTranslator/Feedback/assets/22616936/759ecfd0-5c8c-4a36-bac8-e4ea692e6e01)
from ARAGORN
I do not see how F- is part of K+, and more generally that an ion is part of another ion?

**Comment by sandrine-muller-research** [comment] 2024-04-01 20:54
same issue with :
CaCO3 part of K+ (CAPN1,SOD,CASP3 results)

**Comment by sstemann** [comment] 2024-04-02 12:27
@cbizon @uhbrar

**Comment by cbizon** [comment] 2024-04-02 13:38
The Flouride has part Potassium ion is coming from semmeddb. Looks like both the KG2 and service provider versions.  It looks good in the sense that it's coming from 7 or so papers, so I think it's getting past some of the filters.  But when you dig into it, it looks like the papers are all from the same group, and even have nearly consecutive PMIDs and repeat the same text.  Somebody got a lot of pubs out of this toothpaste.  Anyway, I'm not sure if there's a way to improve the semmed filters to cover a case like this?

The Calcium carbonate part of K+ are the same problem (and same papers I think).

@andrewsu @saramsey

**Comment by saramsey** [comment] 2024-05-01 20:30
This should be fixed in RTX-KG2 as of KG2.9.0c (Octopus release), where we are no longer using `biolink:has_part` for this, but instead, `biolink:coexists_with`.

**Comment by andrewsu** [comment] 2024-07-26 17:14
I'm going to close this as currently not-able-to-reproduce.  When I search for "potassium" in the UI, I only get one option:

![image](https://github.com/user-attachments/assets/11e2315a-aecd-4ab3-b59c-99cb61f7414f)

That corresponds to `CHEBI:26216` (potassium), not `PUBCHEM.COMPOUND:813` (potassium ion) in the example above.  (These are [not equivalent](https://nodenorm.ci.transltr.io/get_normalized_nodes?curie=PUBCHEM.COMPOUND:813&drug_chemical_conflate=true) according to nodenorm.)  and I do not see `ALPL` among the results for "potassium": https://ui.test.transltr.io/main/results?l=Potassium&i=CHEBI:26216&t=3&r=0&q=ab59272c-b892-4677-a78a-9856b4fb9df0

**Closed by andrewsu** 2024-07-26 17:14 UTC
Labels: SEMMED, Next Phase
