### ISSUE TITLE
Unexpected Application Error

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#708] opened 2024-02-01 21:01 UTC
Steps to reproduce:

1. Click https://ui.test.transltr.io/main/results?l=Aicardi%20Syndrome&i=MONDO:0010568&t=0&r=0&q=d30239ed-f1ac-42dd-af25-4768997d8b79 - which should be results for MVP1 > Aicardi Syndrome
2. In the filters select Reasoning Agent > ARAGORN - really any ARA
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/a9253b92-fea4-4fbe-b2d1-61c26f91e8d1)
3.  I also can't page the results

**Comment by dnsmith124** [comment] 2024-02-01 21:15
Looking into this now

**Comment by dnsmith124** [comment] 2024-02-02 17:02
Confirmed resolved in CI, should go out in a TEST deployment later today as well. 

It looks like the orphaned paths are coming from Aragorn. Here are the links from my retest of the issue in CI.
https://ui.ci.transltr.io/main/results?l=Aicardi%20Syndrome&i=MONDO:0010568&t=0&r=0&q=fbf8ea0a-ba31-4a33-be78-4387a8931c40
https://arax.ci.transltr.io/?r=f2c2b103-cfd2-4bb1-a163-f1dee10f35d0
Sodium is one of the results that demonstrates the issue. 

@MarkDWilliams I'm assuming there's something wrong with these paths that's causing them to be removed during merging?

**Comment by gprice1129** [comment] 2024-02-02 17:23
@dnsmith124 this is almost certainly my fault as the ARS has no notion of a path.

**Comment by gprice1129** [comment] 2024-02-02 18:22
I also pushed a fix and tested that it fixed the root cause. I'm going to close this ticket.

**Closed by gprice1129** 2024-02-02 18:22 UTC
