### ISSUE TITLE
search for "what treats Alzheimer's Disease" return results that instead cause or exacerbate AD

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#12] opened 2022-10-05 19:48 UTC
## Steps to reproduce:
look for drugs that treat Alzheimer's Disease, investigate first result "Inflammation mediators"

## Screenshots:
![screenshot](https://raw.githubusercontent.com/TranslatorSRI/IssueScreenshots/main/screenshot_20221005194854052975.jpeg)

**Comment by sierra-moxon** [comment] 2022-10-05 19:52
In addition, the last row/metapath there shows that Inflammation mediators treat rats (we could probably constrain this a bit more - I imagine this is trying to provide clear evidence that this study/studies were performed in rats).  The "has part" path is not immediately clear to me in terms of why "has part" was used here.

**Comment by sierra-moxon** [comment] 2022-10-05 19:56
and finally, if you look at the evidence for "causes" between Lipopolysaccharides and AD, there is a row of evidence that declares this edge to be a possible cause in mice. "Our data showed that SEO improved the cognitive ability of mice with Abeta1-42 or lipopolysaccharides (LPS)-induced Alzheimer's disease (AD) and suppressed the production of..." 
<img width="806" alt="Screen Shot 2022-10-05 at 12 53 40 PM" src="https://user-images.githubusercontent.com/4561292/194150516-fc633515-2830-44ec-9f14-2c0ec86b3664.png">

Which is also fine, but a couple of potential issues with this are:
1) we have an inconsistent representation of the organism in which the study took place -- in the comment above, there is a row that shows the rat node directly.
2) we probably don't want "causes" to be used without some sort of qualifier that is always shown on the UI to reflect that this was done "in mice."

**Comment by sierra-moxon** [comment] 2022-10-05 19:57
these are probably 3 or 4 separate issues, but I can only submit one "feedback" ticket from the UI for this ARS pk identifier; happy to split them up if that is helpful.

**Comment by capasfield** [comment] 2023-01-13 17:55
Which ARA is responsible for this answer? Andy to take a look at it.

**Comment by Genomewide** [comment] 2023-01-13 18:38
It is ARAX returning these 3 edges. They are semmeddb through RTX.  Data below

Edge info

ara-arax
Antioxidant treat Alzheimer
infores:rtx-kg2:CHEBI:22586-biolink:treats-MONDO:0004975infores:rtx-kg2:CHEBI:22586-biolink:treats-MONDO:0004975
infores:rtx-kg2
infores:semmeddb

ara-arax
Antioxidant causes Alzheimer
infores:rtx-kg2:CHEBI:22586-biolink:causes-MONDO:0004975
infores:rtx-kg2
infores:semmeddb

ara-arax
Antioxidant prevents Alzheimer
infores:rtx-kg2:CHEBI:22586-biolink:prevents-MONDO:0004975
infores:rtx-kg2
infores:semmeddb

**Comment by sierra-moxon** [comment] 2023-02-14 21:44
Hi @saramsey, @dkoslicki- It looks like this data is coming from ARAX/rtx-kg2, would you be the best people to assign this to?  :). I guess the action requested here is to consider if the results from RTX-KG2 are correct (or correct based on text mined evidence maybe?)

**Comment by saramsey** [comment] 2023-02-14 22:49
Starting to look at this.... if anyone else on the team wants to also have a look, [this URL](https://arax.ncats.io/?r=66422L seems to pull up the ARAX results in question, that connect "inflammatory mediators" to Alzheimer's Disease.

**Comment by saramsey** [comment] 2023-02-14 22:53
Looks like the direct edge between "Inflammation mediators" (`MESH:D018836`) and "Alzheimer's disease" (`MONDO:0004975`) came from DTD?  @dkoslicki is that correct?

<img width="775" alt="Screen Shot 2023-02-14 at 2 51 57 PM" src="https://user-images.githubusercontent.com/5562107/218881305-bc7b8c52-6fd4-41db-b82c-063869e0f50a.png">

My feeling here is that the main issue is the vagueness of "inflammatory mediators". I wonder if that result should (ideally) be downweighted (i.e., downranked) based on its low "concept specificity", an idea that our team has been working on. @amykglen is currently leading up work on computing node specificity so that we can provide that information in RTX-KG2 results, and thus, in ARAX results.

**Comment by saramsey** [comment] 2023-02-14 22:59
As for the second row in the New Translator UI results, namely, "Inflammation mediators" to "Lipolysaccharide" to "Alzheimer's disease", the first edge (connecting "Inflammation mediators" to "Lipopolysaccharide") seems to come from SemMedDB. 

<img width="961" alt="Screen Shot 2023-02-14 at 2 58 12 PM" src="https://user-images.githubusercontent.com/5562107/218882299-f3ee3a4d-675a-4f6f-9d15-0068a59f7508.png">

**Comment by saramsey** [comment] 2023-02-14 23:03
So, we have a triple coming from SemMedDB, `C0243042` ("Inflammation mediators") `SEMMEDDB:stimulates` `C0023810` ("Lipolysaccharide"). The direction of that triple is, of course, not consistent with biology. But it is consistent with what I see in RTX-KG2.8.0pre,

<img width="734" alt="Screen Shot 2023-02-14 at 3 02 55 PM" src="https://user-images.githubusercontent.com/5562107/218882850-bc225779-94db-4882-9cb5-c16fca733b6e.png">

**Comment by sierra-moxon** [comment] 2023-02-16 19:22
From TAQA:

- semmeddb provides a "novelty" declaration on nodes. 
- BTE filters out "non-novel" node properties. (it might help this issue - maybe RTX-KG2 could also filter on this).

**Comment by dkoslicki** [comment] 2023-02-16 21:54
I apparently didn't hit enter on my last reply, but this is a known issue with our machine learning model (and not RTX-KG2, but rather with a component of ARAX): it sometimes finds paths that affect the disease, but in the wrong direction. We decided that since a practitioner would be able to immediately recognized this as a mistake, we'd ere on the side of permissiveness, rather than strict filtering and risk removing interesting results.
If there's a list of criteria by which we could filter, that would be great, as there are 279K possible kinds of (meta)paths that we could return for this query. Eg. (drug)-[positively_regulates]-(gene)-[positively_regulates]-(gene)-[causes]-(disease) .

**Comment by cbizon** [comment] 2023-03-10 17:38
@dkoslicki Understood - is there any kind of post processing that can/should be done here?

**Comment by sierra-moxon** [comment] 2023-03-10 17:44
From TAQA:
- from Sarah: similar issues in stand-up calls (sometimes we have causes instead of treats).  has a low score.  working as designed.
- from Andy: is giving a low score enough to filter this out of the UI results?  It's clearly the opposite in the UI.
- from Tyler: +1 Andy - it's different when talking about multiple hops or increasing/decreasing the resultant phenotypes.  One solution is to simply not return a causes or exacerbates edge when searching for treats.  We need to keep user confidence in mind. 
- Sarah: on Tuesday, there was a connection between drug and disease, had multiple edges - one was causes, one was not.  So would we just not show the causes edge?  - Tyler: yep, just remove the causes edge?  
- Chris: the causes edge is part of the reasoning path.  In general, there is a big graph under here, and UI has extracted a path that may show "causes."
- Tyler: don't remove any causes edges from a path - but don't display those.  In a 2 or 3-hop query, it could help.  Chris: this issue is a 2-3-hop.
-  Chris: this is not always wrong.  Spent some time investigating this in Robokop.  Sometimes papers do show that the opposite effect happens in a small number of cases.  How do we take out just parts of a path?   We need an overall discussion about how to handle conflicting evidence here. Tyler- +1 - but we can't show this to the users. 
- Christine: inclined to leave it because it might be informing something about biology as well.  
- Andy: is this a refinement of the rules to produce the result, or is this something that the UI has to figure out in order to hide? if a result path is upregulates-upregulates-causes, what should be fixed? 
- Tyler: I like the idea of the UI just somehow low-lighting causes edges in the specific MVP1 query, and on mouse-over you could have something like "We've determined that the causes edge is potentially unhelpful for this type of query, but we have chosen to leave them in because they could lead a user to valuable information" or something.
- Andy: we need specific rules on when to show this disclaimer


similar result from standup this week: 
![Image](https://user-images.githubusercontent.com/4561292/224386627-112d6965-99b7-4c13-9955-b9dbc5605617.png)

**Comment by sierra-moxon** [comment] 2023-03-10 17:46
closing for now?

**Closed by sierra-moxon** 2023-03-10 17:46 UTC
Labels: bug, reasoning
