### ISSUE TITLE
Unable to submit multiple feedbacks without a page refresh

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#241] opened 2023-06-05 17:03 UTC
## Steps to reproduce:
Submit feedback. You're shown a modal saying your issue is created. Close that modal and click the "Send Feedback" button again. You're again shown the "Your issue was created" modal and there's no way to submit a new issue.

**Comment by dnsmith124** [comment] 2023-06-22 16:02
There are two buttons that appear in the modal after sending feedback, one is a link to the created issue in github and the other says "Submit More Feedback", which when clicked resets the form and allows you to submit another issue. 

I think the user just didn't see this "Submit More Feedback" button, as it's been present since October of 2022. Confirmed that it's there on test and ci, including at the url the user submitted. 

Closing.

**Closed** 2023-06-22 16:03 UTC
Labels: bug
