### ISSUE TITLE
UI Incorrectly Grays Out Paths When Forbidding a Node

### ISSUE THREAD

**Issue by MarkDWilliams** [NCATSTranslator/Feedback#240] opened 2023-06-05 17:01 UTC
Starting with this result (Epoprostenol) from this query (What drugs may treat Raynaud's):
https://ui.test.transltr.io/results?l=Raynaud%20Disease&t=0&q=e897ac27-e19e-44bc-a857-d1eaf176aee1

<img width="1378" alt="Screen Shot 2023-06-05 at 12 58 49 PM" src="https://github.com/NCATSTranslator/Feedback/assets/12091335/9cea3689-54be-4c81-9156-f33d2ddfa194">

When we try to deselect Connective Tissue Disorder, it grays out all paths:
<img width="1382" alt="Screen Shot 2023-06-05 at 12 59 37 PM" src="https://github.com/NCATSTranslator/Feedback/assets/12091335/fdb3298e-15bd-49d1-99b2-af0cc2eed0b0">

However, there are paths which exist that do not go through that node (which do show if you manually select a node for those paths):
<img width="1382" alt="Screen Shot 2023-06-05 at 1 00 13 PM" src="https://github.com/NCATSTranslator/Feedback/assets/12091335/d3a5f870-ff6e-42d2-a986-2a56037bd028">

<img width="1385" alt="Screen Shot 2023-06-05 at 1 00 51 PM" src="https://github.com/NCATSTranslator/Feedback/assets/12091335/aa0c40d4-eb85-4798-a432-cec4a6c3dd95">

**Comment by dnsmith124** [comment] 2023-06-05 17:17
Currently the algorithm for path selection works on a list of selected nodes and deselected nodes, so in this case it's _technically_ working correctly but I agree that it's not perfectly intuitive. 

If you select Connective Tissue Disorder, then deselect it, the list of 'selected nodes' is now empty, so no paths are highlighted. This is why selecting another node causes it to highlight those paths. 

I agree with you though that if there are no selected nodes and only deselected nodes that the rest of the paths should probably be highlighted by default!

**Comment by dnsmith124** [comment] 2023-06-23 20:58
I am working on making this more intuitive. Giving it the August milestone for now, but I will update as I make progress.

**Comment by sandrine-m** [comment] 2023-06-26 13:28
Ok! I moved the ticket in progress. Thank you sdo much @dnsmith124 !

**Comment by sierra-moxon** [comment] 2023-08-08 22:25
bumping this ticket with a comment to keep it at the "in progress" stage in our filters so we don't have to look at it again until the milestone is finished.

**Comment by dnsmith124** [comment] 2023-09-14 14:48
@sstemann The deselection works well in combination with any number of selected nodes, that aspect of the functionality is working as intended. The workflow is intended to be as follows: 
1. The user selects some number of nodes they're interested in. 
2. After looking at the highlighted paths either in the graph view or the path view, they are able to narrow their selection by clicking twice on nodes that they aren't interested in in order to exclude any paths that include those deselected nodes. 

I think the only potentially unintuitive aspect of the system as it functions now is that if you select just a single node, then deselect that node, all of the paths appear grayed out because technically no nodes are marked as `selected`, leaving no valid paths for the graph to highlight. 

After reviewing this fairly comprehensively I think the problem isn't necessarily in the functionality itself, but how it is conveyed to the user. If the user was aware that the highlighting operated based on two sets of nodes (selected and deselected) then I don't think the particular scenario Mark is describing would be confusing. To that end, I think the best way to resolve this issue is to add some sort of tutorialization showing how to use the graphs, which is a feature we're planning on working on once the functionality of graphs is closer to being finalized.

**Comment by gprice1129** [comment] 2023-09-27 17:16
Should we close this?

**Comment by dnsmith124** [comment] 2023-09-27 17:55
I do recommend that we close this @gprice1129 @sstemann.

**Closed** 2023-09-28 20:20 UTC
Labels: bug, UI - display
