### ISSUE TITLE
Autocomplete is incomplete

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#315] opened 2023-06-06 16:25 UTC
## Steps to reproduce:
Type "Sex" into the search bar - Using the what drugs may treat disease query. 5 options are returned, including one that starts with "sexual". However, if you type "sexual" into the search bar, many more options are returned. Seems like all of the "sexual *" options should be returned when just "sex" is entered.

**Comment by codewarrior2000** [comment] 2023-06-23 16:25
Taking a contrarian perspective, what kind of autocomplete do we expect when someone types "Se"?

**Comment by gaurav** [comment] 2023-06-23 16:25
Andy:
* Caused by lack of Biolink type information -- got 1000 results from NameRes, filtered out 999 drugs and only showed the one disease. As you get more specific, you start pushing out the drugs, and suddenly more results appear.
* Would like Biolink type filtering and CURIE type (e.g. MONDO/HP for disease) -- will not be as noticeable when that happens
* Simpler/quicker fix: max = 10,000
* Having these examples would be great for testing

Gaurav: we want to do improved testing one-character-at-a-time.
* Biolink type filtering: fixing one last bug
  * Andy: higher priority that CURIE filtering
  * David: it's going to solve 95% of the problem
* CURIE type (e.g. MONDO/HP for disease): @gaurav to add to NR and see if we can deploy this really quickly

**Comment by sstemann** [comment] 2023-09-18 19:06
this behavior described at the start of this ticket is still happening.  is there something that should change?

**Comment by gprice1129** [comment] 2023-09-27 21:19
I can't reproduce this behavior in the production environment @sstemann @dnsmith124

**Comment by dnsmith124** [comment] 2023-09-27 21:30
I've retested as well and can't seem to either

**Comment by gprice1129** [comment] 2023-10-05 15:51
@sierra-moxon do we need a third-party tester to decide if this is closeable? I would be more comfortable if we had someone outside of our team test.

**Comment by gaurav** [comment] 2024-01-24 19:45
I think we've tested this enough that we're pretty sure it's fixed, so I'm going to close it. Please reopen if I missed something or if it fails testing at some point in the future.

**Closed by gaurav** 2024-01-24 19:45 UTC
Labels: UI - term selection, autocomplete
