### ISSUE TITLE
inferred edge "affected_by" while all predicates in reasoning are "has_increased activity or abundance"

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#758] opened 2024-04-10 18:30 UTC
## Steps to reproduce:
What genes are upregulated by potassium ion?

**Comment by sandrine-muller** [comment] 2024-04-10 18:31
![image](https://github.com/NCATSTranslator/Feedback/assets/153299800/05ddce18-c594-4e41-a211-531c1a18f877)

Why is the inferred predicate not _has increased activity of abundance_?

**Comment by gprice1129** [comment] 2024-04-12 17:42
@sandrine-muller could you explain more about why you think this is a UI issue? For the first and third screenshot the underlying data for inferred edge shows that the predicate is "affected by", so that seems correct.

For the second screenshot I'm quite mystified about what it is you're looking at. On the top left I see the result is VPS51 but in the graph I don't see a reference to that node anywhere. Can you provide exact instructions on how you arrived at that result in the ARAX UI and also provide a screenshot on what it looks like in the Translator UI?

**Comment by sandrine-muller** [comment] 2024-04-15 14:23
@gprice1129 Perhaps that is due to my misunterstanding of how qualified statements are shown in the UI (note that I have **not** triaged as a UI issue per se)
This issue to me comes from the fact that, in the UI, when I see all the evidence under 1 statement (e.g. VPS51 `affected by` ...) that has the qualifiers "`has increased activity or abundance`" only,  it looks to me as there is a "mismatch" in inferrence: I would expect the whole statement to be VPS51 `has increased activity or abundance caused by` and not simply `affected by`
This distinction for me is even more interesting to make for a user as it would differentiate cases like this one (although this one is a bad example as the output node normalization is wrong):
![image](https://github.com/NCATSTranslator/Feedback/assets/153299800/45e9dfb8-e973-4574-a278-cfd77e286a02)
where the inferred `affected by` comes from different predicates (we could potentially get the same output as well if the qualifers are different for the same predicate). 
For the second screenshot, if you copy paste the pk on ARAX UI, you can have access to the aux graphs, I believe that is what it was? I could not reproduce though, the results are different now.

**Comment by gprice1129** [comment] 2024-04-16 16:45
@sandrine-muller I think for this issue you should tag the underlying ARAs/KPs. The UI team is of the opinion that we should not be altering the predicates we are given to match expectations and instead the reasoning or underlying data should be improved.

**Comment by sandrine-muller** [comment] 2024-04-17 16:04
@sierra-moxon Please provide guidance here, thank you so much!

**Comment by sierra-moxon** [comment] 2024-05-16 23:34
If I understand the ticket correctly, we are interested in the inferred predicate matching the only existing predicate in the supporting edges instead of being "rolled up" to the affects predicate (maybe this is a default for inferred edges from Unsecret in this use case?)

@kaiwenho - is this something you can help us sort out?

**Comment by kaiwenho** [comment] 2024-05-21 20:29
From the Translator Architecture Committee Meeting on May 21 2024:
1. ARAs should include qualifiers specified in the query graph (the object aspect qualifier and the object direction qualifier for now; like it in the first attached example (Aragorn) below) in the inferred edges. 
2. Should the qualified predicate be included in the query graph and the returned inferred edges? @cbizon would like to dig into this deeper offline. 

Attaching two kinds of presentations of the answers for query 'What genes may be upregulated by Potassium Ion' from UI (@Genomewide)
From Aragorn - predicate: Affected By;  object aspect qualifier: Activity Or Abundance; object direction qualifier: Increased
<img width="861" alt="Screenshot 2024-05-21 at 2 48 30 PM" src="https://github.com/NCATSTranslator/Feedback/assets/67288473/1bade15d-ffcb-491b-bc85-b91f87b67cbb">
From BTE - predicate: Affected By
<img width="876" alt="Screenshot 2024-05-21 at 3 06 17 PM" src="https://github.com/NCATSTranslator/Feedback/assets/67288473/5cb20f49-76e8-47bd-a949-ee098d6ce5a2">

Unsecret Agent will improve the answers by adding object aspect qualifier and object direction qualifier in the inferred edges.

**Comment by gprice1129** [comment] 2024-05-22 18:40
The UI team has updated the MVP2 query to include the qualified predicate `biolink:causes` in the query graph. This change is live in CI.

**Comment by gprice1129** [comment] 2024-05-23 18:42
@cbizon @kaiwenho we had to roll back the above change in CI for the time being. It seems to be causing some issues for BTE.

**Comment by kaiwenho** [comment] 2024-07-02 01:51
This issue has been fixed in Unsecret CI, Test, and Prod. 
<img width="1109" alt="Screenshot 2024-07-01 at 8 41 23 PM" src="https://github.com/NCATSTranslator/Feedback/assets/67288473/bf61d654-d8fb-4c2b-bc1a-e03307500856">

**Comment by sstemann** [comment] 2024-11-08 18:29
looks resolved 

![image](https://github.com/user-attachments/assets/eebff7fb-0aa2-49a7-91ac-e287ed11d35b)

**Closed by sstemann** 2024-11-08 18:29 UTC
Labels: Hammerhead (Sprint 6) - due Oct 4 in CI
