### ISSUE TITLE
liberal usage of "physically_interacts_with"

### ISSUE THREAD

**Issue by sandrine-m** [NCATSTranslator/Feedback#34] opened 2022-10-26 19:54 UTC
The following query:
Query ID: 5bc57d1a-ad14-40ad-a819-adf78afafa77
```
{
  "edges": {
    "e00": {
      "attribute_constraints": [],
      "object": "n01",
      "predicates": [
        "biolink:physically_interacts_with"
      ],
      "qualifier_constraints": [],
      "subject": "n00"
    }
  },
  "nodes": {
    "n00": {
      "constraints": [],
      "ids": [
        "CHEMBL.COMPOUND:CHEMBL1431"
      ],
      "is_set": false
    },
    "n01": {
      "categories": [
        "biolink:Protein"
      ],
      "constraints": [],
      "is_set": false
    }
  }
}
```
When I look at aragorn results I find:
`PUBCHEM.COMPOUND:4091----biolink:physically_interacts_with----NCBIGene:7225`
The provenance info states:
PMID:31778750 : In this study, we demonstrated that metformin normalized TRPC6 expression _via_ AMPKalpha1 activation in podocytes exposed to high glucose concentrations. (2019 Nov 25)

This issue is similar to issue #22 where semmedb map to incorrect predicates.

**Comment by capasfield** [comment] 2023-01-13 17:59
Some visual cue on the edge (color coding or ???) would be a help.

**Comment by sierra-moxon** [comment] 2023-01-20 17:12
from TAQA:
can we move SEMMED physically interacts with to something less strong in Biolink? 
are we confusing confidence with data quality?  SEMMED is a text-mined resource.

maybe this comes down to how frequently this occurs - does it happen a lot of the time or most of the time does it get it right and we don't want to lose it? 

moving it higher in the hierarchy makes it "true" - sometimes less useful. 
we could do a sampling of SEMMED manually? 

grading of infores?  1-10?

**Comment by bill-baumgartner** [comment] 2023-02-08 23:14
Some additional context may be helpful here. The example above turns out to be a SemMedDB edge returned by Aragorn (as Sandrine notes above), but via RTX-KG2. See result 397 [here](https://arax.ncats.io/?r=b71b2b73-3ae3-46fd-ae4e-4d56e09b7714). The original SemMedDB predicate is `interacts_with`, and it appears that RTX-KG2 has mapped that predicate to `biolink:physically_interacts_with`. 

FWIW, when I read the supporting sentence, I don't see an interaction relationship at all between Metformin and TRPC6, so I think this assertion would be incorrect regardless of how specific of an interaction is indicated by the "interacts_with" predicate used. Also, it should be noted that SemMedDB does not have a `physically_interacts_with` predicate. It only has a more general `interacts_with` predicate. SemMedDB predicates are enumerated and defined in the appendix of [this paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3281188/).

**Comment by sandrine-m** [comment] 2023-02-09 18:55
@dkoslicki would you be able to confirm the presence of the predicate `biolink:physically_interacts_with` in RTX-KG2? how many edges are impacted? 
Thank you!

**Comment by saramsey** [comment] 2023-02-10 17:51
@sandrine-m thank you for bringing this to our team's attention. I can confirm that in the new build of RTX-KG2 (which is available at the "development" endpoint for the RTX-KG2 service), the source relation `SEMMEDDB:interacts_with` should be mapped to `biolink:interacts_with`. I see the following in the mapping code that we used for building RTX-KG2.8.0c, our latest (development endpoint) version:
<img width="432" alt="Screen Shot 2023-02-10 at 9 46 35 AM" src="https://user-images.githubusercontent.com/5562107/218161095-ef11e135-0bdd-4088-a0c3-b840d9fd6906.png">

I'm running some Neo4j queries to verify that this is the case, now.

As for the number of predicates affected on the production RTX-KG2 service (which is based on an older database, RTX-KG2.7.6c, if I recall correctly), I am not sure of the answer to that. Our team member Lili Acevedo can provide that information.

**Comment by saramsey** [comment] 2023-02-10 17:52
Yes, confirmed, it looks like this is not an issue in the "development" endpoint RTX-KG2 service:
<img width="1216" alt="Screen Shot 2023-02-10 at 9 51 45 AM" src="https://user-images.githubusercontent.com/5562107/218161541-5a7247eb-9530-4631-9009-8270ffb49c0d.png">

**Comment by saramsey** [comment] 2023-02-10 18:04
> can we move SEMMEDB physically_interacts_with to something less strong in Biolink?

Do you mean, like `biolink:interacts_with` or something?

**Comment by sandrine-m** [comment] 2023-02-10 18:35
@saramsey yes, that's what I meant yes. My feeling from the few examples I went into was that this mapping seemed incorrect and a more correct one should be higher in the Biolink hierarchy (what you've confirmed). If in the next production releases, the `biolink:physically_interacts_with` disappear, this issue can be closed.

**Comment by sierra-moxon** [comment] 2023-02-10 19:25
@cbizon - deployments of Biolink 3.1.0 should only be surfaced on DEV and CI environments at the moment, right?  I would say we don't want to deploy this to PROD before the relay if that is the case.  

As an alternative for resolution here, we could close this ticket with the expectation that this will make it to PROD RTX-KG2 when we get the green light to deploy Biolink3 to PROD?

**Comment by cbizon** [comment] 2023-02-13 14:40
@sierra-moxon correct.  Biolink 3.1.0 should be DEV/CI only for now.

**Comment by andrewsu** [comment] 2023-07-11 23:58
Since the specific example of `PUBCHEM.COMPOUND:4091----biolink:physically_interacts_with----NCBIGene:7225` would be filtered out by the proposed solution to #100, and since @saramsey confirmed that they changed the mapping of `SEMMEDDB:interacts_with` to `biolink:interacts_with` (instead of `biolink:physically_interacts_with`), I propose that we close this issue.

**Closed** 2023-07-13 18:11 UTC
Labels: KP - liberate usage of predicate, TMKP, EPIC: SEMMEDDB
