### ISSUE TITLE
Air treats cerebral Palsy (with dubious primary source)

### ISSUE THREAD

**Issue by mbrush** [NCATSTranslator/Feedback#624] opened 2023-11-01 17:07 UTC
Search for 'What may treat cerebral palsy' - look for 'Air' as a Result.
https://ui.test.transltr.io/main/results?l=Cerebral%20Palsy&i=MONDO:0006497&t=0&q=52bea588-5893-48b2-8561-16309ab0a1ed

![image](https://github.com/NCATSTranslator/Feedback/assets/5184212/b5c38520-8d61-432f-94ba-c1733e654dfc)

Issue 1 is that '**Air**' should likely be on a blocklist.  Also found '**Aerosols**' in the list of results. And '**Pharmaceutical Preparations**' which is the top result.

Issue 2 is that the only primary source is reported as 'Service Provider TRAPI Endpoints' . . . not sure what this is, but doesn't seem like a valid primary source. I have seen this showing up as a primary source for many other answers as well (e.g. Tizanidine, Diazepam, Phenol)

**Comment by sierra-moxon** [comment] 2024-01-23 20:18
from TAQA: we don't see "air" necessarily in the top set of 300 results, but we do see Oxygen in the result coming from TMKP (but we see a paper that talks about hyperbaric oxygen treating CP, which is dubious -- eg. the paper gives the note that it does not show significant improvement of symptoms), but technically not wrong. 

pharmaceutical preparations should be on the "too generic to be useful" list 
aerosols we are not convinced should be blocked.

**Comment by gaurav** [comment] 2024-07-19 06:16
I'm assigning this to Mark to add to the answer blocklist.

**Comment by sstemann** [comment] 2024-08-07 22:48
since air, aersols and pharmaceuticals are no longer displayed in Prod i'm not super sure how to get to the EPC re: service provider trapi endpoints.  let's raise a separate issue if it's reproducible.

https://ui.transltr.io/main/results?l=Cerebral%20Palsy&i=MONDO:0006497&t=0&r=0&q=43ef9df9-a37d-4c38-bfbd-4fa9bad0294f

**Closed by sstemann** 2024-08-07 22:48 UTC
Labels: EPC, blocked answers
