### ISSUE TITLE
not sure the result is really for "fig allergenic extract"

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#129] opened 2023-02-17 17:19 UTC
I've seen this a couple of times in the UI and it seems to be coming from BTE.  

https://ui.ci.transltr.io/results?q=9ed3a7bc-7faf-45a2-bed1-121ecd110831

![image](https://user-images.githubusercontent.com/38321826/219720134-3e10f7f5-4af4-4b6b-86d9-5eeab49ab095.png)

https://arax.ncats.io/?r=9ed3a7bc-7faf-45a2-bed1-121ecd110831

![image](https://user-images.githubusercontent.com/38321826/219720681-faeb40e3-05e7-4871-ab10-62fe68d95382.png)

https://pubmed.ncbi.nlm.nih.gov/PMC5332279/
I'm not sure "fig allergenic extract" is in this paper, but I see "Fig. [#]" quite a bit.

**Comment by sstemann** [comment] 2023-02-17 17:20
@andrewsu feel free to re-assign but I feel like someone from your team can track this down better than I can and I'm not sure it's ready for a TAQA review.

**Comment by andrewsu** [comment] 2023-02-17 21:07
A few notes:
* I can't load the results on the UI https://ui.ci.transltr.io/results?q=9ed3a7bc-7faf-45a2-bed1-121ecd110831 in my browser. I'm currently on my wimpy laptop so that could be the issue, but still noting it in case anyone else observes this behavior.
* The general topology seen at the top of the list -- one ChemicalEntity connected to many genes each of which is connected to one (or a small number) of diseases; see screenshot below -- is I think in large part due to the fact that the query CURIE `MONDO:0100062` [has many subtypes](https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0100062), each of which has a different genetic cause.  Because of how we do node expansion (from a parent node to all its children) and combining of results, this is one common expected topology.  Because of how we do scoring (sum over all edges) these results with lots of edges are also expected to be highly ranked. Bottom line, things are working as designed, and even though the results here might look a little odd, I don't see an obvious change in logic that we'd want to make.
![image](https://user-images.githubusercontent.com/2635409/219790627-664ef63f-8dd6-476d-8c2f-e96dbc1c7027.png)
* The first result talking about "fig allergenic extract" I agree appears to be an error in named entity recognition (NER).  Those edges look like they're coming from text-mining provider, so tagging @bill-baumgartner.

**Comment by bill-baumgartner** [comment] 2023-03-08 17:56
Update: We have pushed a fix for the `fig allergenic extract` issue to CI. I've tested similar queries to make sure that this drug and other `Fig`-related entities are not returned by our system. I attempted to reproduce this exact query ([yesterday](https://arax.ci.transltr.io/?r=35e2e752-1957-4593-a239-7aeec0350f7f) & [today](https://arax.ci.transltr.io/?r=50c58314-f04a-46b4-a81f-f235dd9c34dc)) but can't seem to get a result set from BTE to confirm.

**Comment by sierra-moxon** [comment] 2023-03-10 16:00
@andrewsu  - is the "fig" results already fixed in BTE? :)

**Comment by sierra-moxon** [comment] 2023-03-10 17:52
from TAQA: 
Andrew: long-running queries on BTE are being investigated.  Need to explore the use cases behind the searches - maybe there is a better way to test this. 
Andy: might not be another way to test this from UI POV, but maybe another way?
Chris: I think that this issue is related to the “race” one we were discussing on DM yesterday and using NER to get classes from the text should help it as well
Andy: use one query to get all the ids, then I use the ids to query again (sometimes can be 1000s), this broke BTE/others/etc.  Gets too big.  If there is something that knows about gene-gene but not drug-gene.  Do I get the same results from translator if I ask a two hop if I ask two one hops?  (probably not) 
Tyler: need some dev to make that test above work without breaking things. 

Andrew + Bill: the answer is fixed from Bill's end.  Set up something to ask TMKP directly, then close this issue. 
separate issue about one/two is for Architecture.

**Comment by sierra-moxon** [comment] 2023-03-10 17:53
Sierra: break into two tickets, one can be closed after testing TMKP with a special BTE service, second should go to architecture to discuss one vs. two hop query results.

**Comment by colleenXu** [comment] 2023-03-11 02:02
It should be fixed. 

The BioThings API has been updated and [when queried](https://pending.biothings.io/text_mining_targeted_association/query?q=subject.id:%22DRUGBANK:DB10633%22%20OR%20object.id:%22DRUGBANK:DB10633%22), there's no data with the [fig DRUGBANK ID](https://go.drugbank.com/drugs/DB10633) `DRUGBANK:DB10633`

If Fig `DRUGBANK:DB10633 -> NamedThing` is sent to TMKP through BTE-prod (by POSTing to `https://bte.transltr.io/v1/smartapi/978fe380a147a8641caf72320862697b/query`), there's no results / KG. The txt file contains the TRAPI response json. 
[direct_no_more_fig.txt](https://github.com/NCATSTranslator/Feedback/files/10947330/direct_no_more_fig.txt)

Finally, if I run the creative-mode query on my local BTE instance, I no longer get "fig allergenic extract" in the results. The txt file contains the TRAPI response json. 
[creative_no_fig.txt](https://github.com/NCATSTranslator/Feedback/files/10947339/creative_no_fig.txt)

**Comment by sierra-moxon** [comment] 2023-05-05 15:28
I am going to close; since we can no longer see `fig allergenic extract` in the result set.

**Closed by sierra-moxon** 2023-05-05 15:28 UTC
Labels: text mined
