### ISSUE TITLE
Aggravates disease rather than treats (text mining)

### ISSUE THREAD

**Issue by IritR** [NCATSTranslator/Feedback#506] opened 2023-09-01 00:29 UTC
When searching for treatments for [Aceruloplasminemia](https://ui.ci.transltr.io/main/results?l=Aceruloplasminemia&i=MONDO:0011426&t=0&q=348ce982-848b-424b-9746-de2caaeadeb6) the top result was iron. Iron accumulation is actually the problem in aceruloplasminemia, and the correct treatment is iron chelation. The source of the result is Text Mining Targeted Association API.

**Comment by sandrine-muller-research** [comment] 2023-10-05 16:32
Retested today on [PROD](https://ui.transltr.io/main/results?l=Aceruloplasminemia&i=MONDO:0011426&t=0&q=ab418a2d-e491-422c-8b58-84c921313a39):
Iron could be found but with a different graph

**Comment by sandrine-muller-research** [comment] 2023-10-06 16:54
splitting this issue for reasoning issue

**Comment by codewarrior2000** [comment] 2023-10-06 17:27
In case it helps with the troubleshooting, Iron (Fe) is not the cause of Aceruloplasminemia, which is an autosomal disorder caused by a mutation in the CP gene. As @IritR pointed out Fe accumulation is a symptom of Aceruloplasminemia.

**Comment by sandrine-muller-research** [comment] 2023-10-06 18:39
Sorry for not being clever on label reuse, I updated the label to encompass this specific example: [causes/aggravation of symptoms not treats](https://github.com/NCATSTranslator/Feedback/labels/causes%2Faggravation%20of%20symptoms%20not%20treats)
a case of opposite of what... where the reasoning leads to the cause or aggravation of symptoms
I had to play a bit with the definition because I am restricted in length so it is hard to get precise.
Please @codewarrior2000 or @IritR feel free to remove that label if you think it is not triaged appropriately. 
Thanks

**Comment by codewarrior2000** [comment] 2023-10-06 23:41
In case it helps with the troubleshooting, the graph should depict that Iron is "affected by CP" gene mutation not that Iron "affects CP" gene. In other words, that edge is reversed, it's in the wrong direction.

**Comment by sandrine-muller-research** [comment] 2023-10-10 14:16
@codewarrior2000 I do not think the labels you put goes towards fixing the issue. You are talking about the direction of the edge that you'd like to see given the disease. First, this is not the question asked so even if the graph would be correct it should not show up. (Though you can use ARAX UI and test whether the opposite edge is found, this is not the edge used by Unsecret).
I went in and checked the sources that TMKP is stating, for example, the first one (in the context of anemia, see paper here):
"Although the ceruloplasmin levels were depleted (48.9 mg/dL vs 41.4 mg/dL, p=0.035) during ferrous iron treatment, the copper and zinc levels remained unchanged."  so **the direction of the edge is correct** for this statement (tmkp:6330bda13d6bcd14f337c11c633d3ebb376a4d9960b5e668ef385885640a72df).
The second statement is completely uncorrect and should be removed ([0c971faee9fc7fa93266b11cbb06d9de6a60d04c2eb174430601b42bad1990ef](https://tmui.text-mining-kp.org/evidence/0c971faee9fc7fa93266b11cbb06d9de6a60d04c2eb174430601b42bad1990ef)). 
The third is reversed:_Superoxide dismutase (SOD) and catalase did not affect initial rates of iron release whereas ceruloplasmin was an effective inhibitor of iron release._

**Comment by codewarrior2000** [comment] 2023-10-10 17:00
@sandrine-muller-research The query was “What drugs may treat:[Aceruloplasminemia](http://purl.obolibrary.org/obo/MONDO_0011426)” Unfortunately, a top result was Iron — due to a misinterpretation that Iron affects the CP gene, an assertion not supported in the literature.
￼

**Comment by sandrine-muller-research** [comment] 2023-10-11 16:16
According to Unsecret aux graph (medik:auxiliary_graph#66) from ARAX for their creative mode query:
<img width="869" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/22616936/1efe8757-0691-4849-b6ee-cd303b77083b">
And as cited in their aux graph from[ this paper](https://pubmed.ncbi.nlm.nih.gov/12907830/):
![image](https://github.com/NCATSTranslator/Feedback/assets/22616936/71a53939-5910-4285-881a-667d85af5553)
the edge is supported.

**Comment by sierra-moxon** [comment] 2024-07-11 18:13
This has been added to our test assets, and is running weekly.  Folks are addressing test failures.  I am closing this one as completed for tracking in that effort now.  Thank you to everyone who identified this issue and got it into our automated P/F tests!  it is a great effort and a great help.

**Closed by sierra-moxon** 2024-07-11 18:13 UTC
Labels: TMKP, opposite of what I asked for, test asset, causes/aggravation of symptoms not treats, does not treat, Edge reversed
