### ISSUE TITLE
Sources shouldn't show Source "Semantic Medline Database" without any publications

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#322] opened 2023-06-06 20:19 UTC
1. MVP 1 in the Test UI for Niemann Pick disease:  https://ui.test.transltr.io/results?l=Niemann-pick%20Disease&t=0&q=280c5d97-f8b1-4dcd-a809-a8136f3d3b64
2. Expand the result for Cholesterol
3. In this path:
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/2d154f63-2c8b-4745-942b-017898b96dd1)
4. Click the edge between Cholesterol and ABCA1
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/21b4c3fe-8643-44ed-9eb0-c864971cd50f)

5.  In the source it looks like there are specific pubs
Robokop
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/e7e0d089-d991-4a45-aa47-17a4747508d7)

Unsecret
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/d190729b-f00d-4193-bc0d-dcd57d0e6123)

**Comment by gprice1129** [comment] 2023-06-16 04:02
This was caused by a bug on the UI. It is fixed now. Closing.

**Closed by gprice1129** 2023-06-16 04:02 UTC
Labels: infores
