### ISSUE TITLE
Plant subclass of a human anatomical part

### ISSUE THREAD

**Issue by sandrine-m** [NCATSTranslator/Feedback#172] opened 2023-05-04 17:15 UTC
This query has been made throught ARAX (posted to ARAX, ARS was returning an error) using the following JSON:
```
{
   "edges": {
      "e00": {
         "subject":   "n00",
         "object":    "n01",
         "predicates": ["biolink:related_to"]
      }
   },
   "nodes": {
      "n00": {
         "ids":        ["UMLS:C0697176"]
      },
      "n01": {
         "categories":  ["biolink:NamedThing"]
      }
   }
}
```

The 7th result is 3 edges relating the input (a plant) to a human body part (here tooth):
<img width="1106" alt="image" src="https://user-images.githubusercontent.com/66342541/236277642-005059b3-a7b7-42d5-b5ac-cf7be9b85617.png">

Info on input:
<html>
<body>

category | biolink:OrganismTaxon
-- | --
identifier | UMLS:C0697176

</body>
</html>

**Comment by balhoff** [comment] 2023-05-04 19:48
This is definitely not in Ubergraph (at least currently). I suspect this could be a NodeNorm issue? Something lumping Uberon "tooth root" with NCBI taxon "root"? @gaurav can you query this?

**Comment by gaurav** [comment] 2023-05-04 20:24
According to http://arax.ncats.io/?term=UBERON:0003677, ARAX considers UBERON:0003677 to be identical to NCBITaxon:1 (probably because they both have the word "root" as their label). This is not coming from the current NodeNorm, which does not clique NCBITaxon:1 with any other identifier ([link](https://nodenorm.transltr.io/1.3/get_normalized_nodes?curie=NCBITaxon%3A1&conflate=true)). The source information says "KG2,SRI_NN"; I'm not sure if that means it came primarily from KG2 or from a previous version of NodeNorm, but it should be updated in ARAX to fix this bug.

<details>
<summary>Here's my process in figuring this out if anyone's curious.</summary>

The problem seems to be happening somewhere in ARAX. I tried replicating this query on ARAX (https://arax.ncats.io/?r=136015) and confirmed that the UMLS:C0697176 --(biolink:subclass_of)--> UBERON:0003677 edge is present in those results. According to ARAX, this is the query it is sending Uberongraph:

```json
{
  "message": {
    "query_graph": {
      "edges": {
        "e00": {
          "object": "n01",
          "predicates": [
            "biolink:related_to"
          ],
          "subject": "n00"
        }
      },
      "nodes": {
        "n00": {
          "categories": [
            "biolink:OrganismTaxon"
          ],
          "ids": [
            "NCBITaxon:159425"
          ],
          "is_set": false
        },
        "n01": {
          "categories": [
            "biolink:NamedThing"
          ],
          "is_set": true
        }
      }
    }
  }
}
```

However, when I send that query directly to Uberongraph at https://automat.transltr.io/#/uberongraph/reasoner_api_1_3_query_post, I get [this response](https://github.com/NCATSTranslator/Feedback/files/11401127/response_1683230495596.txt), which doesn't have any references to UBERON.

So it looks like one of the parents of NCBITaxon:159425 are being misnormalized into UBERON:0003677 (possibly because UBERON:0003677 has the label ["tooth root"](http://purl.obolibrary.org/obo/UBERON_0003677)). However, I can only find a single reference to UMLS:C0697176 in NodeNorm, and it is not combined with any identifier there (not even NCBITaxon:159425, which it really should be: https://github.com/TranslatorSRI/Babel/issues/129)

I think ARAX does some normalization of its own, and that's where this is coming from.
</details>

**Comment by sandrine-m** [comment] 2023-05-04 20:55
thank you so much @gaurav ! @sierra-moxon do you know who is the person on "KG2,SRI_NN"/ARAX we can ping regarding this bug?

**Comment by sierra-moxon** [comment] 2023-05-04 21:01
@amykglen - is this something that would be from RTX-KG2?  or @dkoslicki - is this a ARAX user issue?

**Comment by dkoslicki** [comment] 2023-05-04 21:20
@sierra-moxon, On first pass, it looks like Automat is the one which came up with this edge. I used the following workflow operation to restrict the results to be only those from RTX-KG2:
```
{
  "workflow": [
    {
      "id": "fill",
      "parameters": {
        "allowlist": [
          "infores:rtx-kg2"
        ]
      }
    },
    {
      "id": "bind"
    },
    {
      "id": "complete_results"
    }
  ],
  "message": {
    "query_graph": {
      "edges": {
        "e0": {
          "predicates": [
            "biolink:related_to"
          ],
          "subject": "n0",
          "object": "n1"
        }
      },
      "nodes": {
        "n0": {
          "ids": [
            "UMLS:C0697176"
          ],
          "categories": [
            "biolink:OrganismTaxon"
          ],
          "is_set": false,
          "name": "Passiflora incarnata"
        },
        "n1": {
          "is_set": false
        }
      }
    }
  },
  "submitter": "ARAX GUI",
  "stream_progress": true,
  "query_options": {
    "kp_timeout": "30",
    "prune_threshold": "50"
  }
}
```
Tooth root is now missing.

**Comment by sierra-moxon** [comment] 2023-05-04 21:29
Thanks @dkoslicki - at this point @sandrine-m, I am not sure who to ask.  Maybe @YaphetKG might have some insight?   I'll set this to review at TAQA :)

**Comment by sandrine-m** [comment] 2023-05-04 21:35
Thanks so much @sierra-moxon and @dkoslicki ! I'll try to ask on slack see if I get any response in the meantime

**Comment by amykglen** [comment] 2023-05-05 17:58
so I just took a peek and this definitely appears to be due to an ARAX synonymization problem

I wrote this up in https://github.com/RTXteam/RTX/issues/2014

the good news is that it's fixed in the new ARAX synonymizer, which should be deployed (at least to dev/staging) by early next week

I'm going to remove @EvanDietzMorris since this seems to be purely an ARAX problem

**Comment by jaredroach** [comment] 2023-05-12 16:14
Issue should be closed with fix in the new ARAX synonymizer.

**Closed by jaredroach** 2023-05-12 16:14 UTC
Labels: bug
