### ISSUE TITLE
Combinatorial explosion in answers

### ISSUE THREAD

**Issue by karafecho** [NCATSTranslator/Feedback#78] opened 2022-12-15 21:22 UTC
The QotM surfaced a (known) issue related to a combinatorial explosion in answers. Specifically, answer sets explode and become unmanageable each time an intermediary node is added to a query. For example, moving from connections between _ATP1A3_ and chemical entities or diseases yields a reasonable number of results; however, when you add in intermediary genes and pathways, the answer sets blow up. Known issue, and related to performance, I think, but creating a new ticket for this particular use case.

**Comment by sierra-moxon** [comment] 2023-01-04 21:18
duplicate of #33

**Closed** 2023-01-04 21:18 UTC
Labels: O&O issue
