### ISSUE TITLE
Pathwhiz Node Types - No Links outs, no labels

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#540] opened 2023-09-13 01:35 UTC
Steps to recreate:

1.  Prod  UI > Login
2. Drug > Disease:  https://ui.transltr.io/main/results?l=Familial%20Pityriasis%20Rubra%20Pilaris&i=MONDO:0008251&t=0&q=17e013e2-9da0-4a60-b650-3a21eb8772ba
3. Text Search > "pathwhiz"
4. take a look at the nodes, links out to a 404 page
 
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/d2cdfd92-96af-46b2-9b9f-19737f10f352)

**Comment by dnsmith124** [comment] 2023-09-13 17:00
It appears this was caused by some provenance links coming in as strings and others as arrays, where the latter was not getting stopped by the conditional that determines whether the link icon should be displayed. 

I've corrected this, and the fix will go to CI later today. I'll update the ticket when it does.

**Comment by dnsmith124** [comment] 2023-09-13 19:29
So the fix for this has been deployed to CI, but I can no longer get any results that include 'Pathwhiz' to return. I even returned to the query I ran this morning on CI to verify the bug and the result that had the 'Pathwhiz' nodes isn't showing there anymore either. 

I do still get the result when hitting the prod ARS locally, and it's resolved for me there. We can retest once the change is deployed to test and prod before closing to confirm the fix is working as intended.

**Comment by Genomewide** [comment] 2023-09-28 23:32
@sstemann Should this be sent to Richard to see if this is caught by the error handling or to someone (?) who can say if it is Trapi compliant?  I think our team is done with the ticket though.

**Comment by gprice1129** [comment] 2023-10-06 20:36
Closing. Please reopen if more discussion is needed.

**Closed by gprice1129** 2023-10-06 20:36 UTC
Labels: bug, UI - display
