### ISSUE TITLE
Additional information section in feedback does not transfer to the repo

### ISSUE THREAD

**Issue by Genomewide** [NCATSTranslator/Feedback#16] opened 2022-10-07 22:59 UTC
Everything I wrote in the free text section below the 'steps to replicate' did not show up on the ticket anywhere.

**Comment by dnsmith124** [comment] 2022-10-21 17:09
As far as I can tell the value of the Comments input field is being sent to the issue router, so this may have something to do with how the issue router handles ticket generation.

**Comment by maximusunc** [comment] 2022-11-09 17:05
I have been unable to reproduce this issue. Note: I also see steps to reproduce in other issues, so it looks like it's working for other people. I'm going to close this issue, but feel free to open back up if you can reproduce.

**Closed by maximusunc** 2022-11-09 17:05 UTC
Labels: bug
