### ISSUE TITLE
Water treats premature menopause 

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#730] opened 2024-02-28 18:39 UTC
## Screenshots:

    Would be really nice to understand the provenance. With no links to the literature or to specific entries in a database or some other logic or providence, just saying it comes from a source like "SPOKE" makes this result relatively useless - although I guess it is somewhat useful is that it tickles the imagination enough so that I can go look to see if I can find evidence in Perplexity, Google Scholar, or PubMed - i.e., reverse engineering the answer using another resource. This is in the context of trying to troubleshoot the test criteria that Translator should not report "Basis treats premature menopause". I am trying to figure out if this result "Nictotinamide riboside treats menopause" is a synonym for that bad undesirable result, and if indeed it is undesirable.

**Comment by gglusman** [comment] 2024-02-28 18:50
A somewhat confusing report since the 'Basis' result isn't from SPOKE, and "nicotinamide riboside" (after correcting the typo) isn't a result either.
I'm guessing the user meant this:
![image](https://github.com/NCATSTranslator/Feedback/assets/3977332/d9d4c45a-752d-40c3-9401-4e6ee610920e)
...which is indeed not very helpful in terms of EPC.

**Comment by cartmanbeck** [comment] 2024-03-01 16:01
Having the only listed source for knowledge as "SPOKE KP" with no link explaining what it is is definitely insufficient EPC. We really need to get more detail about the underlying connections within SPOKE that support this result. I would consider SPOKE an aggregator tool, not a primary source.

**Comment by mbrush** [comment] 2024-03-01 17:31
I took a look at this result and there are many strange things happening - including the fact that an 'associated with' edge from SPOKE is showing up as an answer edge, and that the one Inferred answer path seems to collapse support paths from ARAGORN and Improving Agent.

![image](https://github.com/NCATSTranslator/Feedback/assets/5184212/5ced2fec-9db4-4a67-91c7-b4265a3f5c6e)

I did note that the Improving Agent result in the ARAX interface looks as I expect it, so it may be that something goes wrong in the UI implementation.

**Comment by sstemann** [comment] 2024-03-01 17:43
related to #706

**Comment by sstemann** [comment] 2024-03-01 17:49
- SPOKE link to wiki page would improve provenance for this user

**Comment by mbrush** [comment] 2024-03-01 18:02
Per discussion on the 3-1-24 TAWA Call, a few issues to address here:
 
1.	'Basis' is showing up as a result - seems like this is a text mining mis-parse that should be on a blocklist.
 
2.	An 'associated with' edge from SPOKE is showing up as an answer edge for a 'treats' query.

3.	There is not link to a SPOKE KP wiki page provided in the UI
 
4.	The Inferred answer path seems to collapse support paths from ARAGORN and Improving Agent (see screen shot above).  My understanding is that separate Answer Edges are shown in the UI in cases where two ARAs predict the result - so that the UI could display the specific provenance/evidence used by each ARA in making their prediction.  If this is the case, this is a bug.
 
5.	ARAGORN reasoner is returning direct 'treats' edges as support paths for treats predictions - which sounds like it is a known issue based on #706

**Comment by bill-baumgartner** [comment] 2024-03-01 23:14
Regarding (1) above, the `Basis` mis-parse appears to be from SEMMED DB.

**Comment by gprice1129** [comment] 2024-03-07 17:56
@mbrush edges can be merged across different ARAs if their knowledge types are the same. In this case both of the inferred edges are curated, so they are merged together.

**Comment by sierra-moxon** [comment] 2024-07-11 21:51
Retested today on TEST: https://ui.test.transltr.io/main/results?l=Premature%20Menopause&i=MONDO:0001119&t=0&r=0&q=d36aac6c-b259-4a05-aaf5-f38898faec3f

All of the issues identified in the list above are resolved!  hooray! 
- better EPC
- support paths are intelligible and I can trace the provenance
- I don't see generic nodes like "basis" being returned
- I don't see associated_with edges any longer
- nicotinic acid is part of the support paths, which makes sense.
 
However, there are still some questionable answers being returned. I think we're trying to say that Vitamin B is a good treatment for some of the symptoms of menopause...in many different ways, including via "water" and "hydron" treating premature menopause.  

<img width="905" alt="Screen Shot 2024-07-11 at 2 50 32 PM" src="https://github.com/user-attachments/assets/82570200-a691-42c9-b4bc-0942683d25a5">

**Comment by gglusman** [comment] 2024-07-11 22:22
I just looked at those paths 'supporting' water as a result...

1) Water is part of cyclophosphamide, which [treats+] premature menopause.
...except a mouseover shows that Cyclophosphamide (Drug) is described as "the anhydrous form of cyclophosphamide", so no, water is not part of that.
![image](https://github.com/user-attachments/assets/f01bebd6-dea5-445a-9496-e27b2d25a3b1)

2) Water has increased activity caused by insulin, which causes increased activity of estradiol valerate...
...I have no idea what increasing water activity means. But again, this is a mixture of direct and reverse predicates, leading to meaningless answers. If insulin affects water and estradiol, and estradiol treats the phenotype, this implies nothing about a relationship between water and the phenotype.
![image](https://github.com/user-attachments/assets/38ddd48a-22b3-47ff-adbd-c27acad419f6)

3) Similar to 2, but involving TNF.

4) There's a pathway that has both water and cyclophosphamide. The latter does something. This implies nothing about the former. Again, mixing direct and reverse predicates.

5-7) Like 4, with nicotinic acid, and different pathways.

**Comment by gprice1129** [comment] 2024-07-12 20:22
@sierra-moxon @sstemann close?

**Comment by gglusman** [comment] 2024-07-12 21:44
@gprice1129 Should I start new tickets with what I wrote yesterday?

**Comment by sierra-moxon** [comment] 2024-07-25 23:59
@sundareswarpullela

**Comment by cbizon** [comment] 2024-08-30 15:36
Retest, now that pathwhiz is removed in Aragorn

**Comment by sstemann** [comment] 2024-11-06 20:45
water and Basis are gone.  The Spoke issues remain.

**Closed by sstemann** 2024-11-06 20:45 UTC
Labels: Hammerhead (Sprint 6) - due Oct 4 in CI
