### ISSUE TITLE
Strange logic (or incorrect edge type) for what gene's activity may be decreased by lithium

### ISSUE THREAD

**Issue by khanspers** [NCATSTranslator/Feedback#830] opened 2024-07-03 15:42 UTC
https://ui.test.transltr.io/main/results?l=Lithium%20Ion&i=CHEBI:49713&t=4&r=0&q=9b265413-9819-42bb-a913-59b7138a36ad

EPH2B is returned, and the inferred edge looks like this:

EPHB2 - _downregulates_ - AKT1 - _has increased activity or abundance caused by_ - Lithium ion  (same pattern for INS and GSK3B)

To me, that logic doesn't say anything about the effect of lithium on EPH2B, which is what the query is asking. 

<img width="1191" alt="Screen Shot 2024-07-03 at 8 26 06 AM" src="https://github.com/NCATSTranslator/Feedback/assets/1442197/8fa60f9e-07df-44d0-8fe6-500487930632">

It looks like the answer is coming from BTE (deduced by filtering for EPHB2 in the UI, then looking at Reasoning Agents in the Filters menu), and in ARAX I see the following support graph:

<img width="1405" alt="Screen Shot 2024-07-03 at 8 31 14 AM" src="https://github.com/NCATSTranslator/Feedback/assets/1442197/860079d8-3f94-4b48-91c7-00db79f9cf89">

Here there are affects/regulates edges from AKT1, INS, and GSK3A to EPHB2.  So it seems the _downregulates_ edge from EPH2B to AKT1/INS/GSK3A is just incorrect in the UI and should be something that indicates the interaction is the other direction?

**Comment by mikebada** [comment] 2024-07-05 00:26
I agree; I think if the first assertion in the path were instead `EPHB2` `downregulated_by` `AKT1`, I think it would be valid...

**Comment by sierra-moxon** [comment] 2024-07-11 19:31
@andrewsu - I noticed the result in the screenshot has `infores:biothings-explorer` tagged.  Would you have a chance to take a look at this one?

**Comment by andrewsu** [comment] 2024-07-11 19:41
If I'm reading this correctly, I think @khanspers is pointing out that the visualization in the UI (the first screenshot above) does not reflect what BTE is outputting (and visualized by ARAX in the second screenshot above). So I think this is an issue for the UI team to look into? tagging @Genomewide 

(@khanspers @gglusman @mikebada please let me know if I'm missing something, or maybe add a 👍reaction if you agree...)

**Comment by sierra-moxon** [comment] 2024-07-11 19:44
apologies - yes, you are right.  thank you for taking a look.

**Comment by gglusman** [comment] 2024-07-11 20:06
I think the main issue here is that by mixing directionality of predicates (as evidenced by the active voice in the 1st "downregulates", and the couched passive voice in the 2nd "...caused by"), the pathway itself is not relevant as an answer to the query. That's the connection to #468 I made above.
If we instead used normalized predicate directions and stated that "Lithium ion increases activity or abundance of AKT1", and correspondingly displayed the arrow from right to left, the issue would become visually apparent. But how to display it is not the issue. This pathway logic is producing incorrect results.

**Comment by andrewsu** [comment] 2024-07-11 20:29
BTE is reporting two edges for AKT1 -- `Lithium - affects / increases - AKT1` and `AKT1 - regulates / downregulates - EPHB2` -- both in the "forward direction". This pathway logic seems fine to me, and it looks like the UI has incorrectly reversed the directionality in displaying `EPHB2 - downregulates - AKT1`. @gglusman are you seeing this differently?

**Comment by gprice1129** [comment] 2024-07-11 20:40
I agree with your assessment @andrewsu. The UI should be displaying `is downregulated by` or something equivalent.

**Comment by gprice1129** [comment] 2024-07-11 21:50
Found and fixed the bug locally. Will update when pushed to Test.

**Comment by gprice1129** [comment] 2024-07-15 17:38
This is fixed in Test. Closing.

**Closed by gprice1129** 2024-07-15 17:38 UTC
Labels: UI - display, transitive, Edge reversed
