### ISSUE TITLE
If I select 'Atherosclerosis' from the type-ahead, the preferred term it uses to represent this concept isn't ideal 'atherogenesis'. Also, the term definition links out to UMLS, which requires a license to access. It might be better to link out to a public website definition source for something like UMLS:C1563937 like https://www.ncbi.nlm.nih.gov/medgen/?term=C1563937


### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#87] opened 2022-12-22 12:57 UTC

**Comment by sierra-moxon** [comment] 2023-01-06 19:58
closing as duplicate of #42

**Closed by sierra-moxon** 2023-01-06 19:58 UTC
