### ISSUE TITLE
META LIST: potentially embarassing terms / statements

### ISSUE THREAD

**Issue by colleenXu** [NCATSTranslator/Feedback#287] opened 2023-06-06 15:11 UTC

**Comment by Genomewide** [comment] 2023-06-06 15:38
This list was found by searching for CRT - 


![Image](https://github.com/NCATSTranslator/Feedback/assets/55069176/67a65eaf-66bb-435b-9d3d-829049eb761c)


This may be a full index of loaded terms
https://www.apa.org/pubs/databases/training/thesaurus

It looks like the terms may have UMLS curies as well?

**Comment by sstemann** [comment] 2023-06-06 19:08
Ozone as a result for "may treat" both as a result as well as in many paths

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/8119cb93-e882-4362-908b-cb2fa9478abb)

**Comment by gloriachin** [comment] 2023-06-09 16:09
What gene is upregulated by venetoclax?

<img width="1212" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/2994757/02cc2277-a66d-4295-afe6-2b108604c7a7">
All evidence shows BCL2 has decreased activity caused by venetoclax, but the answer is wrong, which shows up-regulation.

**Comment by sandrine-m** [comment] 2023-07-25 21:15
Bisphenol A treats Maturity Onset Diabetes of the Young ([issue](https://github.com/NCATSTranslator/Feedback/issues/444), [PK](https://ui.test.transltr.io/results?l=Maturity-onset%20Diabetes%20Of%20The%20Young&i=MONDO:0018911&t=0&q=325624e2-6053-4e2b-963c-9f13981f5070))

**Comment by sandrine-m** [comment] 2023-08-28 22:21
https://ui.ci.transltr.io/results?l=Obstructive%20Sleep%20Apnea%20Syndrome&i=MONDO:0007147&t=0&q=80bb5ee1-40ec-4f99-a6cb-2677c5f496da
Methamphetamine treats [Obstructive Sleep Apnea Syndrome](https://monarchinitiative.org/disease/MONDO:0007147)

**Comment by andrewsu** [comment] 2023-08-28 23:28
> https://ui.ci.transltr.io/results?l=Obstructive%20Sleep%20Apnea%20Syndrome&i=MONDO:0007147&t=0&q=80bb5ee1-40ec-4f99-a6cb-2677c5f496da 
> Methamphetamine treats [Obstructive Sleep Apnea Syndrome](https://monarchinitiative.org/disease/MONDO:0007147)

Quick note that this result is coming from Unsecret Agent.  Also, the answer preceding methamphetamine is "Soot", with a reasoning path of `Soot - affects - IL6 - associated_with - Obstructive Sleep Apnea Syndrome` -- probably also a reasonable example of "potentially embarassing"...

**Comment by sandrine-m** [comment] 2023-08-29 18:29
@andrewsu my "reasoning" to not put the soot issue in this thread that it is more of an "an opposite of what I ask for" type of issue rather than an "embarrassing" type: e.g. as a user I find that result interesting and I do not want to filter it

**Comment by gaurav** [comment] 2024-02-22 23:14
I've made sure that all the terms from here have been added to the [Blocklist spreadsheet](https://docs.google.com/spreadsheets/d/1UR2eplHBvFRwaSIVOhlB44wpfNPY1z7AVzUkqzDqIWA/edit#gid=0) (there's a ticket to make sure they are no longer visible at https://github.com/NCATSTranslator/Blocklists/issues/33) and reported the Results Blocklist terms at https://github.com/NCATSTranslator/Blocklists/issues/44. I think we can close this issue.

**Closed by gaurav** 2024-02-22 23:14 UTC
Labels: Red team
