### ISSUE TITLE
I asked what "upregulates" ATP1A2, but the evidence seems to indicate that these top two results should actually downregulate the gene. Seems the evidence is solid, but the directionality is wrong.

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#256] opened 2023-06-05 17:27 UTC
## Steps to reproduce:
Ask "What chemical upregulates... ATP1A2"
Look at first two results: Daunorubicin and Digitoxin
Look at paths explaining the evidence.
Link: https://ui.test.transltr.io/results?l=ATP1A2&t=1&q=fc1b681d-cf5e-4ea3-bf59-17cd73a96549

**Comment by sierra-moxon** [comment] 2023-06-06 13:40
from TAQA:
common issue; despite the opposite, the score seems very "confident" -- ~ 99+ 
from Chris B: this is a ranking issue.  - ARA should take a look. 
Should we not show if it's the opposite? 
Perhaps from SPOKE - bipartite qualifier. 
Can't be fixed upstream, then maybe we could label those that have directionality (by source) appropriately (else they are not directional) in the UI;  we'd prefer to push to the ARAs.

**Comment by cbizon** [comment] 2023-07-20 01:58
Current CI: aca1d679-222e-4863-ada6-5ac293f6aac9

For Digitoxin:

ARAX is returning an edge of "INHIBITOR": 

<img width="1621" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/10744350/9774fd9f-fd08-416e-bd99-5ab703924389">

**Comment by edeutsch** [comment] 2023-07-20 02:34
yes, but if you look at the `sources`, it seems to come from MolePro:

![image](https://github.com/NCATSTranslator/Feedback/assets/12707718/3c733842-9fd2-4809-b674-860668a78c5d)

ARAX does not validate the responses from KPs, so if they KPs report an incorrect result, ARAX will return it..

**Comment by saramsey** [comment] 2023-08-01 19:42
Confirmed, this seems to be a bug in the RTX-KG2pre build system. Logging an issue in the RTXteam/RTX-KG2 project area now, marking it high priority.

**Comment by saramsey** [comment] 2024-01-24 19:00
This bugfix should get rolled out in the RTX-KG2.9.0 build (slated for late winter).

**Comment by sierra-moxon** [comment] 2024-05-17 01:08
closing as completed!

**Closed by sierra-moxon** 2024-05-17 01:08 UTC
Labels: opposite of what I asked for
