### ISSUE TITLE
I can't find "Addisons Disease Secondary To Adrenal Destruction" nor "Addisons Disease Secondary To Idiopathic Atrophy" in MONDO (neither as terms or synonyms).  Also, selecting either of these returns no results in the UI.  Wondering where these come from? 

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#19] opened 2022-10-17 22:54 UTC
## Steps to reproduce:
Search for "Addisons Disease" - autocomplete returns "Addisons Disease Secondary To Adrenal Destruction" and "Addisons Disease Secondary To Idiopathic Atrophy" as matches.

**Comment by sierra-moxon** [comment] 2022-10-17 22:55
<img width="1502" alt="Screen Shot 2022-10-17 at 3 54 46 PM" src="https://user-images.githubusercontent.com/4561292/196298
<img width="1514" alt="Screen Shot 2022-10-17 at 3 54 25 PM" src="https://user-images.githubusercontent.com/4561292/196298633-786fe44a-7e8d-438f-ae5e-a6b8cdf7cdd2.png">
628-e8a7271e-5e79-45d3-8ee9-f35313a6e3f0.png">

**Comment by sierra-moxon** [comment] 2022-11-18 06:17
closing as duplicate of #10.

**Closed by sierra-moxon** 2022-11-18 06:17 UTC
Labels: invalid
