### ISSUE TITLE
EPC Link to Clinical Trials - Broken link: trailing "}". 

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#497] opened 2023-08-30 20:33 UTC
## Steps to reproduce:
Select the Addison's disease suggested query, go to Flutamide, click on "treats" edge, check clinical trials link.

## Screenshots:
![screenshot](https://raw.githubusercontent.com/TranslatorSRI/IssueScreenshots/main/screenshot_20230830203326825385.jpeg)

**Comment by dkoslicki** [comment] 2023-08-30 20:33
I don't know if this is an ARA issue or a UI issue, but it might be good to have a link checker somewhere. And/or track down which part of the system is returning this broken link

**Comment by dkoslicki** [comment] 2023-08-30 20:34
Looks to be RTX-KG2 by way of ARAX. Opening issue there

**Comment by dkoslicki** [comment] 2023-08-30 20:36
Tracking at https://github.com/RTXteam/RTX-KG2/issues/346 and will follow up if this is a UI or RTX-KG2 issue

**Comment by dkoslicki** [comment] 2023-09-06 18:16
Ok, after investigation, it is actually _not_ from RTX-KG2. This might be a decorating from some other service (clinical info perhaps?).

**Comment by mbrush** [comment] 2023-09-09 18:13
I ran into this issue as well - seems like something that we want to address before the release / Tyler's presentation.  And something that may have an easy fix if we can find the cause.  Who should we tag here to figure this out?  Thoughts @Genomewide?

**Comment by dkoslicki** [comment] 2023-09-09 18:34
It might be the annotation service. Tagging @colleenXu @NCATSTranslator/exploring-agent @andrewsu

**Comment by newgene** [comment] 2023-09-11 16:58
Double checked the annotation fields for `flutamide` from MyChem.info:

https://mychem.info/v1/chem/MKXKFYHWDHIYRV-UHFFFAOYSA-N?fields=chembl.pref_name,chembl.drug_indications

It does return `NCT00001521`, but no `}` found in the response.

@Genomewide @gaurav maybe a bit more info about the source of this URL from the UI side will help to identify the root cause?

**Comment by Genomewide** [comment] 2023-09-11 22:30
This should not be an annotation server problem. It should be an edge attribute that is 'publications'

Also this answer does not come back on prod. 

![image](https://github.com/NCATSTranslator/Feedback/assets/55069176/0fa3b59e-be1c-4c76-8f38-bfd982b045cc)


But we do need to track it down.  I am guessing it is a format error from an edge attribute, but will try to hunt it down to confirm.

**Comment by Genomewide** [comment] 2023-09-11 22:43
@dkoslicki I don't see a curly bracket in the edge. So, I think it is us.  I will track it further. Here is the edge from the json
```json
                        "infores:molepro:PUBCHEM.COMPOUND:3397--biolink:treats--None--None--None--MONDO:0018479--infores:chembl": {
                            "object": "MONDO:0018479",
                            "sources": [
                                {
                                    "resource_id": "infores:chembl",
                                    "resource_role": "primary_knowledge_source",
                                    "source_record_urls": null,
                                    "upstream_resource_ids": null
                                },
                                {
                                    "resource_id": "infores:arax",
                                    "resource_role": "aggregator_knowledge_source",
                                    "source_record_urls": null,
                                    "upstream_resource_ids": [
                                        "infores:molepro"
                                    ]
                                },
                                {
                                    "resource_id": "infores:molepro",
                                    "resource_role": "aggregator_knowledge_source",
                                    "source_record_urls": null,
                                    "upstream_resource_ids": [
                                        "infores:chembl"
                                    ]
                                }
                            ],
                            "subject": "PUBCHEM.COMPOUND:3397",
                            "predicate": "biolink:treats",
                            "attributes": [
                                {
                                    "value": "knowledge_assertion",
                                    "value_url": null,
                                    "attributes": null,
                                    "description": null,
                                    "value_type_id": "string",
                                    "attribute_source": "infores:molepro",
                                    "attribute_type_id": "biolink:knowledge_level",
                                    "original_attribute_name": "biolink:knowledge_level"
                                },
                                {
                                    "value": "FDA Clinical Research Phase 2",
                                    "value_url": null,
                                    "attributes": [],
                                    "description": null,
                                    "value_type_id": "biolink:FDA_approval_status_enum",
                                    "attribute_source": "infores:chembl",
                                    "attribute_type_id": "biolink:FDA_approval_status",
                                    "original_attribute_name": "max phase for indication"
                                },
                                {
                                    "value": [
                                        "clinicaltrials:NCT00001521"
                                    ],
                                    "value_url": null,
                                    "attributes": null,
                                    "description": null,
                                    "value_type_id": "linkml:Uriorcurie",
                                    "attribute_source": null,
                                    "attribute_type_id": "biolink:publications",
                                    "original_attribute_name": null
                                },
                                {
                                    "value": "manual_agent",
                                    "value_url": null,
                                    "attributes": null,
                                    "description": null,
                                    "value_type_id": "string",
                                    "attribute_source": "infores:molepro",
                                    "attribute_type_id": "biolink:agent_type",
                                    "original_attribute_name": "biolink:agent_type"
                                }
                            ],
                            "qualifiers": []
                        },
```

**Comment by Genomewide** [comment] 2023-09-11 22:45
@dnsmith124 @gprice1129 The edge data is above in my post.  The display of the link has a curly bracket that does not appear in the data.  Can you see what is up?

**Comment by sstemann** [comment] 2023-09-12 10:55
another example is in #530

**Comment by dnsmith124** [comment] 2023-09-12 14:50
Looking into this and [#530](https://github.com/NCATSTranslator/Feedback/issues/530) now

**Comment by dnsmith124** [comment] 2023-09-12 15:15
The errant curly brace was being added by the UI by mistake, I've addressed the issue and deployed a fix that is live on CI: https://ui.ci.transltr.io/demo/results?l=Addison%20Disease&i=MONDO:0009410&t=0&q=71c30524-934b-41e7-b4ef-8f26da0ae73c 

Same process as the original ticket, search for **Flutamide**, then check the evidence window for that result.

**Comment by dnsmith124** [comment] 2023-09-13 16:58
confirmed resolved in CI, closing.

**Closed by dnsmith124** 2023-09-13 16:58 UTC
Labels: UI - display
