### ISSUE TITLE
add 'Mendelian Disease' and 'Pharmaceutical preparations' to too-generic block list

### ISSUE THREAD

**Issue by gglusman** [NCATSTranslator/Feedback#471] opened 2023-08-11 16:39 UTC
Vascular Ehlers-Danlos syndrome (8/10 reevaluation [CI after duplicate fix](https://ui.ci.transltr.io/results?l=Ehlers-danlos%20Syndrome,%20Vascular%20Type&i=MONDO:0017314&t=0&q=afeed50c-c68c-4c81-bd51-a2e9d094f0bd))

[Elx-02](http://identifiers.org/chembl.compound/CHEMBL4297744) and [Busulfan](http://identifiers.org/pubchem.compound/2478) are results that 'treat [Mendelian Disease](http://purl.obolibrary.org/obo/MONDO_0003847)'.
These results will likely go away, but it probably is worth adding 'Mendelian Disease' to a block list since it's too generic.

**Comment by sandrine-m** [comment] 2023-08-11 18:33
<img width="749" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/66342541/fcf36a19-0b16-4b58-8720-4d01cd32a393">
Assigning this to the people I know have been working on this but feel free to unassign/change Milestone :)

Thank you!

**Comment by dnsmith124** [comment] 2023-08-11 18:39
@sandrine-m @Genomewide I don't think the UI team is in charge of any sort of blocklist

**Comment by sandrine-m** [comment] 2023-08-11 18:43
@sierra-moxon would you help triage this issue? I think I got all mixed up

**Comment by gaurav** [comment] 2023-08-13 05:08
The only blocklist currently functional in Translator is used by NameRes to filter embarrassing or controversial terms out of the autocomplete (which is at https://github.com/NCATSTranslator/Blocklists). I don't believe any other blocklist has been implemented anywhere.

**Comment by Genomewide** [comment] 2023-08-13 05:11
I think there may be part of the block list plan that lives with @MarkDWilliams ? I could be very off on this though?

**Comment by gglusman** [comment] 2023-08-14 01:38
"**Pharmaceutical preparations**" http://linkedlifedata.com/resource/umls/id/C0013227 should also be blocked as too generic.

**Comment by sandrine-muller-research** [comment] 2023-10-05 20:09
Retested today, I was not able to reproduce on any environments : [PROD](https://ui.transltr.io/main/results?l=Ehlers-danlos%20Syndrome,%20Vascular%20Type&i=MONDO:0017314&t=0&q=5f7d6bd9-f291-42fa-9ce1-7f56bff6a939), [TEST](https://ui.test.transltr.io/main/results?l=Ehlers-danlos%20Syndrome,%20Vascular%20Type&i=MONDO:0017314&t=0&q=744336f0-b3ac-4280-9bcf-9b04b952191d), [CI](https://ui.ci.transltr.io/main/results?l=Ehlers-danlos%20Syndrome,%20Vascular%20Type&i=MONDO:0017314&t=0&q=6f0daa78-71cf-4578-8244-cb2e98869605)

**Closed** 2023-10-05 20:10 UTC
Labels: category too generic
