### ISSUE TITLE
There seems to be an error with the brief description of known paths that appear under the drug name. For example, in the Breast Cancer disease -> drug search, Trastuzumab, the most widely used treatment for HER2+ breast cancers, is described as having "2 Paths that may treat Male Breast Carcinoma". It's odd that it would suggest the drug has such a limited role. A more extreme example with breast cancer is Letrozole, a treatment for ER+ breast cancers, described as having "3 Paths that may treat Her2 Positive Breast Carcinoma" as a separate molecular subtype. 

-Aaron Bernstein, NCATS

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#665] opened 2023-12-21 19:59 UTC
## Steps to reproduce:
See comments.

**Comment by sstemann** [comment] 2024-01-02 20:50
I think there are a couple of issues working here, Aaron is working off of the cached breast cancer result:
https://ui.transltr.io/demo/results?l=Breast%20Cancer&i=MONDO:0007254&t=0&q=41a15961-3703-4c70-a008-c55f0fa5d6c9

1. it seems as though the number of paths is being equated to evidence here.  while there are two paths, in one path there are 860 publications, unfortunately though, in the path evidence modal the only knowledge source is Semmed.  @desiyopp 

2.  Trastuzumab appears twice in the results if you Text Filter with the drug name.  So it's not being merged as much as it should @gaurav @MarkDWilliams 

- The highest score Trastuzumab is coming from [UNIIP188ANX8CK](https://gsrs.ncats.nih.gov/ginas/app/beta/substances/P188ANX8CK) and the CI Node Norm does not list the [UNIIP188ANX8CKresponse_1704227989677.json](https://github.com/NCATSTranslator/Feedback/files/13813781/UNIIP188ANX8CKresponse_1704227989677.json) CHEMBL1201585 as a synonym
- The full record in public GSRS lists the UNII and CHEMBL on one record in the Codes - Identifiers section:
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/8159203c-9828-4a2d-9a68-419c2a18dba2)

-  the second Trastuzumab response is  [CHEMBL.COMPOUND:CHEMBL1201585 ](https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL1201585/) which has no synonyms listed in  Node Norm [CHEMBL.COMPOUNDCHEMBL1201585response_1704227949270.json](https://github.com/NCATSTranslator/Feedback/files/13813782/CHEMBL.COMPOUNDCHEMBL1201585response_1704227949270.json)

3.  Even with the addition of the second Trastuzumab result - Improve's answer seems to not be displayed.  They respond with a direct path and lists Chembl at a primary KS, but this info isn't making it to the UI. @dnsmith124 
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/780a0788-37a7-44a9-a0fa-f5b179c63264)

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/5f88e949-6f1b-43fa-b4ce-65de25215fd3)

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/43852162-9d05-4c0c-b59a-b55521c55aac)

**Comment by dnsmith124** [comment] 2024-01-02 21:47
@sstemann no. 3 in your list appears to be a bug that I resolved today as part of #669, so that portion of this should be resolved.

**Comment by gaurav** [comment] 2024-01-19 06:56
I've confirmed that the Trastuzumab clique is being split -- even better, it _shouldn't_ be split, since DrugCentral:4979 should connect those two identifiers. So this is clearly a bug in Babel's ChemicalEntity handling code! I've filed this issue at https://github.com/TranslatorSRI/Babel/issues/223

**Comment by gaurav** [comment] 2024-01-19 17:46
1. There may be multiple issues:
    - Answer quality: We don't have a result for Trastuzumab --[ treats ]--> Her2 Positive Breast Carcinoma, but we _do_ see that for Letrozole, but Trastuzumab is used much more often for Her2 positive breast carcinoma. --> Answer Quality group?
    - Answer quality: given how well Trastuzumab is studied, we should have one-hop and lots of mechanisms of action.
    - Summary description: why does it say "2 Paths that may treat Male Breast Carcinoma" 
instead of referring to breast cancer? (assign to @dnsmith124)
    - Publication count is off: we show 1740 but when you open the edge you only get 860 + 3 (#669 is closed, so this might be closed too -- **needs to be rechecked**)
3. Assigned to @gaurav, will aim to fix by next release.
4. Assigned to @dnsmith124, should be fixed already. **Needs to be rechecked**.

Also NodeNorm (@gaurav): breast cancer and breast carcinoma are different in MONDO? **To be investigated**.

**Comment by gaurav** [comment] 2024-01-19 17:46
No showstoppers.

**Comment by sstemann** [comment] 2024-08-07 22:49
who should be assigned here?  which part is Guppy and which part is Next Phase?

<img width="212" alt="image" src="https://github.com/user-attachments/assets/933ad28d-4703-4662-9399-02c098eb56de">

**Comment by dnsmith124** [comment] 2024-08-08 14:54
It appears that the pre-run queries have since been updated, and the original PK is now no longer returning results. The updated link is now: https://ui.transltr.io/demo/results?l=Breast%20Cancer&i=MONDO:0007254&t=0&r=0&q=56db1e8a-a849-4f4d-8528-f2ba079b3e53

**Comment by dnsmith124** [comment] 2024-08-08 14:58
The issue RE: improving's result not showing for Trastuzumab has been resolved, though the primary knowledge source on the 1 hop it returns is listed as Chembl (which is what improving provided). The path count is also correct. Removing myself from this ticket, as the UI issues have been addressed.

**Comment by gaurav** [comment] 2024-08-30 16:16
I've manually combined UNII:P188ANX8CK and CHEMBL.COMPOUND:CHEMBL1201585 [in the current NodeNorm CI](https://nodenormalization-sri.renci.org/1.5/get_normalized_nodes?curie=DrugCentral%3A4979&curie=CHEMBL.COMPOUND%3ACHEMBL1201585&conflate=true&drug_chemical_conflate=true&description=false&individual_types=false) with DrugChemical conflation turned on, but I'm still trying to figure out why we didn't connect this automatically at https://github.com/TranslatorSRI/Babel/issues/131.

I think this closes the NodeNorm part of this issue, so I'll remove myself as an assignee and tag it as needs to review.

**Comment by sierra-moxon** [comment] 2024-08-30 16:29
closing as completed - retested on TAQA and see the drug Trastuzumab

**Closed** 2024-08-30 16:48 UTC
Labels: needs review, Guppy (Sprint 5) - due Aug 23 in CI

**Comment by sstemann** [comment] 2024-08-30 17:42
this is in Prod with Fugu

https://ui.transltr.io/results?l=Breast%20Cancer&i=MONDO:0007254&t=0&r=0&q=5b4ce30a-b1ae-4c82-9e33-9e1881ae3d75

![image](https://github.com/user-attachments/assets/3ba2eaa2-95ac-4ff2-acba-89c34caec0b4)
