### ISSUE TITLE
Edge Labels Missing in the UI

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#667] opened 2023-12-28 20:17 UTC
Steps to reproduce:

1. Test UI > Drugs/Diseases > Paget Disease
- https://ui.test.transltr.io/main/results?l=Paget%20Disease&i=MONDO:0021165&t=0&r=1b076d0c&q=0951bf57-d8b0-462d-91fa-916ae0da3160
- https://arax.ncats.io/?r=0951bf57-d8b0-462d-91fa-916ae0da3160

2. Search for any of the following results:
- Lidocaine
- Imiquimod
- Cabergoline

3. Notice the edges with no labels
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/0cdf970b-223b-481c-8310-b4ce25781246)

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/8b9384ed-190c-4688-b52f-559c19f1b7b2)

4. It looks like its coming from BTE but I can't really tell, the UI EPC says Mondo and the subclass_of edge in the ARAX GUI says mondo but it has an edge label so I dont know

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/ef4b735d-3eb9-4316-88bc-3cae5a3820a2)

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/bf695016-628d-4e7b-a70d-d676b65401dd)

I'm not sure if this is a UI issue or a BTE issue.  So tagging both teams.

**Comment by gprice1129** [comment] 2023-12-29 00:20
In the biolink model the predicate `subclass of` has no inverse. Looking a little closer I found that the inverse of `superclass of` is `subclass of`. This might be a mistake in the biolink model but we are waiting for verification. @sierra-moxon @sstemann

**Comment by sierra-moxon** [comment] 2024-01-02 20:11
It's not technically a mistake, we only document the inverse on the non-canonical predicate.  

It would be interesting to see how you are parsing the model directly - usually we encourage folks to wrap that with the biolink-model-toolkit to get access to helper methods that abstract this kind of annotation practice from the user. 
e.g. `toolkit.get_inverse('subclass of')` will return `superclass of` and `toolkit.get_inverse('superclass of')` will return `subclass of` despite the disparity in annotation.

**Comment by gprice1129** [comment] 2024-02-01 21:52
@sierra-moxon @sstemann @dnsmith124 this is likely a bug in how we ingest the biolink model but I haven't been able to get a chance to look at it yet. My intuition is that this will be high on priorities for me for the next cycle.

**Comment by sstemann** [comment] 2024-02-16 16:44
@gprice1129 @dnsmith124 this looks better in test.  if its resolved, can you please close this ticket?
https://ui.test.transltr.io/main/results?l=Paget%20Disease&i=MONDO:0021165&t=0&r=0&q=b8869c38-3c0d-4366-b6e5-b4a60abc9bf6

https://arax.ncats.io/beta/?r=b8869c38-3c0d-4366-b6e5-b4a60abc9bf6
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/1f46c64d-587c-48bd-b4f9-cf682b28b206)

**Comment by gprice1129** [comment] 2024-02-16 18:28
We will be trying to find the root cause of this issue this cycle.

**Comment by gprice1129** [comment] 2024-02-23 23:56
I cannot figure out how this happened. Even looking at the raw JSON from the exact PK it is unclear how this could have happened. Given that this is not showing up anymore I don't think this is a valuable use of time and am going to close the issue.

**Closed by gprice1129** 2024-02-23 23:56 UTC
Labels: lobster1
