### ISSUE TITLE
unnamed disease when searching for myalgia

### ISSUE THREAD

**Issue by gglusman** [NCATSTranslator/Feedback#458] opened 2023-08-04 18:16 UTC
Searching for 'myalgia' in ci:

<img width="583" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/3977332/02b5163c-ab51-4ca5-8eb6-69808cc7e6e2">

Clicking on the MONDO link https://monarchinitiative.org/disease/MONDO:0850415 yields:
<img width="472" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/3977332/cabaa13a-81b4-4522-9449-8383c07ee0ce">

**Comment by sierra-moxon** [comment] 2023-08-08 23:18
closing as duplicate of  https://github.com/NCATSTranslator/Feedback/issues/411

**Closed by sierra-moxon** 2023-08-08 23:18 UTC
