### ISSUE TITLE
IDs not merged correctly leading to duplicative results 

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#767] opened 2024-04-22 20:09 UTC
## Steps to reproduce:
What genes may be downregulated by:Bivalirudin?
search for MPO

**Comment by sandrine-muller-research** [comment] 2024-04-22 20:20
IDs not conflated:
NCBIGene:4353 | MPO
PR:000010543 | MYELOPEROXIDASE
CHEMBL.TARGET:CHEMBL2439 | MPO PROTEIN, HUMAN

![image](https://github.com/NCATSTranslator/Feedback/assets/22616936/01e98911-7168-4391-b7ac-6cb59a7f9b3c)

**Comment by sierra-moxon** [comment] 2024-05-16 22:41
Is this a node-norm issue @gaurav ?

**Comment by sstemann** [comment] 2024-07-05 14:20
@sandrine-muller-research i re-ran this in Test and am not seeing this issue, can you confirm and close if applicable?

https://ui.test.transltr.io/main/results?l=Bivalirudin&i=CHEBI:59173&t=4&r=0&q=0e10870d-261b-4a35-af01-4df4815038f9

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/6460faec-b1c2-4c2c-804d-a71668945115)

**Comment by sierra-moxon** [comment] 2024-07-11 21:07
I can't reproduce this issue on TEST today either, closing as complete - of course, reopen if necessary :)

**Closed by sierra-moxon** 2024-07-11 21:07 UTC
Labels: SRI Tooling
