### ISSUE TITLE
Fragile X syndrome -- correlated with -- Autism missing provenance

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#177] opened 2023-05-09 18:46 UTC
## Steps to reproduce:
query: What drugs may treat Autism
result: Primaquine phosphate

**Comment by sandrine-m** [comment] 2023-05-09 18:49
<img width="1077" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/66342541/85364a58-e91f-46b4-bf78-dec71d5493d4">


It is not clear what the correlation is about (I would have expected associated with). The evidence link points to ARAX UI but the screen in blank.

**Comment by jaredroach** [comment] 2023-05-12 16:43
I cannot reproduce this. When I choose "What drugs may treat autism", I only get 10 results, and none of them are Primaquine phosphate.
<img width="1241" alt="Screenshot 2023-05-12 at 9 41 15 AM" src="https://github.com/NCATSTranslator/Feedback/assets/7597293/7b541ab7-409e-4bad-89e0-d78a1c9c9887">

**Comment by sierra-moxon** [comment] 2023-05-12 18:29
Note: @Genomewide - should the link to "Load New Results" be more prominent?

**Comment by jaredroach** [comment] 2023-05-12 21:05
@sierra-moxon Are you suggesting that I needed to hit the "load new results" button to reproduce the original bug? As it stands, I cannot even get back to the first page of results, because the interface is either hanging or talking an incredibly long time to return results. There has been a spinning purple "Calculating..." arrow for about half an hour.

**Comment by sandrine-m** [comment] 2023-05-12 21:14
@jaredroach I agree with you, I made the query again and could not find this compound anymore. However the same triple is present in the first result "Aripiprazole": 
<img width="1012" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/66342541/4bbd5b14-426f-450d-8d20-3ca6d689395e">

**Comment by jaredroach** [comment] 2023-05-12 21:52
@sandrine-m I still cannot replicate. My search for "What drugs treat autism" now returns 500 rather than 10 queries, but none of them are Aripiprazole. I tried expanding the results for dozens of the hits I got, but none involved Fragile X. Is there any way you could provide the direct link to the problematic "correlated with" link?

Aside: Having an incredibly slow interface that returns a vastly different set of results to different users and even the same user on the same day makes it very hard to beta test and troubleshoot. I wonder if there is a way to save a frozen instantiation of the results of a query, so that they may shared with others and also provide a chain of provenance.

**Comment by sandrine-m** [comment] 2023-05-12 22:10
@jaredroach having 2 different result sets for the same query on the same day for 2 different users is kind of worrying me... @Genomewide do you have any clue why this? 
@jaredroach can you confirm you're using [https://ui.test.transltr.io/](https://ui.test.transltr.io/)?
How did you try to reproduce? 
At the top of this issue in the URL shared I used the query id : 920ada2c-6a4c-4562-b697-06e481adfb0b and posted it through ARAX UI and could reproduce Aripiprazole result (in ARAX):
<img width="1115" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/66342541/5154afae-c94f-43ba-8f5b-0afd05d8674f">
The infores states that it is inferred from ARAXInfer using RTX-KG2c:
<img width="543" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/66342541/f2836b6a-0732-47c7-9b36-e0b862f1dda1">

**Comment by jaredroach** [comment] 2023-05-12 22:20
Am I right in rephrasing the OP as wanting to know what “This edge is inferred by ARAXInfer based on RTX-KG2c.” means." I have called in a bigger billy goat to answer that OP question.

As for my tangents, I tried a number of ways to replicate. Yes I am using https://ui.test.transltr.io/
It is very constrained, so there are not a lot of options in replicating. I choose "What drug treats" from the dropdown menu, and then the topmost most generic form of Autism from the autocomplete field. And then go weed my garden for 40 minutes waiting for the response.

**Comment by sandrine-m** [comment] 2023-05-12 23:08
In the UI we do not have the edge description even, the source points to ARAX only. Having at least the description “This edge is inferred by ARAXInfer based on RTX-KG2c.” would have been helpful to me, not sure for a ouside-of-Translator user. As a user, I was just expecting to understand what are the variables that were correlated there...
Re: replication. I wish I had a garden too!! :D Same issue on my side both when launching the query or trying to load it through the URL. @Genomewide is the UI aware of this issue? 
You can use the PK by going [here](https://arax.ncats.io/) and pasting the key in the field under "import" like this:
<img width="1249" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/66342541/5ce42273-1b99-4bb6-864c-dfe8e642d7dc">
It will load the results, then click on a link under MESSAGE ID and then on the left panel in Results.

**Comment by sandrine-m** [comment] 2023-05-16 20:31
comment from Simon King from UI (I can't find Simon's GitHub handle): 
"what I think happens is when a new version of code is released to each environment, any link taken from the old version no longer works. I know a new version was released a week or so ago. I re-ran the Autism search and got these results https://ui.test.transltr.io/results?l=Autism&t=0&q=ada8e53e-797e-412a-b83a-114429d2c081. I'll talk to the developers about this issue.
ui.test.transltr.ioui.test.transltr.io
[NIH Translator](https://ui.test.transltr.io/results?l=Autism&t=0&q=ada8e53e-797e-412a-b83a-114429d2c081)
NCATS Biomedical Translator"

**Comment by sandrine-m** [comment] 2023-06-17 00:30
RETEST:
I can still replicate (PK = https://ui.transltr.io/results?l=Autism%20Spectrum%20Disorder&t=0&q=eea2d5cc-af99-469f-9fab-ba74108a8fe8)
<img width="1138" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/66342541/3ff81995-849b-4811-8d11-7659fb49b16e">

Monarch initiative website does not load. Is Monarch Initiative returning "correlated_with" type of edges? When I look on [Monarch Initiative website for Fragile X syndrome](https://monarchinitiative.org/disease/MONDO:0010383#phenotype), I cannot find Autism in the nearest neighbors. I do see autism under the following statement:
"Fragile X syndrome has phenotype Autism":
<img width="1247" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/66342541/5e4619b8-68d2-4afc-b2e7-76510b43e4a4">

@sierra-moxon @mbrush could you help figuring out this issue?

**Comment by sierra-moxon** [comment] 2023-07-03 16:47
it looks like the retest happened on ui.transltr.io (PROD) which likely hasn't been updated in quite some time; however, I can replicate the Aripiprazole edge that includes 

![Image](https://github.com/NCATSTranslator/Feedback/assets/4561292/49713786-d4c7-49c2-8ca7-36af387011ca)

BUT, this edge now reports that the source is MONDO.

**Comment by sierra-moxon** [comment] 2023-07-03 16:48
@kevinschaper - can you confirm this is coming from phenio?

**Comment by sandrine-muller-research** [comment] 2023-10-06 20:24
Cannot reproduce closing.

**Closed by sandrine-muller-research** 2023-10-06 20:24 UTC
