### ISSUE TITLE
need better chemical name

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#921] opened 2024-08-13 22:36 UTC
## Steps to reproduce:
search for Drugbank:db14131

**Comment by sandrine-muller-research** [comment] 2024-08-13 22:45
<img width="970" alt="image" src="https://github.com/user-attachments/assets/cd031431-106b-437d-9bae-bb574991bce7">
this drugbank ID corresponds to [Basic Fibroblast Growth Factor](https://arax.ncats.io/?term=Basic%20Fibroblast%20Growth%20Factor) which does not appear in the clique together with the UMLS and the ChEMBL ID
It also appears to be a peptide. 
<img width="1113" alt="image" src="https://github.com/user-attachments/assets/96bb9bb3-4bc5-4086-a75d-96d2bdf45cd3">

The BiolinkModel category for this clique is `biolink:Protein` while for the one in the DrugBank ID it is a `biolink:SmallMolecule` (result from BTE).  I suspect they do not arrive in the same clique because of that. Would you confirm @gaurav ?

**Comment by sstemann** [comment] 2024-08-14 14:36
duplicate of #899 scheduled for Guppy

**Closed by sstemann** 2024-08-14 14:36 UTC
