### ISSUE TITLE
CACNA1C causes Autism spectrum Disorder

### ISSUE THREAD

**Issue by sandrine-m** [NCATSTranslator/Feedback#22] opened 2022-10-18 22:38 UTC
I made a query using ARAX UI to look for diseases or phenotypes related to CACNA1C. A result returned do not make sense to me scientifically. 
query ID : 9c88186c-bf34-40a0-bc32-6afc3a832198
Query:
```{
  "edges": {
    "e00": {
      "object": "n01",
      "predicates": [
        "biolink:related_to"
      ],
      "subject": "n00"
    }
  },
  "nodes": {
    "n00": {
      "categories": [
        "biolink:Gene"
      ],
      "ids": [
        "ENSEMBL:ENSG00000151067"
      ]
    },
    "n01": {
      "categories": [
        "biolink:DiseaseOrPhenotypicFeature"
      ]
    }
  }
}
```
From the BTE results, I see: 
NCBIGene:775----biolink:causes----MONDO:0005258 Id: 8aebf1938160e0b5871cabc772ca63ad
CACNA1C causes Autism spectrum Disorder
infores:semmeddb
Only 1 publication is referred as source: [PMID:33829152](https://pubmed.ncbi.nlm.nih.gov/33829152/)
The abstracts states: "Variants of the CACNA1C voltage-gated calcium channel gene have been associated with autism and other neurodevelopmental disorders including bipolar disorder, schizophrenia, and ADHD. The Timothy syndrome mutation is a *rare de novo gain-of-function variant in CACNA1C that causes autism with high penetrance*, providing a powerful avenue into investigating the role of CACNA1C variants in neurodevelopmental disorders. ... These results suggest that the Timothy syndrome mutation can disrupt multiple steps of axon development. Further work exploring the molecular mechanisms that underlie these perturbations in neuronal polarity and axon termination will give us better understanding of how variants in CACNA1C contribute to the axonal defects that underlie autism."
I do not think that the paper proves a causality between CACNA1C and ASD. Also, I would have expected "variant in CACNA1C causes autism" but I think the qualifier system will solve this.

Thank you for the help!

**Comment by sandrine-m** [comment] 2022-10-18 22:48
Same issue with CACNA1C causing schizophrenia. 
NCBIGene:775----biolink:causes----MONDO:0005090
Id: 6af32011b8f117138f5ede752e07259a
attribute_type_id:	biolink:aggregator_knowledge_source
value_type_id:	biolink:InformationResource
value:	infores:biothings-explorer
attribute_type_id:	biolink:primary_knowledge_source
value_type_id:	biolink:InformationResource
value:	infores:semmeddb
attribute_type_id:	biolink:aggregator_knowledge_source
value_type_id:	biolink:InformationResource
value:	infores:biothings-semmeddb
attribute_type_id:	biolink:publications
value:	PMID:28593527
PMID:33938268
attribute_type_id:	biolink:original_object
value:	C0036341
attribute_type_id:	biolink:original_predicate
value:	CAUSES
attribute_type_id:	biolink:original_subject
value:	C1413057
attribute_type_id:	original_object_name
value:	Schizophrenia
attribute_type_id:	original_subject_name
value:	CACNA1C gene

[PMID:28593527](https://pubmed.ncbi.nlm.nih.gov/28593527/):
At the end of the abstract, clearly states:
"Our study demonstrated that CACNA1C gene polymorphisms and CACNA1C protein expression were *associated* with schizophrenia and its clinical phenotypes."

[PMID:33938268](https://pubmed.ncbi.nlm.nih.gov/33938268/):
Their conclusion:
"Conclusion: We identified an independent, replicable, functional, and significant risk variant block at CACNA1C for schizophrenia, which could be tagged by the most robust risk marker rs1006737, *suggesting an important role of CACNA1C in the pathogenesis of schizophrenia*."

**Comment by sandrine-m** [comment] 2022-10-18 22:53
I wanted to check the knowledge sources of Gene -- causes -- Disease or Phenotype but somewhat does not lead to any results:
```
{
  "edges": {
    "e00": {
      "object": "n01",
      "predicates": [
        "biolink:causes"
      ],
      "subject": "n00"
    }
  },
  "nodes": {
    "n00": {
      "categories": [
        "biolink:Gene"
      ]
    },
    "n01": {
      "categories": [
        "biolink:DiseaseOrPhenotypicFeature"
      ]
    }
  }
}
```

**Comment by sandrine-m** [comment] 2022-10-27 15:06
This issue is related to issue #34 and it seems that predicates for semmeddb are maybe not the best choices

**Comment by capasfield** [comment] 2023-01-13 17:46
Qualifier issue.

**Comment by sierra-moxon** [comment] 2023-03-30 17:01
From SEMMEDDB hackathon session 03/30/2023:
the causes edges are good edges, but they have too strong of predicates, we need these to change to "associated with" edges. 
we don't want the PubMed counts filters to remove these edges.

**Comment by andrewsu** [comment] 2023-07-11 23:53
For pretty much the same reasons I describe in https://github.com/NCATSTranslator/Feedback/issues/9#issuecomment-1631652202, I think we should close this issue (but will leave it to someone else to second my proposal and actually close it)...

**Comment by sandrine-m** [comment] 2023-07-12 00:04
Closing! Thank you @andrewsu

**Closed** 2023-07-12 00:04 UTC
Labels: data error, KP - liberate usage of predicate, text mined, EPIC: SEMMEDDB/text mining
