### ISSUE TITLE
What drugs treats cerebral palsy:  "water" is returned in the first 10 results.  

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#21] opened 2022-10-18 21:35 UTC
## Steps to reproduce:
query for " what drugs may treat Cerebral Palsy."  "water" is in the first 10 results.  

## Screenshots:
![screenshot](https://raw.githubusercontent.com/TranslatorSRI/IssueScreenshots/main/screenshot_20221018213518349564.jpeg)

**Comment by sierra-moxon** [comment] 2022-10-18 21:38
looking into the publications that support "water" as a treatment for cerebral palsy, the publications talk about hydrotherapy (not water as a drug).  

Would expect to see these in the top couple of pages of results so that I could explore the non-familiar drug/therapy results with more confidence:
baclofen (and similar compounds)
phenobarbital (and similar compounds)
physical/speech/occupational therapy (water _therapy_ here makes sense)

**Comment by sierra-moxon** [comment] 2022-10-18 21:50
The second issue I see here is that we have a couple of genes independently being reported as the "causes" of Cerebral Palsy.  In the paper associated with statement "GAD1 causes Cerebral Palsy", the finding was "Our positive findings of haplotype GG suggested that variation of GAD1 gene was an important risk factor for mixed CP." https://pubmed.ncbi.nlm.nih.gov/24228494/

**Comment by sierra-moxon** [comment] 2022-10-18 23:24
Also, the relationship between "Worster-drought Syndrome (Disease)" and "Cerebral Palsy" is currently `subclass_of` -- MONDO types this relationship as `disease has feature`, which has a mapping to "biolink:associated_with"  (I can also see a case to be made for mapping this to "biolink:has_phenotype" @colleenXu - what do you think?

**Comment by sierra-moxon** [comment] 2023-01-20 17:38
- there may be some bad edges here to follow up on "water treats Epilepsy"? - text mined and SEMMEDB
- can the UI cache some records so that we wait until 100 results come back?
- create a set of manually curated edges as a way to improve confidence in some answers?
- BTE ranks this 89 out of 1000 - but will look into why this is happening. 
  - Chris B will run this through Aragorn to check how Aragorn ranks it.
  - could be that Aragorn doesn't return this because algorithms are different.
  - are there a set of negative benchmarks that we can make? 
- Does this mean all text-mined results should be downranked - no, we can't assume this.   
  - hope is that we can phase out SEMMEDB altogether and use text-mining-provider?  as they are doing curation here.
  - if there is a result that has SEMMEDB and text-mining-provider results, we could downrank SEMMEDB?

**Comment by sierra-moxon** [comment] 2023-01-20 17:48
revisit once ARS ranking is in place.
have a SEMMEDB or text-mining label as well.

**Comment by sierra-moxon** [comment] 2023-01-20 17:53
Worster-drought Syndrome (Disease) to Cerebral Palsy is being handled in the mydisease.info KP via @andrewsu

**Comment by andrewsu** [comment] 2023-01-20 18:25
> Worster-drought Syndrome (Disease) to Cerebral Palsy is being handled in the mydisease.info KP via @andrewsu

Note that this bug will be fixed in https://github.com/biothings/mydisease.info/issues/44

**Comment by andrewsu** [comment] 2023-01-27 16:46
After addressing https://github.com/biothings/mydisease.info/issues/44, mydisease.info is no longer incorrectly reporting that `Worster-drought Syndrome` is a subclass of `Cerebral Palsy`.  (Of course, this is just one of the many sub-issues raised above that are intertwined in this issue...)

**Comment by sierra-moxon** [comment] 2023-03-30 16:58
From SEMMEDDB session 3/30/2023:
Andy:
CP water query was rerun bc pk in issue is dead now.
http://transltr-bma-ui-dev.ncats.io/results?l=Cerebral%20Palsy&t=0&q=00578b99-7174-4066-857b-b06ee58c0792
https://ui.ci.transltr.io/results?l=Cerebral%20Palsy&t=0&q=35d21b51-fb73-4bad-8379-7474fcc39bef
Water is there but still loading results

**Comment by gglusman** [comment] 2023-03-30 17:10
In flies, Gad1 is involved in thirst response (e.g., https://elifesciences.org/articles/66286).
Mutations in GAD1 are linked to relevant disease phenotypes (e.g., https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7241960/) and are tested for cerebral palsy (e.g., https://www.preventiongenetics.com/testInfo?val=Cerebral-Palsy-via-the-GAD1-Gene).
Perhaps there is a valid connection to be made there.

**Comment by sierra-moxon** [comment] 2023-03-31 16:19
From TAQA w/re to the SEMMEDDB hackathon summary given there:
We can clean up some of the SEMMEDDB results, but not all of them. hesitate to go down the rabbit hole of fixing an unmaintained resource. Two more things can be tried: Andrew has tickets (link to UMLS, look at scores provided by SEMMEDDB). From Bill B and Andrew S: in general, we agree that Text Mined data should be treated differently, with the goal of increasing user trust. Is this a plan for the UI?
From Andy:
if UI gets 3 PMIDs from 3 sources - one is DrugBank, 3 are SEMMEDDB - do we treat those differently? In discussion.
From Sui and Tyler:
papers are evidence, but not the only kind. - numbers of pubs aren't the only factor to provide evidence.
Andrew:
the key evidence here is SEMMEDDB has paper references and so does DrugBank. We don't have the knowledge level to disambiguate the difference between the confidence of these two sources.
If the evidence is only SEMMEDDB -- then maybe a visual queue - like a dotted line, would be helpful.

Please see notes from the TAQA meeting for more discussion here. There is nothing more specific to this issue, but the issue is a use case for the more broad discussion of how to show users SEMMEDDB is being used.

**Comment by sierra-moxon** [comment] 2023-05-01 23:17
I no longer see "water" as a treatment for cerebral palsy :)

**Closed by sierra-moxon** 2023-05-01 23:17 UTC
Labels: invalid, KP - liberate usage of predicate, text mined
