### ISSUE TITLE
autocomplete not returning for "PASC/Long COVID-19", "multiple sclerosis" returns results with evidence(0)

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#96] opened 2023-01-27 22:00 UTC
## Steps to reproduce:
1. Instead of clicking on the multiple sclerosis term on the landing page, try typing it in - although it returns results/pathways, all evidence are 0 without any links under. The link on the title page appears to be working fine (probably pre-generated search?).

2. PASC/Long COVID-19 generates an empty set of results. Enter any of the suggested "long covid" and "long covid-19".

**Comment by sierra-moxon** [comment] 2023-02-07 19:12
1: I believe this is can be closed as a duplicate of #46  (we need more evidence types than pubs potentially, evidence(0) is not intuitive to users getting back results).

2: It could be that this is a duplicate of #42 - feedback for our autocomplete task.  Noting here, that a search for "Long Covid" here: http://transltr-bma-ui-dev.ncats.io/ using the autocompleted term, has been spinning for 6 mins with no results returned.

**Comment by sstemann** [comment] 2023-03-09 17:50
Fixes for both #1 and #2 are in progress

**Comment by sierra-moxon** [comment] 2023-06-22 22:34
06/22/23 triage - re-tested on ui and test. 
autocomplete and term selection both work as expected, not too many results are returned in autocomplete.  Autocomplete seems good to me.

However, there are still no results, and I waited > 5 mins to see that there are no results.

**Comment by Genomewide** [comment] 2023-06-27 18:50
Rerunning this I get answers in a reasonable time and there is evidence. Closing bc this was likely due to something being down at the time or has been resolved for other reasons.

**Closed by Genomewide** 2023-06-27 18:50 UTC
Labels: UI - term selection, Friends and Family, EPC
