### ISSUE TITLE
Searching for 1 "disease", returns paths treating related "diseases" ranked higher

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#37] opened 2022-11-01 21:19 UTC

**Comment by sandrine-m** [comment] 2022-11-01 21:21
When I search for Fragile X syndrome, I find responses only on FRAXE syndrome which is related but not strictly the same. Some of those responses are ranked higher than reponses on Fragile X syndrome. Could we rank higher up the disease itself and suggest paths to related diseases afterwards in a secondary section perhaps?

**Comment by sandrine-m** [comment] 2022-11-01 21:58
There is an additional issue with this query (leading to _UI - data error_):the need for representation of variants/mutant form. When I look at the Decitabine path (ranked 7th), I see FMR1 causes Fragile X syndrome where in reality it is mutations (increased repeats or point mutations) in the FMR1 gene. We should either have the locations and changes of the possible mutations or at least "mutant form" + required mutation change in that gene to be accurate.

**Comment by sandrine-m** [comment] 2022-11-01 22:13
There is an additional issue with this query (leading to _UI - invalid_): are we expecting illicit drugs there? I know there are some clinical trials using illicit drugs for some therapeutic effects but I find it odd to have them there (maybe rank them lower?)
<img width="964" alt="image" src="https://user-images.githubusercontent.com/66342541/199350599-521d0647-6968-4f85-8a9d-6efd0bf1a0b8.png">

**Comment by sandrine-m** [comment] 2022-11-01 22:16
There is an additional issue with this query (leading to KP - liberate use of predicate): Fragile X syndrome is caused by FMR1 mutation. I could find association with RGS4 though (deletion on RGS4 recues some phenotypes of Fragile X syndrome). The predicate is wrongly chosen.

**Comment by cbizon** [comment] 2022-12-02 19:37
I am now seeing both Fragile X and FRAXE results come back:
![image](https://user-images.githubusercontent.com/10744350/205371129-5db891fb-7d93-455b-a2a1-90c04288aea5.png)

KP b3613a26-58a6-4a12-8fbf-eeff0494b3b4

I think that the FRAXE are coming from Unsecret, tagging @webyrd 

Note that FRAXE is not a subclass of Fragile X

**Comment by sierra-moxon** [comment] 2023-02-16 20:57
from TAQA:
Sarah: why is the subclass disease ranked higher than the disease, is the nuance here?

Sandrine: when trying to treat a subclass of a disease, there are distinct phenotypes between the parent and the subclass, and you are trying to treat the specific phenotype.  Related disease treatment is more helpful than "subclass" diseases. 

Casey: Is filtering out the subtype responses one of the faceted options in the UI? I think that's captured in the TRAPI response
Sarah: +1 Casey, Is filtering out the subtype responses one of the faceted options in the UI?
Tyler: FRAXE is called "Fragile X E syndrome" which is much different than "Fragile X" (a text match issue, really!)
Andy/Sandrine: have some sort of filter in the UI that says "only show me exact matches" - also want to immediately know why you showed me these answers.  

Sui: medical reality is a drug->disease relationship should always occur at the lowest possible level of the hierarchy, else it is just wrong.   But in writing, they know what they mean but say it at a higher level and our tools bring it out at a higher level.  (e.g.: you should not see subclass disease treatments?) 
Tyler: we've made some progress here, but going further down in the hierarchy is common.  +1 to a filter in the UI to show 1) why you got it and 2) option to have exact match only.
Matt: getting disease treatments from a sublcass where it's clearly not a subclass.   
Tyler: its also a corner case, the naming is just too close and this isn't a frequent occurrence.

**Comment by sierra-moxon** [comment] 2023-02-16 20:58
@webyrd  - can you help us understand why this is coming back (it is not a subclass)?

**Comment by webyrd** [comment] 2023-02-17 15:38
Hi @sierra-moxon !  Sorry for the slow reply.

We are currently changing our node normalization code, light-weight reasoning code, Biolink version, scoring, and the underlying KGs, all at once.  We plan to deploy this new version shortly after the Relay.  I suggest we revisit this, and other issues for the Unsecret ARA, after this big update, since the behavior of Unsecret is likely to change significantly.

**Comment by sharatisrani** [comment] 2023-07-13 22:47
Could not reproduce this today, has it been fixed, per @webyrd comment above?  Also Unsecret did not provide any answers in today's test.

**Comment by sandrine-m** [comment] 2023-07-14 16:42
RETEST on [TEST](https://ui.test.transltr.io/results?l=Fragile%20X%20Syndrome&i=MONDO:0010383&t=0&q=9b9f2dce-9a55-43c8-a20b-9c40eb9f19f9) 
FRAXE disappeared. closing issue. Thank you all

**Closed by sandrine-m** 2023-07-14 16:42 UTC
Labels: invalid, data error, O&O issue, KP - liberate usage of predicate
