### ISSUE TITLE
Path includes Animals as Node, seems fairly generic?

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#484] opened 2023-08-17 12:27 UTC
UI CI > MVP1 > Stickler Syndrome > Prednisolone - initially when Prednisolone is returned, before BTE returns this path is the only path

https://ui.ci.transltr.io/results?l=Stickler%20Syndrome&i=MONDO:0019354&t=0&q=7cc56b8c-17d2-43c9-a574-3e909952897f

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/f3be8d12-1ce0-4dbc-bf76-3e2236441a11)

https://arax.ci.transltr.io/?r=7cc56b8c-17d2-43c9-a574-3e909952897f > ARAGORN > Prednisolone

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/e7184f6b-dddc-4cb0-8fe1-798a10ea7a6e)

In the CI UI, in Entity search, put "animals" - looks pretty widespread - i'm fairly certain, when other ARAs show up in the UI Filter, it's because the result was merged with an ARAGORN result
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/de3892c5-944a-4d1d-9ee5-a27fabd4b348)

ARAX - their betamethasone graph does not have a animal node:
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/396f5b95-bb4e-4272-901f-237828fbb015)

BTE - their Captopril does not have animal
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/625c2229-640c-4890-adc7-2ce81864ac68)

Unsecret - Ergocalciferol does not have animal
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/d29869b8-ff9f-4b12-9b9d-278d98590172)

**Comment by sstemann** [comment] 2023-08-17 12:27
@sierra-moxon i'm not sure how to tag this one?

**Comment by sandrine-m** [comment] 2023-08-18 13:25
Hi @sstemann, I triaged the same as #468 . With @gglusman's help we created a "transitive" label to group issues that lead to suboptimal results due to transitive relationships which should be worked out. In the case you describe:
A. _Losartan_ `treats` _Stricker syndrome_
B. _Losartan_ `is part of `_Animal_
C. Prednisolone `is part of` _Animal_
However those statements are not sufficient evidence to say that prednisolone `treats` _Stickler syndrome_. Gwênlyn gives some nice and basic examples of this phenomenon in issue #468.

**Comment by cbizon** [comment] 2023-08-18 13:53
I haven't double checked this, but it looks to me as though KG2 is responding to Losartan-[part of]->(x:chemical) with x = Animal.  Which should not be a chemical.  But as I said, I have not directly queried KG2 yet to see if my guess is correct.

**Comment by saramsey** [comment] 2023-08-18 16:18
All, thanks for bringing this to my attention. I re-ran the original UI query https://ui.ci.transltr.io/results?l=Stickler%20Syndrome&i=MONDO:0019354&t=0&q=7cc56b8c-17d2-43c9-a574-3e909952897f

I've verified that (`MESH:D000818`) appears in a variety of result support graphs returned by the Translator UI for the query _What chemical entities treat Stickler Syndrome?_  

To look into this further, I'm using the following TRAPI query graph to look for nodes of category `ChemicalEntity` that are connected to `MESH:D00818` by a `has_part` relationship, in RTX-KG2.
```
{
   "edges": {
      "e00": {
         "subject":   "n00",
         "object":    "n01",
         "predicates": ["biolink:part_of"]
      }
   },
   "nodes": {
      "n00": {
         "categories":        ["biolink:ChemicalEntity"]
      },
      "n01": {
         "ids":  ["MESH:D000818"]
      }
   }
}
```
I can confirm, in the current production RTX-KG2 KG (`arax.ncats.io/kg2`), there are 329 edges in the current production RTX-KG2 of the form `[biolink:ChemicalEntity]-[biolink:part_of]->[MESH:D00818]`, many of which come from SemMedDB. Many of them are endogenous biomolecules, so not entirely ridiculous but probably not helpful either for the kinds of translational questions we are focusing on in Translator:

<img width="1155" alt="Screenshot 2023-08-18 at 9 08 15 AM" src="https://github.com/NCATSTranslator/Feedback/assets/5562107/40b2be37-9eb9-4e8a-815a-3281b11a7ab9">

However, in the RTX-KG2 KG that is currently running in ITRB TEST (`kg2.ci.transltr.io`), there are only two, "integrins" and "acetyl CoA carboxylase" (both from SemMedDB):

<img width="1126" alt="Screenshot 2023-08-18 at 9 08 56 AM" src="https://github.com/NCATSTranslator/Feedback/assets/5562107/3ac85ed5-9c60-4257-b7b3-23528df851b7">

In both of those cases, the result edges meet our publication count criteria for inclusion in KP results. 

I also note that in the linked result from the Translator UI, when I filter by "animals" in the text filter box and restrict to ARAX results, I see only one result: betamethasone.

I wonder if we _re-generated_ these results from the UI (using the CI version of Translator, of course), if that "betamethasone" result would go away. I wonder if the above result has been cached from a day or two ago when we had not yet deployed the new RTX-KG2 to CI (which we did yesterday afternoon). I've attempted to re-run that query but it is taking a long time.

Anyhow, at least as concerns the RTX-KG2 KP, I think that as of the new release (which is already on ITRB TEST and slated to roll out to ITRB Production hopefully soon), this problem should basically not occur, save for those two aforementioned edges.

And as concerns ARAX, it appears that ARAX (per se) contributed only one result graph containing "animals"; only one result from ARAX contained "animals" and, as I said above, I don't expect that result would occur if we were to re-run the Stickler Syndrome query in the CI Translator UI (a conjecture that I am trying to test but it is taking a long time).

**Comment by saramsey** [comment] 2023-08-21 21:54
ARAX is developing a blocklist of overly general concepts that will be applied at the ARA (or maybe KP?) level. I've requested our team to add "Animals" (`MESH:D000818`) to the blocklist. See [RTXteam/RTX issue 2069](https://github.com/RTXteam/RTX/issues/2069).

**Comment by saramsey** [comment] 2023-08-21 22:04
I've confirmed that in the latest version of the RTX-KG2 KP (on `kg2.test.transltr.io`), presumably due to improved SemMedDB filtering, only two results are returned from the aforementioned TRAPI query with "Animals":

<img width="304" alt="Screenshot 2023-08-21 at 3 04 08 PM" src="https://github.com/NCATSTranslator/Feedback/assets/5562107/3a2476ac-35c5-4644-8716-e4e97cffb720">

So we're down to only two problematic edges. And, as stated above, we are in the process of adding "Animals" to our "overly-general-concept blocklist" for ARAX/KG2 so that sould

**Comment by saramsey** [comment] 2023-09-21 14:30
I can confirm that `MESH:D000818` has been added to the ARAX answer blocklist of overly general concepts:
https://github.com/RTXteam/RTX/blob/8c435f02a1162982bbe4b0d13e1c5dd6d084ecc8/code/ARAX/KnowledgeSources/general_concepts.json#L90C23-L90C23

@sstemann can we close this one out?  My impression is that from a ARAX and RTX-KG2 standpoint, the underlying issue of "Animals" showing up has been addressed and we only have two underlying edges with `XXX-[part_of]->Animals` showing up anymore in RTX-KG2.

**Comment by uhbrar** [comment] 2023-09-21 16:11
I've also run the query again, and it looks like ARAGORN no longer returns that results. We do still have some other questionable results due to generic intermediate nodes, but we are currently working on that, and it is unrelated to this issue. I believe we can close this issue out now.

**Comment by saramsey** [comment] 2023-09-21 16:22
Thank you @uhbrar

**Closed** 2023-09-21 16:22 UTC
Labels: reasoning, architecture, transitive
