### ISSUE TITLE
antioxidants cause, prevent, and treat AD

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#13] opened 2022-10-05 20:11 UTC
## Steps to reproduce:
search for what drugs may treat AD, click on second row (Resveratrol)

## Screenshots:
![screenshot](https://raw.githubusercontent.com/TranslatorSRI/IssueScreenshots/main/screenshot_20221005201151291795.jpeg)

**Comment by sierra-moxon** [comment] 2022-10-05 20:15
antioxidants cause, prevent, and treat AD.
clicking on the "causes" relationship and examining the evidence that is tagged with the "causes" predicate:

(this seems like evidence for "treats")
"The findings in this review suggest that probiotics, prebiotics or synbiotics have potential as novel biological prophylactics in treatment of AD, due to their anti-inflammatory and antioxidant properties, their ability to improve cognition and metabolic activity, as well as their capacity of producing essential metabolites for gut and brain barrier permeability."


(this seems like evidence for "treats")
"Natural antioxidants enhance the power of physical and mental activities versus risk factors inducing progression of Alzheimer's disease in rats"
for this one again, we don't see anything in the UI to show that this was examined in rats vs. humans

**Comment by sierra-moxon** [comment] 2022-10-05 20:17
in another "causes" predicate evidence list:
"Conclusions: Our findings suggest that higher exposure to ascorbate, β-carotene, retinol, or urate **does not lower the risk of AD**. Replication Mendelian randomization studies could assess this further, providing larger AD case-control samples and, ideally, using additional variants to instrument each exposure." 

but this does not imply "causes AD" does it?

**Comment by sierra-moxon** [comment] 2022-10-05 20:25
<img width="1114" alt="Screen Shot 2022-10-05 at 1 19 18 PM" src="https://user-images.githubusercontent.com/4561292/194155317-2f239c5a-93fb-404c-9c81-66ba239353ca.png">

this statement says to me that Resveratrol increases Antioxidants (which are also increased by Cytokine) and that Cytokine causes AD.  The inclusion of Cytokine here is confusing to me.

**Comment by capasfield** [comment] 2023-01-13 17:53
https://arax.ncats.io/?r=6752ab77-ff70-4805-8f7c-c55d078b0a50

Andrew to run query and return results

**Comment by andrewsu** [comment] 2023-01-13 17:56
Note that it appears that the relationships between antioxidants and AD were reported by the ARAX-ARA and were originally reported by semmeddb.  I'd suggest closing this ticket in favor of other ongoing issues / discussions of how to handle semmeddb.

![image](https://user-images.githubusercontent.com/2635409/212387116-1e17da1e-b2b0-40dc-b594-24df37c42d5a.png)

**Comment by sstemann** [comment] 2023-03-09 16:27
@sierra-moxon i dont see your specific example anymore but for Alzheimers, I see Rivastigmine to Parkinson has causes, has adverse events, treats, and ameliorates edges.

i see Andrew's suggestion that this is semmed issue but for the Rivastigmine, the causes edge is coming from "sider" through hetio automat-robokop.  i dont know if sider is use semmed

https://ui.ci.transltr.io/results?l=Alzheimer%20Disease&t=0&q=562d7c4a-d5ab-497b-a56b-88a2ebd121c5

https://arax.ncats.io/?r=562d7c4a-d5ab-497b-a56b-88a2ebd121c5

![image](https://user-images.githubusercontent.com/38321826/224088196-4c457559-21d6-4f95-bea9-883753e0d5dc.png)

**Comment by sierra-moxon** [comment] 2023-03-17 16:47
from TAQA:
in previous examples, we agree that this kind of result is "fine" because it's an ML edge and the low rank means that it "might have issues" - this one is not ranked low.  Maybe it needs to be ranked lower? 
results from Sider not SEMMEDDB.  (database of side effects).

In general, this is ok - we can do an FAQ somewhere in the UI?  But showing something every time this happens is not that favorable for the UI team.  

from Tyler: Score distribution analysis could help us here -  0.4 vs. 0.7 vs. how many scores per team, might actually help disambiguate how highly this is ranked. 

from Andy: "poison is in the dose" -   towards a FAQ for this vs. labeling edges?   If for example, it says "upregulates and downregulates" that is an important paper to read, if we marked this as "weird" or "bad" this would be misleading for the user. 

from Matt: qualifiers would help; in side effects databases, the most prominent side effect is the drug that was taken.  Maybe because the drug didn't do its job (aspirin didn't cure my headache, so it's a side effect).  Maybe drop the side effect when it is equivalent to the indication?    When we have scores on edges (a harmonized score); can we add some sort of visual indicator that one edge is scored higher in the context of a path in the UI?  

from Chris B: this case has some extra strangeness; might need some changes from disease to Parkinson's.  some confusion in the data - each edge might come from the source and contradict itself. 

from Matt: the wider issue is that we need landscape analysis for every source.  different KPs are ingesting differently. 
clean data in = clean data out. harmonize how data is mapped to the model - do we need an ingest wg.  

TODO: first step is an FAQ.

**Closed** 2023-06-01 23:33 UTC
Labels: UI - feature request
