### ISSUE TITLE
I want to be able to see the evidence that estrogens *treat* Feingold Syndrome by clicking on a link and then seeing a summary and links to pub med articles. The NLP team at Stanford was working on a way to do this at one point. 

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#36] opened 2022-10-30 20:56 UTC

**Comment by sierra-moxon** [comment] 2022-11-18 00:17
Trying to reproduce:

- The first three fastest results returned do include "Estrogens, conjugated synthetic a" which may or may not be equivalent in this feedback to "estrogens" and I do see evidence with PubMed associations listed.

- When the rest of the results are returned, this result is however pushed far below 60 results (I paged through 3, 20 results sets to try and find it again but stopped at 60). 

It's not clear to me if this feedback means that "estrogen" should be first on the list of results (and it wasn't because it was pushed too far below the "fold" of the page), or if "estrogens" the role should be returned rather than a specific estrogen, or if there was a problem with the UI.  

If anyone remembers submitting this issue, could you help clarify?  :)

**Comment by sstemann** [comment] 2023-03-09 18:47
@sierra-moxon i'm not getting estrogen from CI, but of the results we are getting only about4 of 493 have 0 evidence.  I think we have a pretty good awareness of gaps in the evidence and i dont think this ticket is adding any value right now and suggest closing it.

**Closed** 2023-03-09 22:12 UTC
Labels: O&O issue, EPC
