### ISSUE TITLE
drug regulates gene is returning incorrect answers for two hop

### ISSUE THREAD

**Issue by sierra-moxon** [NCATSTranslator/Feedback#184] opened 2023-05-19 16:50 UTC
A drug that decreases something that increases the target is returned when asked for things that increase.  At the time of looking at it only improving agent had returned results.  

Result: Pubchem.compound:2958

http://transltr-bma-ui-dev.ncats.io/results?l=MET&t=1&q=83137311-7392-4d27-a3d6-c00fbbdba111

![Image](https://user-images.githubusercontent.com/55069176/239584673-e1ff0e12-21e9-479c-a88a-78e12b2bcd5c.png)

**Comment by sierra-moxon** [comment] 2023-05-19 16:55
From TAQA:
the second path has mismatch logic "don't decrease an increaser and call that chemical an upregulation of Met"
from Sui: will fix.   whether it is true or not is another question.

**Comment by brettasmi** [comment] 2023-05-22 17:52
@sierra-moxon , it's my guess that this is a case where one of the edges actually refers to a knockout gene experiment, thus changing the results in an unintuitive way if only looking at the predicate names.

We knew this would be a challenge to relate this information to the user when we implemented this logic pending a qualifier to make it clearer.

The UI isn't loading results for me right now, so I can't see what information is actually being displayed that might help the user understand this. I will keep trying.

**Comment by suihuang-ISB** [comment] 2023-05-22 18:08
Thanks Brett - tat is what I thought.  It has to do with translating the logics of causation - we have k.o. and overexpression which translates to _necessary_ vs _sufficient_ cause, and are not in biolink or exist as qualifier ....  We have not worked it out in detail. Let's revisit this at our Wednesday meeting.
BTW  these UI pk's also do not work for me (just reenter the original query freshly: "WHAT CHEMICAL UPREGULATES MET".

**Comment by suihuang-ISB** [comment] 2023-05-24 22:43
Hi Sierra - so we have pinpointed the source of the problem. The internal logics in imPROVING is correct. The two edges e1 , e2 are mapped to the "NET EFFECT" as shown in the table below. What causes the problem is that the "**GENE STATUS**" (* in the graph below) , namely, 'KNOCKOUT' or 'OVEREXPRESSION' as a qualifier for the predicate 'UP/DOWNregulates' that is in SPOKE gets lost.  This qualifier either is not in Biolink, or is not exposed to the user in UI...  Thus, "gene knockout causes increase..." (the gene is a repressor)  becomes "gene causes increase ..." = opposite meaning!
Brett may have more comments, and also ideas on at what level we shold fix that?. Thx

![image](https://github.com/NCATSTranslator/Feedback/assets/67438204/875caae7-656c-481b-8a85-557c915bde97)

**Comment by GregHydeDartmouth** [comment] 2023-06-05 17:14
Another example of wrong regulation semantics in multi-hops

My Query: What gene is upgregulated by [Tryptophan]
Entity Search [crat] or go to page 3
This result shows two paths:
-   Crat -- affected by --> Tryptophan
-   Crat -- has decreased activity of abundance of caused by --> Adgre5 -- has increased expression caused by --> Tryptophan

 path: https://ui.test.transltr.io/results?l=Tryptophan&t=3&q=ffe2e40a-cd45-41f1-932c-ec82d30f8415

 
![wrong semantics](https://github.com/NCATSTranslator/Feedback/assets/60626258/f39c04a5-f9cb-463c-a12a-ef806fbeaab7)

**Comment by brettasmi** [comment] 2023-07-20 01:55
@cbizon , this logic should be disabled for the time being.

In the medium-term, we are working with Sierra and Matt to put together qualifiers for overexpressed and knockout.

**Comment by sstemann** [comment] 2023-08-01 19:56
@sierra-moxon this one seems pretty good for Improving Agent - i did an entity search for decreased and filtered on Improving agent, and it looks like when that is used, it is with another decreased.  https://ui.test.transltr.io/results?l=Tryptophan&i=PUBCHEM.COMPOUND:6305&t=3&q=9fc6f21f-0eaa-4b9f-9b35-c2bfe924f2f9

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/7eb8be28-d728-4f44-9409-26eca0e239d6)

but when i switch to filter on ARAX, the first one doesn't look right
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/8a0d77a8-d679-46a7-a8c1-46ddc8307344)

not sure if this should get reassigned to team expander agent?

**Comment by sierra-moxon** [comment] 2023-08-01 20:16
@edeutsch - do you know which KP is providing STITCH data?

**Comment by edeutsch** [comment] 2023-08-01 20:25
looks like MolePro from the sources list:
![image](https://github.com/NCATSTranslator/Feedback/assets/12707718/b83e7bca-8159-436a-af05-38939d93ebfd)

**Comment by sierra-moxon** [comment] 2024-02-16 00:32
@vdancik - I think this is working now, do you agree?

**Closed** 2024-05-17 00:33 UTC
Labels: opposite of what I asked for
