### ISSUE TITLE
Treating pregnancy still allowed in intermediary node?

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#607] opened 2023-10-23 22:13 UTC
## Steps to reproduce:
MVP1 on Obstructive sleep apnea
search for Omega-3 fatty acids

**Comment by sandrine-muller-research** [comment] 2023-10-23 22:15
<img width="1038" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/22616936/c63c17e9-3658-4d47-8df1-a4ecade83d5f">

**Comment by sandrine-muller-research** [comment] 2023-10-23 22:17
To note that this path seems to be low quality.

**Comment by andrewsu** [comment] 2024-01-23 19:59
The `omega-3 fatty acids` - `treats` - `Pregnancy` is coming from ARAX via RTX-KG2.  assigning to @saramsey and @dkoslicki to assess...

https://ui.transltr.io/main/results?l=Obstructive+Sleep+Apnea+Syndrome&i=MONDO%3A0007147&t=0&r=0492963e&q=a3a387b0-6d9a-4ec1-940d-de0157d56915
https://arax.ci.transltr.io/?r=a3a387b0-6d9a-4ec1-940d-de0157d56915

![image](https://github.com/NCATSTranslator/Feedback/assets/2635409/fdab5ce8-8b19-4ff8-afa9-39e56dd2337e)

**Comment by saramsey** [comment] 2024-01-24 18:55
This edge comes from ChEMBL:
```
{
  "predicate": "biolink:treats",
  "primary_knowledge_source": "infores:chembl",
  "domain_range_exclusion": "False",
  "publications_info": "{}",
  "kg2_ids": [
    "CHEMBL.COMPOUND:CHEMBL4298065---biolink:treats---None---None---None---MESH:D011247---identifiers_org_registry:chembl.compound"
  ],
  "subject": "CHEMBL.COMPOUND:CHEMBL4298065",
  "id": "30366584",
  "object": "UMLS:C0032961"
}
```
Could someone please help me to understand, what specifically is wrong about this edge?  Please pardon my ignorance. Thanks.

**Comment by andrewsu** [comment] 2024-01-24 19:05
Apologies for the brief post yesterday -- we were moving quickly in the TAQA session.  I think the original user thought that anything treating pregnancy was odd, and we just wanted to identify and tag the source team to assess whether everything was working as intended (and not some error in data transformation/ingestion).  If that's the case here and you don't think there's anything to fix (I'd agree with that), then I think it would be safe for you to close the issue....

**Comment by sierra-moxon** [comment] 2024-01-29 18:55
@MarkDWilliams - were you thinking that the ARS blocklist would also block intermediate nodes?  
Is this a use case you can look into? 

I agree with @sandrine-muller-research, that while omega-3-fatty-acids are worth taking in pregnancy to improve the outcome for the baby, we don't want this answer returned even as an intermediate hop for MVP1 queries. 

I would also put this on the list for predicates WG -- the idea that something is beneficial to the baby so you should take it in pregnancy doesn't really fall into the hierarchy of "treats" predicates we've analyzed.

**Comment by sstemann** [comment] 2024-04-09 13:30
@sierra-moxon my understanding is the blocklist is not specific to a query/input but rather by blocking pregnancy it would be blocked for all queries - is that that request here?  this result still appears from ARAX

https://arax.ncats.io/?r=49894270-eaf0-4b20-9206-0486beb0c640

**Comment by sierra-moxon** [comment] 2024-04-10 16:19
@andrewsu @saramsey @sstemann  - maybe we should discuss further?  I can tag this as a large-group TAQA review ticket if that helps.

here are my justifications for this being an incorrect result:

1.  "pregnancy" in my opinion, is not a disease or a phenotypic feature (which means this is violating a Biolink range constraint).  Neither Mondo, nor HP ontologies have "pregnancy" as a term.

2. but, let's say we were to make "pregnancy" a disease or phenotypic feature by getting the term added to one of those ontologies, in this edge, we're not talking about treating pregnancy per se.  Instead, we're talking about giving a ChemicalEntity to the carrier of a fetus to aid in the development of a fetus, and/or about preventing a phenotypic feature or disease state caused by (or correlated with) pregnancy in the person carrying the fetus.  

"Adequate consumption of omega-3 fatty acids is vitally important during pregnancy as they are critical building blocks of fetal brain and retina. Omega-3 fatty acids may also play a role in determining the length of gestation and in preventing perinatal depression." https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3046737/#:~:text=Adequate%20consumption%20of%20omega%2D3,and%20in%20preventing%20perinatal%20depression.


We could say:
```
subject: omega3 (ChEBI)
predicate: preventative_for_condition
object:  perinatal_depression (MONDO)
```

and/or

```
subject: omega3 (ChEBI)
predicate: contributes_to
object: brain development (Uberon/GO)
temporal_context_qualifier: fetus 

subject: omega3 (ChEBI)
predicate: contributes_to
object: retina development (Uberon/GO)
temporal_context_qualifier: fetus 
```

If we can go beyond all of that, this two-hop is a fairly large leap and I would immediately discount it as a user.

**Comment by sierra-moxon** [comment] 2024-05-17 14:44
I no longer see pregnancy in the results (I checked for the Omega-3 Fatty Acids keyword and it is no longer found).  I am closing this as complete! :)

**Closed by sierra-moxon** 2024-05-17 14:44 UTC
Labels: blocked answers, wrong path, predicate pattern, deferred/will not fix this release
