### ISSUE TITLE
expose deeper provenance than components of Translator

### ISSUE THREAD

**Issue by remontoire-pac** [NCATSTranslator/Feedback#282] opened 2023-06-06 14:27 UTC
![image](https://github.com/NCATSTranslator/Feedback/assets/2120526/9d687640-8fd2-4c67-9687-4c611a1a06d2)

Which sources were used by these Translator components?
Curiously, I had the opposite comment elsewhere, preferring "ChEMBL (MolePro)" to simply "ChEMBL".

**Comment by sierra-moxon** [comment] 2023-06-07 14:48
from TAQA:
the extra information requested is captured in the support graphs in ARAX.  
this is shown in the PATHs section - the treats edge from ARAX shows none of the underlying publications in the support graph
perhaps tag the edges with "this is an inferred edge" and then show the support graphs.

**Comment by remontoire-pac** [comment] 2023-06-11 03:25
To clarify, I'm hoping that we can (in general) expose: (1) original
source; (2) KP; (3) ARA within the UI. I saw examples this week that leaned
in both directions of omission -- can we make it a priority to expose this
basic level of source name for all UI displays? I understand that "deeper
down" we are still working on how precisely to provide EPC, so for now I'm
just talking about the UI to be exposed this summer. PAC

**Comment by edeutsch** [comment] 2023-06-15 21:26
I had a quick peek in the JSON:
https://arax.ci.transltr.io/api/arax/v1.4/response/98042ea4-3abe-4da1-8775-018cd6bcdc20

and it appears that there are a few edges like this:
```
        "80995b128a9a": {
          "attributes": [
            {
              "attribute_type_id": "biolink:has_numeric_value",
              "original_attribute_name": "weight",
              "value": 1,
              "value_type_id": "EDAM:data_1669"
            },
            {
              "attribute_source": "infores:pubchem",
              "attribute_type_id": "biolink:original_knowledge_source",
              "attributes": [],
              "original_attribute_name": "biolink:original_knowledge_source",
              "value": "infores:pubchem",
              "value_type_id": "biolink:InformationResource"
            }
          ],
          "object": "PUBCHEM.COMPOUND:135398739",
          "predicate": "biolink:chemically_similar_to",
          "qualifiers": [],
          "sources": [
            {
              "resource_id": "infores:aragorn",
              "resource_role": "aggregator_knowledge_source",
              "source_record_urls": [],
              "upstream_resource_ids": [
                "infores:molepro"
              ]
            },
            {
              "resource_id": "infores:molepro",
              "resource_role": "aggregator_knowledge_source",
              "source_record_urls": [],
              "upstream_resource_ids": []
            }
          ],
          "subject": "PUBCHEM.COMPOUND:135398739"
        },
```

Edge 80995b128a9a declares that PUBCHEM.COMPOUND:135398739 is biolink:chemically_similar_to to PUBCHEM.COMPOUND:135398739.

But edge 80995b128a9a does not appear to be referenced anywhere else in the document, so that's probably why it doesn't show up anywhere. An orphaned edge. Maybe it's supposed to be part of a support graph that's not actually there? I don't know.

We should probably not gloss over the fact that this TRAPI document fails validation on numerous grounds, including:
```
    "error.knowledge_graph.edge.provenance.missing_primary": {
      "PUBCHEM.COMPOUND:10954115--biolink:chemically_similar_to->PUBCHEM.COMPOUND:10954115": null,
      "PUBCHEM.COMPOUND:135398739--biolink:chemically_similar_to->PUBCHEM.COMPOUND:135398739": null,
      "PUBCHEM.COMPOUND:16137271--biolink:chemically_similar_to->PUBCHEM.COMPOUND:16137271": null,
      "PUBCHEM.COMPOUND:871--biolink:chemically_similar_to->PUBCHEM.COMPOUND:871": null
    },
```

**Comment by sierra-moxon** [comment] 2023-07-03 15:15
@sandrine-m - I think I mischaracterized this ticket originally, and I just found it again this morning while cleaning up some infores tickets.  Is this something you or @vdancik or Larry could look into?  (there seems to be an orphaned edge)

**Comment by sandrine-m** [comment] 2023-07-21 18:00
Thank you! Sorry @sierra-moxon this issue fell of my radar. I have just asked Larry if he could have a closer look to MolePro KG. We will keep you posted.

**Comment by codewarrior2000** [comment] 2023-07-24 12:56
@sierra-moxon I will try to do some troubleshooting to isolate the cause of the orphaned edge.

**Comment by sandrine-m** [comment] 2023-08-08 10:58
@cbizon would you be able to confirm? Thank you!

**Comment by cbizon** [comment] 2023-08-11 19:50
We did have a bug like this (missing edges) in an earlier version.  It should be corrected now.

But I think that the real request for this issue is understanding the relationships between edges in the UI.   The ARAs are listed as the sources of those edges because the ARAs made those edges.  There is no KP that made the edges.   Looking in the TRAPI for any creative edge will look the same.  The edge will then point to a support_graph which will have more edges which will have the KP infores. 

So assuming that the ARAGORN issue is really fixed (checking now), this is a UI issue.

**Comment by sandrine-m** [comment] 2023-08-24 13:48
Following @cbizon recommendation, I have retriaged the issue. I searched related issues and found #342 . I have updated Milestone there as well. Please feel free to change any change I made. Thank you

**Comment by sierra-moxon** [comment] 2024-05-17 01:21
closing as complete wiht our efforts to the infores wiki pages.

**Closed by sierra-moxon** 2024-05-17 01:21 UTC
Labels: UI - display
