### ISSUE TITLE
after choosing "FDA Approved Tag", add drug name to filter box, FDA status facet values show ones when should be zero

### ISSUE THREAD

**Issue by sierra-moxon** [NCATSTranslator/Feedback#439] opened 2023-07-20 22:13 UTC
Per @Genomewide  - please make a ticket for UI for this:

from DM testing session for 
Inclusion body myositis ([ci](https://ui.ci.transltr.io/results?l=Inclusion%20Body%20Myositis&i=MONDO:0007827&t=0&q=39d68464-4792-4ead-b505-cfd1bbaa9c5e), [test](https://ui.test.transltr.io/results?l=Inclusion%20Body%20Myositis&i=MONDO:0007827&t=0&q=f409140a-52c1-426b-a85a-2705707bdd98))

click on "FDA Approved" check box
filter for Bimagrumab

noticed the FDA Status facet values.

<img width="1460" alt="Screen Shot 2023-07-20 at 11 58 59 AM" src="https://github.com/NCATSTranslator/Feedback/assets/4561292/23985034-c477-4d42-ac6e-bdb2b8865477">

**Comment by dnsmith124** [comment] 2023-07-21 16:05
This does have the appearance of a bug, but I think this is actually working correctly per the rules that govern how the facets work. 

Because the facets function based on an intra-OR/inter-AND ruleset, selecting a single FDA Status facet does not prevent the others from displaying counts if they have results that would display when combined with any other selected facets. The two facets here with counts apply for the filtered string, so they show up. 

If you were to enable another facet, say the minimum evidence facet with a value higher than 1 (since Bimagrumab only has a single source and no pubs), the 2 FDA facets that are displaying would go away. 

This is the intended behavior with the system as far as I can tell (aside from the duplicate "Show less" buttons, which I can't seem to recreate).

**Comment by dnsmith124** [comment] 2023-07-21 16:16
I take back that last statement, I was able to recreate the issue with the show less buttons and have implemented a fix in a local branch.

**Comment by dnsmith124** [comment] 2023-08-07 17:16
Confirmed resolved on test

closing.

**Closed by dnsmith124** 2023-08-07 17:16 UTC
Labels: UI - display
