### ISSUE TITLE
Help - Workspace and Filters

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#532] opened 2023-09-12 16:41 UTC
1.  I'd really love one of these Help Topics to be called Workspace.  I feel like step 8 in "Review and Identify Favorite Results" is a bit buried and then "Focused Analysis of the Top Results" doesnt really tell me much. 

3. Seems like there should be a topic on Filters

**Comment by gprice1129** [comment] 2023-10-04 21:59
@sstemann is the solution above good?

**Comment by sstemann** [comment] 2024-02-14 16:25
yep sounds good!

**Comment by sstemann** [comment] 2024-03-28 21:35
when will the help be updated?
<img width="551" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/3415d19c-421d-4bec-bd59-fcfaf0605720">

**Comment by Genomewide** [comment] 2024-03-28 21:36
This sprint.

**Comment by sstemann** [comment] 2024-04-24 17:35
is this considered the final?
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/ab8e1c53-e325-4783-b8c4-0d735322ac89)

there's also a lot here;  https://ui.transltr.io/demo/review-and-identify that seems like could be broken out

**Comment by Genomewide** [comment] 2024-04-25 22:29
I agree. I will update our internal tracking ticket.

**Comment by sstemann** [comment] 2024-05-28 17:54
with all the changes to facets this i think there are updates here

**Comment by sierra-moxon** [comment] 2024-07-19 16:22
from TAQA:  this is a duplicate of another ticket, @dnsmith124 - seems correctly labeled but will reconcile.

**Comment by sstemann** [comment] 2024-08-02 18:03
@dnsmith124 i dont see any changes in CI or Test, should the label be updated?

**Comment by dnsmith124** [comment] 2024-10-18 17:57
The 2 action items from this ticket have been deployed to prod:
1. Workspace help topic added
2. Content added for facets to the Review and Identify Favorite Results page [here](https://ui.transltr.io/review-and-identify)

An upcoming interactive tutorial will also further address this issue, but for now I think we can consider this matter resolved.

**Closed by dnsmith124** 2024-10-18 17:57 UTC
Labels: UI - feature request, Guppy (Sprint 5) - due Aug 23 in CI
