### ISSUE TITLE
Questions about EPC - KS as Primary and Aggregator? 

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#704] opened 2024-02-01 18:44 UTC
I ran the query, in the Test UI, MVP1 > atrial fibrillation:  https://ui.test.transltr.io/main/results?l=Atrial%20Fibrillation&i=MONDO:0004981&t=0&r=0&q=cb620c3f-8792-442b-a5c2-dee8dfb95d46
- take a look at Sotalol - looks good in the UI
- 
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/679ff79d-f3c8-4061-92fd-b1f5c65a7c91)

I viewed the results in ARAX: https://arax.ncats.io/beta/?r=cb620c3f-8792-442b-a5c2-dee8dfb95d46

In the ARAX Result Set I noticed that this edge has:
- attribute infores: drugcentral
- primary ks: chembl
- aggregator ks: chembl
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/504ac0b5-18ea-4ddf-9474-d0a5d771dab2)

which is from SPOKE
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/4ec56895-ef41-4601-8b4e-ff56ccd50377)

**Comment by edeutsch** [comment] 2024-02-01 18:49
And I note that ARAX got this edge from SPOKE, so I think this is a question for the SPOKE maintainers..

**Comment by sierra-moxon** [comment] 2024-02-23 17:22
from TAQA:
Matt: in this case, Chembl is a PKS, maybe not an AKS.
if there are data in Chembl that are created based on another source, you could include that source in the "supporting data source" attribute. It might be that we need the clinical KP to replace Chembl in general throughout Translator (this is longer term, in the short term Chembl would still be the source here). 

Sui: It's difficult to tell what is an inference.  clinical trial == treatment (hypothesis).  Chembl also has indications (FDA approval for anything).  everything in clinical trials is inference. 

Matt: with the treats refactor, we are trying to write edges that are more in line with their sources, (e.g. "in clinical trials" assertion vs. "treats" assertion).  We can also make "treats" _predictions_ (inferences) -- the way we do this is still in discussion but likely via the CQS. 

Sui: what is the predicate for a phase 2 CT?  Matt: "treats" but knowledge level = "predication" and inference/predication are synonymous in our syntax.  The other important part here is that we still create the foundational edge - the "in clinical trial" predicate-labeled edge. (this comes through to the UI in the aux graph or supporting studies attribute, TBD).

**Comment by brettasmi** [comment] 2024-02-28 22:26
In this case, the assertion comes from both drugcentral and chembl and is resolved into a single edge in SPOKE. We have some code that tries to resolve these cases when they occur, but it appears that there is a bug. I'll take a look.

**Comment by brettasmi** [comment] 2024-03-06 03:10
@sierra-moxon , as part of the treats refactor work, I confirmed the following about SPOKE:
- ChEMBL is the primary source of "treats" information via its indications section
- DrugCentral is mostly used to annotate the edges with additional information, the provenance of which is captured in attribute sources. However, these "treats" assertions do exist in DrugCentral's indications table, which SPOKE accesses as part of its annotation process

As such, in all cases where SPOKE merges information from ChEMBL and DrugCentral, I plan to make ChEMBL the primary source and DrugCentral a supporting data source to resolve this issue. Does this modeling make sense to you?

Where appropriate, the modeling changes under the treats refactor, but the general logic in the above statement will still hold.

**Comment by mbrush** [comment] 2024-03-06 21:14
Hi Brett. Thanks for the clarification.  I think the convention for aggregators like SPOKE is that if there are two separate sources that report "Drug X treats Condition Y" (here, Drugbank, and Chembl), then the SPOKE should maintain separate edges with the appropriate primary source for each.  Merging of these separate edges is not something that happens until things pass to the ARS or UI. @uhbrar @sierra-moxon can you confirm this is the case?

If you just want to annotate the nodes or edges in Chembl-derived 'treats' edges with info from Drug-Central, I assume this info would live in Attribute objects on the nodes/edge. And here, the fact that the annotated info came from DrugBank should be captured in the `attribute_source` field of the Attribute object.  So each piece of info pulled form Drugbank can be specifically attributed to them. No need to annotate the edge directly as having DrugBank as a supporting_data_source. This is not really consistent with the meaning or intended use of this term.  

Happy to talk this through with you on a short call Brett.

**Comment by brettasmi** [comment] 2024-03-06 22:03
Thanks @mbrush , I will remove DrugCentral from the EPC for these edges, only exposing it where appropriate in the `attribute_source` field.

**Comment by sstemann** [comment] 2024-04-01 15:37
@mbrush @brettasmi i'm not sure i followed what it should look like - but now we have this:

Inferred Edge:
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/deae039e-f630-48bb-ad61-a99286415b16)

Support Graph of that Edge:
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/e5e3bbf0-3590-4e83-ba26-b1ac252ef558)

UI:
<img width="695" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/eb06208a-5e89-4fc9-acdc-3905f52cd404">

I feel like something has gone askew.  I never see the edge in clinical trials in the UI.  I dont see any CT #s in the Improve support graph for the edge so I dont know what's going on here anymore
<img width="737" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/7970d340-b9aa-4308-a376-25ed15d51ec3">

**Closed** 2024-08-14 18:33 UTC
Labels: EPC
