### ISSUE TITLE
Missing ChEBI roles

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#611] opened 2023-10-23 23:52 UTC
## Steps to reproduce:
MVP1 on Familial Pityriasis Rubra Pilaris
submit by @sandrine-muller-research

**Comment by sandrine-muller-research** [comment] 2023-10-23 23:54
Why are the ChEBI roles not showing in the page? I have a hard time to believe that on 1215 compounds non of them is annotated, but I could be wrong.
<img width="267" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/22616936/a8f18bca-021c-464b-8dfd-dde059cfb9f5">

**Comment by gprice1129** [comment] 2023-12-05 21:07
Hi @sandrine-muller-research. This is due to the annotation service failing for some reason. The UI has no recourse when this occurs other than not to show the facets. In the future we would like to alert the user when something like this occurs.

**Comment by andrewsu** [comment] 2023-12-05 21:14
@gprice1129 if you have any more details on what specific calls to the annotation service are failing, I can pass it along to that team (since @newgene is traveling at the moment)...

**Comment by sandrine-muller-research** [comment] 2023-12-07 08:35
FWIW I had the same issue again today on this query:
https://ui.ci.transltr.io/main/results?l=Hiv-associated%20Nephropathy&i=MONDO:0005798&t=0&q=f6427adc-167a-4993-9d00-3135aac1806d

**Comment by gprice1129** [comment] 2024-02-01 20:23
I'm going to close this because the root cause is captured in other tickets. Please reopen and comment if you feel strongly.

**Closed by gprice1129** 2024-02-01 20:23 UTC
Labels: UI - display
